### ISSUE TITLE
URL shortening link not very obvious

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#1000]
Icon to get the link for a query is not very obvious. Perhaps needs to be bigger, or use 'link' icon rather than the current one?

**Comment by nclopezo** [comment]
It now appears on the search bar
<img width="1402" alt="Screen Shot 2019-03-29 at 14 39 12" src="https://user-images.githubusercontent.com/1944922/55240323-926c7500-5230-11e9-932e-544d546a68d8.png">
