### ISSUE TITLE
Moelcular formula incorrect

### ISSUE THREAD

**Issue by baoilleach** [chembl/GLaDOS#1015]
Hi there. The molecular formula for "Br-" is not "Br-CH3". See under "Molecular Formula" at https://www.ebi.ac.uk/chembl/beta/compound_report_card/CHEMBL11685/

**Comment by agaulton** [comment]
Can we check where this field comes from? As it's correct in the database compound_properties table..

**Comment by nclopezo** [comment]
Note for me, it's also correct in elasticsearch:
https://www.ebi.ac.uk/chembl/glados-es/chembl_molecule/_doc/CHEMBL11685
it must be an error in the formula parsing.

**Comment by nclopezo** [comment]
comment: the formula doesn't need to have subindexes

**Comment by nclopezo** [comment]
This is fixed now:
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL11685/
