### ISSUE TITLE
URL without trailing backslash gives Internal Error Message

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#1031]
Why does the url: https://www.ebi.ac.uk/chembl/beta  give me an Internal Server Error message, while 
https://www.ebi.ac.uk/chembl/beta/  (with a final backslash) leads to the correct page? It seems a bit odd to me? Can it be corrected at some point, please?

![screenshot 2019-01-31 at 17 14 41](https://user-images.githubusercontent.com/32895834/52071843-bc305500-257b-11e9-9ee4-b06cc2150fd3.png)

**Comment by nclopezo** [comment]
Hi Fiona, 

We fixed this when we did the switch, it should work now.

**Comment by agaulton** [comment]
Looks good to me now.
