### ISSUE TITLE
Some reference documents in metabolic schemes are incorrect

### ISSUE THREAD

**Issue by apbento** [chembl/GLaDOS#1036]
For some compounds with metabolic schemes, the reference for the metabolic conversion (i.e. the document displayed when we click on the edges) is incorrect.

Take, for example, compound CHEMBL1233. Looking at the conversion of Carisoprodol (CHEMBL1233) into Hydroxymeprobamate (CHEMBL3706481):

- in the old interface, the reference for that conversion is document CHEMBL3706456
- in the new interface, the reference is document CHEMBL3544494

Here are some screenshots that show this:
![screenshot 2019-02-14 at 12 27 50](https://user-images.githubusercontent.com/9975206/52801923-ccb1f680-3076-11e9-896d-375401e77433.png)
![screenshot 2019-02-14 at 12 28 41](https://user-images.githubusercontent.com/9975206/52801939-d0de1400-3076-11e9-92c5-ec35e98c871d.png)

Looking at the web services or elastic search, it doesn't look obvious where the problem comes from.

**Comment by nclopezo** [comment]
I checked and the document ChEMBL ID is actually missing from the response in elasticsearch. I created this issue to add it https://github.com/chembl/GLaDOS-es/issues/38.

**Comment by nclopezo** [comment]
As we discussed (https://github.com/chembl/GLaDOS-es/issues/38#issuecomment-547492790). The document was just removed from the edge description:
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL25/
