### ISSUE TITLE
missing web link

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#1038]
1. Link to ChEMBL blog is not correct - 
https://chembl.gitbook.io/chembl-interface-documentation/about#staying-in-touch
See missing link when clicked on 'group blog' 
![screenshot 2019-02-19 at 17 34 13](https://user-images.githubusercontent.com/32895834/53035120-9f958780-346c-11e9-9597-f20a87f90c4d.png)

**Comment by nclopezo** [comment]
This has been fixed.

**Comment by nclopezo** [comment]
Hi Fiona,
This should be fixed now.
