### ISSUE TITLE
A CSV/TSV file exported from beta site includes control characters

### ISSUE THREAD

**Issue by kzfm** [chembl/GLaDOS#1042]
The file downloaded from the following link contains controle characters like this "^@".

https://www.ebi.ac.uk/chembl/beta/g/#browse/compounds/filter/_metadata.related_documents.chembl_ids.%5C*%3ACHEMBL1141975

[test.txt](https://github.com/chembl/GLaDOS/files/2930667/test.txt)

```
"^@C^@h^@E^@M^@B^@L^@ ^@I^@D^@"^@,^@"^@N^@a^@m^@e^@"^@,^@"^@S^@y^@n^@o^@n^@y^@m^@s^@"^@,^@"^@T^@y^@p^@e^@"^@,^@"^@M^@a^@x^@ ^@P^@h^@a^@s^@e^@"^@,^@"^@M^@o^@l^@e^@c^@u^@l^@a^@r^@ ^@W^@e^@i^@g^@h^@t^@"^@,^@"^@T^@a^@r^@g^@e^@t^@s^@"^@,^@"^@B^@i^@o^@a^@c^@t^@i^@v
^@i^@t^@i^@e^@s^@"^@,^@"^@A^@l^@o^@g^@P^@"^@,^@"^@P^@S^@A^@"^@,^@"^@H^@B^@A^@"^@,^@"^@H^@B^@D^@"^@,^@"^@#^@R^@O^@5^@ ^@V^@i^@o^@l
^@a^@t^@i^@o^@n^@s^@"^@,^@"^@#^
```

**Comment by nclopezo** [comment]
The files are encoded as 'utf-16-le' to avoid some issues with Excel. In vim you can use ':e ++enc=utf16le' to hide those characters, other editors can hide them automatically. 

Is this encoding causing trouble to some analysis that you run afterwards?

@agaulton

**Comment by kzfm** [comment]
Thank you for your information, I didn't notice that was the encoding problem.

I don't have any problem with this but was just wondering because I couldn't display it properly with vim nor less/more command.

@fmkz___
