### ISSUE TITLE
Add additional filters to the heatmap visualisation

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#1043]
At present the heatmap allows filtering on the rows only. However, I have had several discussions with users recently where it would be very useful to filter for both rows and columns. e.g. 
https://www.ebi.ac.uk/chembl/beta/g/#search_results/all/query=P02675 allows filtering on the targets, but I would like to filter both the targets (rows) and the compounds (columns) (e..g. find max_phase=4 compounds only). 

Similarly for this heatmap, I would like to filter on the row (compounds) as well as the targets (columns) https://www.ebi.ac.uk/chembl/beta/g/#browse/drugs/filter/%5Bobject%20Object%5D

**Comment by nclopezo** [comment]
We have already discussed this. Actually, today we had a meeting about the new target prediction models and that they could be presented as a heatmap. Anyway, while this progresses, I will prepare the heatmap to be more generic and more robust (support more data and configurations). It is in the plans so I will close this issue.
