### ISSUE TITLE
Question mark in compound report card by "Max Phase"

### ISSUE THREAD

**Issue by milar4** [chembl/GLaDOS#105]
There is a blue circle with a white question mark inside. If you click there it explain what Max Phase is. 
From my point of view the question mark there could be a little misleading making users think that the information by "Max Phase" is questionable. 
Could we have a different symbol (for example an "i" from information) or a smaller one in a different position (perhaps by "Max Phase"  instead of at the end of the line.

Thank you,
Mila

**Comment by nclopezo** [comment]
This has been fixed, the icon has been changed (https://github.com/chembl/GLaDOS/commit/5b50620c13858339a7efa71aa190d2f6f0a5a1c2). 
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL59/
The description will be changed according to what is stated in (https://github.com/chembl/GLaDOS/issues/255)

**Comment by mnowotka** [comment]
Thanks!
