### ISSUE TITLE
Can't download drug indications

### ISSUE THREAD

**Issue by apbento** [chembl/GLaDOS#1050]
After selecting "Select All", I've tried to download all the drug indications data from https://www.ebi.ac.uk/chembl/beta/g/#browse/drug_indications and got the following error: 'There was an error: Internal Server Error. Please try again later.'

I even tried selecting fewer indications and I still got the same error.

**Comment by nclopezo** [comment]
Hi Patricia, 

The errors in these downloads were fixed. You can try again now.

**Comment by exocyclic** [comment]
Hello I am unable to download all drug information from https://www.ebi.ac.uk/chembl/g/#search_by_ids_results/SEARCH_BY_IDS-_veucErXlfWSutIo-6jvZesPcPKSbf1DrvacKZf9fP8= 
 
I get the error: got the following error: 'There was an error: Internal Server Error. Please try again later.'
can someone please help> Thank you.

**Comment by nclopezo** [comment]
Hi @exocyclic

It looks like a clean up task deleted part of the results of the search that we create internally. I deleted the search so you can try again. Could you also please send us the list of IDs that you entered? 

You can also write an email to chembl-help@ebi.ac.uk.
