### ISSUE TITLE
max phase for indication on drug indications

### ISSUE THREAD

**Issue by apbento** [chembl/GLaDOS#1051]
The max phase for indication in drug indications should be the 
MAX(max phase of the parent, max phase of the child) for a given indication.

At the moment it seems that the max phase for indication is the max phase of the parent for that indication.

See, for example, AFATINIB (molecule_chembl_id: CHEMBL1173655) AND efo_term:"non-small cell lung carcinoma") in https://www.ebi.ac.uk/chembl/beta/compound_report_card/CHEMBL1173655.
In this case, the max_phase for indication should be 4, since its child AFATINIB DIMALEATE (molecule_chembl_id: CHEMBL2105712) has been approved for that indication.

**Comment by apbento** [comment]
Same issue on drug mechanisms.
See for example PIXANTRONE (CHEMBL167731): https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL167731/.
It's a max_phase 4 drug, but it shows max_phase 3 in mechanism of action, presumably due to its salt PIXANTRONE DIMALEATE (CHEMBL2103844) being a phase 3 candidate.

**Comment by nclopezo** [comment]
After asking @juanfmx2, this needs a fix in the indexation. Unfortunately it can't be fixed from the interface. I created this issue in the elasticsearch project https://github.com/chembl/GLaDOS-es/issues/36

**Comment by juanfmx2** [comment]
This has been fixed! :)
