### ISSUE TITLE
Defined stereo at tetrahedral center with two hydrogens

### ISSUE THREAD

**Issue by baoilleach** [chembl/GLaDOS#1072]
Congrats on a new release.

With respect to https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2068760/, the stereo should not be defined at the tetrahedral center with two hydrogens. Perhaps a check should be added when converting deuteriums to default hydrogen.

**Comment by nclopezo** [comment]
Replaced by https://github.com/chembl/chembl_data/issues/133
