### ISSUE TITLE
Hide/remove/fix word cloud on document page

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#1073]
I think we shouldn't show the word cloud section if there is not data because it looks odd:
https://www.ebi.ac.uk/chembl/document_report_card/CHEMBL3301472/

In general, we should consider whether to remove altogether or redo it another way, as most of the ones I've seen are not very useful e.g.,
https://www.ebi.ac.uk/chembl/document_report_card/CHEMBL1926502/

Also, clicking on the words doesn't show related documents as the URL is wrong e.g., 
https://www.ebi.ac.uk/documents_with_same_terms/dose-proportional%20pharmacokinetics

(related to issue #1032)

**Comment by nclopezo** [comment]
I would really prefer to remove it if it isn't very useful right now. It is less code that can break and we will have to maintain. And we can focus on other things.

**Comment by eloyfelix** [comment]
let me know what you finally decide about this one as I have some code generating the data for this widget

**Comment by agaulton** [comment]
Let's remove the word cloud section

**Comment by eloyfelix** [comment]
I updated document_processes so related tables won't be generated anymore. 
Also removed the two related tables (doc_2_term and doucument_terms) from schema cleanup whitelist.

**Comment by nclopezo** [comment]
After fixing some issues with the deployment process this is now finally deployed:
https://www.ebi.ac.uk/chembl/document_report_card/CHEMBL1926502/
The word cloud has been removed.
