### ISSUE TITLE
Drug_indications edit query string returning error message

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#1084]
Hello,
Can you tell me how to use the edit_query string for the drug_indications page, please? When I type this into the edit query field: 
parent_molecule_chembl_id:CHEMBL79
or 
molecule_chembl_id:CHEMBL79
or 
molecule_chembl_id:(CHEMBL79 OR CHEMBL635)
or 
parent_molecule_chembl_id:(CHEMBL79 OR CHEMBL635)

Then the result is an error message: e.g. 
https://www.ebi.ac.uk/chembl/g/tiny/pjltFnYamA8dS3aBgmx5Ng==

The user question is "how do I find drug indications for a set of known drugs". 
Thanks, 
Fiona

**Comment by nclopezo** [comment]
Hi Fiona, 

The correct query is 'parent_molecule.molecule_chembl_id:(CHEMBL79 OR CHEMBL635)

See:
https://www.ebi.ac.uk/chembl/g/tiny/adgX6OirSMz0ENYsHJ9ePg==

This gives me an idea, we can add a small clickable link to get the full property name for every column.

**Comment by nclopezo** [comment]
https://github.com/chembl/GLaDOS/issues/1085

**Comment by FionaEBI** [comment]
Dear David, 
Yes - it would be very helpful to know what field I need to search for in the edit_query string. At the moment it’s as clear as mud to me (!) - hence I’ve tried various options until something worked…
Thanks for your help!
Fiona
