### ISSUE TITLE
No hyperlinks on bioactivity view

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#1086]
Noticed that the CHEMBL_IDs for molecules, assays, targets, documents on the activities view are not hyperlinked to the report cards.

Also should we have images of the molecules?

**Comment by anne123** [comment]
This is a critical bug to fix.  It was also mentioned to me by a user at the meeting yesterday

**Comment by nclopezo** [comment]
This is fixed now:
https://www.ebi.ac.uk/chembl/g/#browse/activities
