### ISSUE TITLE
Links to NTD sets not working please fix

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#1092]
for example https://chembl.gitbook.io/chembl-ntd/downloads/deposited-set-1-gsk-tcams-dataset-20th-may-2010

This is the error 
![image](https://user-images.githubusercontent.com/3308733/55634937-72e8c580-57b7-11e9-80ef-d5587e64ba03.png)

The files do seem to be in the correct location they just aren't seen from the gitbook URL.

**Comment by anne123** [comment]
ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLNTD/set1_gsk/chemblntd_all.sdf.gz

**Comment by agaulton** [comment]
FYI I think this is a Safari issue rather than a ChEMBL issue - I get this a lot (on various ftp sites) but it works fine in Firefox/cyberduck. Not sure of cause though...

**Comment by nclopezo** [comment]
I will close this issue since we can't fix it from our side.
