### ISSUE TITLE
Missing information when downloading items

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#1105]
If you compare the fields you get when you download the drugs between the old interface (https://www.ebi.ac.uk/chembl/old/drugstore) and the new one (https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/_metadata.compound_records.src_id%3A13), you will see some important ones are missing (canonical_smiles, drug_type...)

**Comment by nbosc** [comment]
related to #942

**Comment by nclopezo** [comment]
I am creating this spreadsheet:
https://docs.google.com/spreadsheets/d/10GKleHwMfKK2VczSLttQU2ZPrFDtTz7xyZO5v8Zp8U8/edit?usp=sharing

Here we can discuss the current download columns. Log in as chemblgroup@googlemail.com to edit it

**Comment by nclopezo** [comment]
@nbosc I am doing some changes to the downloads in https://github.com/chembl/GLaDOS/pull/1159. Please see the following file:
[CHEMBL25-chembl_molecule-bRQyb5FDXEzS6DmEpWMlc4_K_I9oBFDbFkHNcnolUdA=.csv.gz](https://github.com/chembl/GLaDOS/files/3346493/CHEMBL25-chembl_molecule-bRQyb5FDXEzS6DmEpWMlc4_K_I9oBFDbFkHNcnolUdA.csv.gz)
It is a csv file with all the drugs, let me know if this is as expected. It will be generated like that after the pull request is merged.

**Comment by nbosc** [comment]
To me it’s look good, but the more I think about this, the more I believe that the download file should contain the column filtered. Because every user has different usage.

**Comment by nclopezo** [comment]
Do you mean that the user can select the columns to include in the file?

**Comment by nbosc** [comment]
Yes

**Comment by nclopezo** [comment]
All the downloads from all the entities have been reviewed, the downloads package has been refactored, and now this should be fixed, you can try downloading the drugs again.
https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/_metadata.compound_records.src_id%3A13
