### ISSUE TITLE
download sdf for drugs returns many empty molecules

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#1106]
In the sdf file you can download from [here](https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/_metadata.compound_records.src_id%3A13), drugs without structures are not filtered out resulting in many empty molecules in the file.

IMHO, these molecules should not be exported in the sdf, but they should be in the tsv/csv file as they have other important data.

**Comment by nclopezo** [comment]
This is fixed now, see for example:
https://www.ebi.ac.uk/chembl/g/tiny/GgR9O6doaqcDQ10FaD836g==

**Comment by nbosc** [comment]
Looks good indeed. Now maybe we can discuss #1105
