### ISSUE TITLE
Binding DB references missing on new interface

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1115]
The assay report cards (e.g. CHEMBL3706301) are missing the Binding DB links on the new interface (these can be found on the old interface).

**Comment by nclopezo** [comment]
This is now done, see for example:
https://www.ebi.ac.uk/chembl/assay_report_card/CHEMBL3889209/
https://www.ebi.ac.uk/chembl/assay_report_card/CHEMBL3707759/
https://www.ebi.ac.uk/chembl/assay_report_card/CHEMBL3887375/
