### ISSUE TITLE
Drug use cases from Indications or Mechanism tables

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#1136]
From the drug indications and drug mechanism tables I think an obvious use case is to select some compounds and then view the bioactivity data.

e.g what data is there in ChEMBL for compounds that are cardiovascular drugs or for compounds that are approved drugs and are inhibitors of JAK2.

So is it possible to have a browse compounds link on these pages that would then enable you to select compounds, view compounds and then go to bioactivity data in the normal way.

**Comment by nclopezo** [comment]
This was solved by https://github.com/chembl/GLaDOS/pull/1200

**Comment by nclopezo** [comment]
The links are deployed now: https://www.ebi.ac.uk/chembl/g/#browse/mechanisms_of_action
