### ISSUE TITLE
Interface searches (>20 results)

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1139]
I’ve been using the search bar to look for cell lines in ChEMBL. 

The website seems to stall when a search provides more than 20 results (and I’ve subsequently scrolled to the next page). New searches then display results from the previous query.

In this screenshot, there should be a single result but the 28 cell lines identified in the previous search are shown instead (until I close and reload the website).

![Screenshot 2019-06-04 at 14 12 48](https://user-images.githubusercontent.com/46962491/58886862-7ed00580-86dc-11e9-9d60-3169b55585e2.png)

**Comment by nclopezo** [comment]
Hi Emma, 

Could you please paste here the url of the page you are were looking at?

**Comment by Emma-Manners** [comment]
I have just searched for the cell line ‘GBL 28’ using the search bar – 
https://www.ebi.ac.uk/chembl/g/#search_results/cells/query=GBL%2028

This gave 101 results which I scrolled through. 

I then searched for the cell line ‘M9-ENL1’ using the search bar - 
https://www.ebi.ac.uk/chembl/g/#search_results/cells/query=M9-ENL1

This gave one result which wasn’t loaded (the previous results were displayed). I tried the same ‘M9-ENL1’ search again but the previous search results were reloaded.

![Screenshot 2019-06-05 at 10 56 49](https://user-images.githubusercontent.com/46962491/58948027-23a41e80-8781-11e9-929b-21dfd2cc437e.png)

**Comment by agaulton** [comment]
I can reproduce this with other searches e.g., 
search 'kinase' in Targets -> go to page 3 -> then search 'dopamine d2' in Targets 
Targets tab still shows the page 3 kinase results but other tabs that have not previously been paged (e.g., compounds/documents) show dopamine related results. Cells tab still shows the results of me testing Emma's search above!

**Comment by nclopezo** [comment]
This is deployed now:
https://www.ebi.ac.uk/chembl/
