### ISSUE TITLE
inconsistency in the results displayed when looking for a compound

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#114]
If you look for a compound using its name (eg: imatinib), you get compounds, assays and documents.
If you look for the same compound using its chemblid (eg: CHEMBL941), you only get compounds.

**Comment by juanfmx2** [comment]
now that the relationtips have been denormalized, the search for CHEMBL941 returns the related assays and documents of that molecule. However, the search for the text imatinib, and the text CHEMBL941, as there might be documents that contain the text imatinib that have not been yet linked to CHEMBL941 in the database. So I'm closing this for now.
