### ISSUE TITLE
SDF file for drugs

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#1143]
Someone asked me a question last week when I was at the eTRANSAFE meeting about downloading an SDF file of all the ChEMBL drugs.  It is possible to do this but there are two issues with the file, I think it is including all the drugs that aren't small molecules in some way as there are lines of $$$$.  Also the only identifier in this is the ChEMBL_ID.  People who are accessing the data via the interface would find this much more useful if the pref_name was also included as a field in the SDF file.

**Comment by nclopezo** [comment]
Hi Anne, 

Could you please give me an example of the lines with $$$? I think that was fixed here https://github.com/chembl/GLaDOS/issues/1106, and the downloads this bug should have expired

**Comment by nclopezo** [comment]
As we discussed, the extra lines bug is fixed already (https://github.com/chembl/GLaDOS/issues/1106). We discussed with @juanfmx2. And the best solution is to include the prefered name in the elasticsearch sdf field (see https://github.com/chembl/GLaDOS-es/issues/34)

**Comment by juanfmx2** [comment]
This has been fixed! :) It has both chembl id and pref name now
