### ISSUE TITLE
click on a result opens a new tab

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#115]
To me it is annoying that when you click on a result, the card is opened in a a new tab. I would prefer to stay in the same tab. Like this I could use the go back function of the web browser.

**Comment by nclopezo** [comment]
I actually thought that it is annoying to loose the results page in which you are, just to take a look to one result. You can open 5 results for example, and you still have the results page in the original tab, and go back to where you were just by switching the tab.

**Comment by nbosc** [comment]
I agree. We should organize a vote!

**Comment by nbosc** [comment]
Therefore it would be nice to have a search box in the record cards.

**Comment by mnowotka** [comment]
This will be resolved in #257
