### ISSUE TITLE
http://europepmc.org/abstract/MED/No%20Data links to Europe PMC

### ISSUE THREAD

**Issue by datasome** [chembl/GLaDOS#1152]
On https://www.ebi.ac.uk/chembl/g/#browse/documents/filter/doc_type%3A%22DATASET%22%20AND%20NOT(_metadata.source.src_id%3A(%20%221%22%20OR%20%227%22%20OR%20%228%22%20OR%20%229%22%20OR%20%2211%22%20OR%20%2212%22%20OR%20%2213%22%20OR%20%2215%22%20OR%20%2218%22%20OR%20%2225%22%20OR%20%2226%22%20OR%20%2228%22%20OR%20%2231%22%20OR%20%2235%22%20OR%20%2237%22%20OR%20%2238%22%20OR%20%2239%22%20OR%20%2241%22%20OR%20%20%2242%22))%20AND%20_metadata.related_activities.count%3A%3E0, there are 'No data' links in Pubmed ID column that direct the user to http://europepmc.org/abstract/MED/No%20Data. If there is no data, there should not be any links?

**Comment by datasome** [comment]
I have noticed the same in BTO ID, EFO ID and Caloha ID columns.

**Comment by nclopezo** [comment]
This is fixed now
