### ISSUE TITLE
font size too small on big screens

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#116]
In a record card, look at the indications. Ok you can read it, but with large blank spaces on both sides of the page (on the 27'' screen), you could slightly increase the font size. Also it would be more consistent with, for instance, the compound properties.

**Comment by mnowotka** [comment]
I'm linking this issue with #264 which also is about fixing layout on the biggest screens.

**Comment by mnowotka** [comment]
After discussion with @nbosc this can be closed.
