### ISSUE TITLE
Bad page returns when clicking on a compound from a target card

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#117]
On a target record card (eg: CHEMBL1862), under Approved Drugs And Clinical Candidates if you click on a drug link it opens the target record card instead of the drug record page.

**Comment by nclopezo** [comment]
This still needs to be fixed.

**Comment by nclopezo** [comment]
This has been fixed, you can check here: 
https://chembl-glados.herokuapp.com/target_report_card/CHEMBL1862/

**Comment by mnowotka** [comment]
Looks totally like fixed!

**Comment by mnowotka** [comment]
OK, reopening this as @nbosc found out this is not yet working correctly.

**Comment by nbosc** [comment]
At least, it no longer points to a target card! :D

Sorry guys, Friday joke…

N

**Comment by nclopezo** [comment]
This should be hopefully fixed now:
https://chembl-glados.herokuapp.com/target_report_card/CHEMBL1862/

**Comment by nbosc** [comment]
Good! Thanks.
