### ISSUE TITLE
Still an issue with mechanism of action data?

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#1186]
CHEMBL190 is parent of CHEMBL1370561 and CHEMBL1200434
All three have the same three mechanisms in the database. The parent page (CHEMBL190) correctly shows all three, but https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1370561/ shows only the Phosphodiesterase 3 mechanism and https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1200434/ shows only the other two mechanisms. In reality they should all be identical.

(see also closed issues: #1097 and #1172)

**Comment by juanfmx2** [comment]
This has been fixed! :)
