### ISSUE TITLE
Selection checkboxes don't work on activities browser

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#1187]
If I view the activities for a target, I am unable to select anything other than the top row. Clicking on the second checkbox just unchecks/rechecks the first row. So it's impossible to select say the top 3 compounds

e.g., https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL3972/
=> click on activities chart => select top 3 compounds

**Comment by nclopezo** [comment]
The fix is deployed now
