### ISSUE TITLE
Ligand efficiency plot not displayed correctly?

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#1188]
I looked at a number of different target pages (e.g., https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL1827/) , and in each case I only see a single spot on the ligand efficiency plot. If you mouse over the background, it looks like other data is there but not displayed (see screenshot)
![Screenshot 2019-09-16 at 15 25 11](https://user-images.githubusercontent.com/7058697/64966323-76b86200-d896-11e9-9480-93715900b119.png)

**Comment by nclopezo** [comment]
This was also fixed by https://github.com/chembl/GLaDOS/pull/1189
