### ISSUE TITLE
Include patent_IDs on the document report card

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1192]
It might be useful to include the patent ID (and/or a link) on the document report card. 

There is limited information for patents on the document report card (compared to the information for scientific literature).

**Comment by agaulton** [comment]
Adding this to ChEMBL 26 as I think the data is there and it should be simple, but let me know if not

**Comment by nclopezo** [comment]
Added by https://github.com/chembl/GLaDOS/commit/c6a4ff0709f194b8dd7dba26c44fe98f493be640 which is in the chembl26 branch, will be available in wwwdev.

**Comment by nclopezo** [comment]
This is included now:
https://www.ebi.ac.uk/chembl/document_report_card/CHEMBL3880383/
