### ISSUE TITLE
Hyperlink on the Activity Charts

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#1196]
On the report card piecharts can we make the hyperlink which the displays the bioactivity table more obvious.  e.g "Activity Types for Target CHEMBLxxxx" Preferably by using a button but if that is difficult change the colour of the text.  At the moment it doesn't look like a hyperlink
https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL230/
https://www.ebi.ac.uk/chembl/g/#browse/activities/filter/target_chembl_id%3ACHEMBL230

**Comment by nclopezo** [comment]
This is deployed now:
https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL230/
