### ISSUE TITLE
Links on metabolic schemes are wrong

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#1199]
One of the participants at the course this week spotted that the links to the targets on the metabolic schemes don't go to a valid URL e.g. https://www.ebi.ac.uk/target_report_card/CHEMBL3397
It should be https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL3397

**Comment by nclopezo** [comment]
This is fixed now:
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL25/
