### ISSUE TITLE
Show in vivo assay classification on the interface

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#1201]
We have the in vivo assay classification already in the web services (assay_class, and also nested in the assays), but might not be in elastic yet...

We would like to have the different levels as filters on the browse assays view (and also maybe on the activities view if that's possible). 

But it could also be good to have the whole classification as a sunburst that allowed you to retrieve a set of assays (like we have for protein family classification and targets).

Added to ChEMBL_26 milestone, but not critical for switching off old interface since it's a new feature

**Comment by agaulton** [comment]
Filters look good. Please could we add the three levels as optional columns for the assay table view/exports also? 

For the long term, we need to work out what to do with the 'Other' categories in the filters, but we can discuss that separately...

**Comment by nclopezo** [comment]
Hi Fiona, 

I just updated the filters as you suggested in 1 and 2. See https://www.ebi.ac.uk/chembl/g/#browse/assays

- **Regarding 3:** 'N/A' means 'No value set for this property', whereas 'Other Categories' means 'Categories that don't fit on the space given'. I am not sure I understand what is the inconsistency. 
Could you please paste here an example of it?

- **Regarding 4:** Just to be clear, I plan to work on the 'Other Categories' but is not currently what I am working on.

**Comment by FionaEBI** [comment]
Thanks David, 
It all looks fine.

Regarding 3: the inconsistency was between L1, L2 and L3 (not between N/A and Other Categories within e.g. L1) - but I can no longer see the issue, so perhaps it arose as a result of the assay data that I had selected. So no need to look at this further.

In general N/A is not a helpful label until the user understands that only a small fraction of all the assays have been annotated using the L1, L2, L3 annotation, hence the need to have something that obviously shows that ‘Other Categories’ means more annotated assays that have not been shown in the current view. 

Best wishes, 
Fiona

**Comment by nclopezo** [comment]
There is a new visualisation on the visualisations page, it is a sunburst showing the in vivo assay classification:
https://www.ebi.ac.uk/chembl/visualise/
