### ISSUE TITLE
problem with X-Frame-Options in external iframes

### ISSUE THREAD

**Issue by juanfmx2** [chembl/GLaDOS#1202]
This 2 tickets are related, and are about problems with these settings that prevent embedding iframes.
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=372964
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=372780

**Comment by nclopezo** [comment]
Those settings have not changed. We asked them for more information about what they want to do but there is no response yet. I will reopen this if we get an answer on the tickets.
