### ISSUE TITLE
CREDO structure cross reference is broken

### ISSUE THREAD

**Issue by eloyfelix** [chembl/GLaDOS#1211]
https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL6030/

It shows internal server error:
http://marid.bioc.cam.ac.uk/credo/structures/4G31

Shall we contact them?

Thanks @muthuvenkat for spotting it

**Comment by anne123** [comment]
I noticed this too - I can't see that their website is live so just removing the links to credo  would be my suggestion. I don't think it adds a lot above the PDB links.

**Comment by anne123** [comment]
I've just noticed this again while trying to create some training material.  Can we remove these links for ChEMBL26?

**Comment by nclopezo** [comment]
OK. I will remove them for ChEMBL26.

**Comment by nclopezo** [comment]
They were removed by https://github.com/chembl/GLaDOS/commit/167a42fd45e2f5d17084abd636240751864eac01 which is currently in the chembl26 branch. Will be available when the release is published.

**Comment by nclopezo** [comment]
The CREDO Links have been removed:
https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL6030/
