### ISSUE TITLE
Update ChEMBL NAR paper on front page of website

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#1213]
The front page of the ChEMBL interface is still showing the 2017 ChEMBL paper. This should be updated to the 2019 ChEMBL paper - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6323927/

**Comment by nclopezo** [comment]
Fixed by 997d9350b1df3b9025527cdc9e6f554333e94504. Will be available when ChEMBL 26 is ready.
