### ISSUE TITLE
Mapping mutants for assay data

### ISSUE THREAD

**Issue by LivC193** [chembl/GLaDOS#1216]
I am trying to generate compound-protein pairs that have an assay value associated. I see you map protein targets to Uniprot, but how do you deal in cases where the protein has been mutated ? Is there any way to get access to the mutated sequence ?

**Comment by Emma-Manners** [comment]
Yes, mutations are recorded in the variant_sequences table. 

There is some additional information here - https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/target-questions#how-does-chembl-treat-protein-variants

Thanks
