### ISSUE TITLE
Show additional columns on the interface?

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1229]
There has been interest in downloading physchem (PSA, logD, MW) and target (IC50s, Ki) data from the interface. I'm not sure if this can be done in a single table at the moment.

Consider adding an option to show PSA and LogD columns when 'Browsing activities' so that this is possible?

See 389827 for more details.

**Comment by nclopezo** [comment]
Hi Emma, 

I checked and PSA and logD are not currently in the Activity index, they need to be in the index to be shown on the interface. If @agaulton and @juanfmx2 agree, we can add it to the index for ChEMBL26.

**Comment by agaulton** [comment]
Sure, I think it would be good to add them

**Comment by Emma-Manners** [comment]
Resolved.
