### ISSUE TITLE
Literature data displayed on compound report cards

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1241]
For CHEMBL1114, there is activity data associated with the parent form but no literature is shown on the compound report card (see screenshot). Is this correct?

![Screenshot 2020-03-06 at 10 16 13](https://user-images.githubusercontent.com/46962491/76074789-cf3e0180-5f93-11ea-84c3-7a25786860c6.png)

**Comment by juanfmx2** [comment]
This is fixed now :)
