### ISSUE TITLE
Associated compounds not shown on the target report card

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1243]
Associated compounds are not shown on the compound report card e.g. 

https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL1824/

![Screenshot 2020-03-10 at 11 02 55](https://user-images.githubusercontent.com/46962491/76306644-3115a880-62bf-11ea-8cb2-5603eb275f0c.png)

But are shown in table of target search results - 

![Screenshot 2020-03-10 at 11 05 41](https://user-images.githubusercontent.com/46962491/76306624-29560400-62bf-11ea-81ed-0e0131107b13.png)

Is this correct?

**Comment by juanfmx2** [comment]
This is fixed now :)
