### ISSUE TITLE
Calculate stereochemistry not working

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1247]
If I click on rapamycin, then structure search and then calculate stereochemistry, I get an error.

<img width="1218" alt="Screenshot 2020-03-23 at 09 16 50" src="https://user-images.githubusercontent.com/46962491/77301254-4939ee80-6ce7-11ea-829c-b11c48e70c7e.png">

<img width="1221" alt="Screenshot 2020-03-23 at 09 16 58" src="https://user-images.githubusercontent.com/46962491/77301270-51922980-6ce7-11ea-8997-7df2f3fd5b4d.png">

**Comment by eloyfelix** [comment]
Hi, this is a beaker related bug. 
I'll take a look at it as soon as I can.

**Comment by eloyfelix** [comment]
beaker endpoints are working as originally designed:

https://colab.research.google.com/drive/1KgJ904kXpJOtekxwqsKAjrkopHs2Bygd?authuser=1#scrollTo=Zwdk1J1bwzVl

we need to check how marvin is calling them, if it can be changed and if marvin upgrade broke anything.

**Comment by eloyfelix** [comment]
current marvin version v18.11.0 changed a bit the format of its document so all beaker functions that required to read it crashed. this is now updated and functions are working.
We should not upgrade marvin for a while since v20 changes a lot the format!

**Comment by Emma-Manners** [comment]
This is now working perfectly
