### ISSUE TITLE
Molecular species is null

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1248]
The molecular species is null for some entries, I'm not sure why - is this correct?

e.g.

https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL171623/
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL269644/
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1330792/
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1256668/
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2105678/
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL550936/
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1762621/

**Comment by eloyfelix** [comment]
hi, this is correct since their CX Acidic pKa and CX Basic pKa are null as well.
I can see that some of the compounds have data in cx_logd and cx_logp fields so it's just chemaxon doesn't returning a value for them (for some good reason).

**Comment by Emma-Manners** [comment]
Great - shall I close?

**Comment by eloyfelix** [comment]
yup!
