### ISSUE TITLE
Uniprot accession link broken/no longer available?

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1254]
https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL4660/

<img width="1225" alt="Screenshot 2020-04-04 at 13 32 32" src="https://user-images.githubusercontent.com/46962491/78532570-62f72d80-77df-11ea-9841-72d23afa0c27.png">

**Comment by nclopezo** [comment]
This has been fixed by 6e35baa3fd3c9237bd61da195776050925a4678e
