### ISSUE TITLE
Broken link - ChEMBL database release DOIs

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1259]
e.g. 
ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/releases/chembl_20

**Comment by nclopezo** [comment]
Hi Emma, 

Could you please give me the url of the page where you saw the broken link?

Thanks

**Comment by nclopezo** [comment]
There is an issue with Safari and ftp servers. Opening the link with other broswers should work.
