### ISSUE TITLE
Search by SMILE don't work anymore?

### ISSUE THREAD

**Issue by Vitruves** [chembl/GLaDOS#1264]
Hi,

I usually search on ChEMBL with SMILE codes, usually multiple SMILE at a time.

But since two days (since 21 May 2020) the query don't work and return Internal Server Error.

I've tested on OSX Safari and Google Chrome (latest versions) without success.

Is this problem going to be fixed?

**Comment by juanfmx2** [comment]
this issue has been fixed now!
