### ISSUE TITLE
remove duplicate in alternative forms

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#1276]
for instance:
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL822/

**Comment by juanfmx2** [comment]
I have checked the data and it seems to be fine, I think it is an issue in the web interface. If you check on this one https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2068714/ the pagination knows there are 10 compunds, but it tries to display more than that.
![image](https://user-images.githubusercontent.com/6558395/97584767-48410c00-19f0-11eb-89ce-2b78944a62da.png)

**Comment by nclopezo** [comment]
It seems like there is a bug with the carousel :(

**Comment by nclopezo** [comment]
This is fixed now.
