### ISSUE TITLE
DailyMed links in Cross References not working

### ISSUE THREAD

**Issue by apbento** [chembl/GLaDOS#1277]
DailyMed has updated their URLs, so the links to DailyMed in the Cross References section are currently not working.

The URL should be changed from
http://dailymed.nlm.nih.gov/dailymed/advSearch.cfm?startswith=NAME:(%22XREF_ID%22)
to
https://dailymed.nlm.nih.gov/dailymed/search.cfm?adv=1&labeltype=human&query=INGREDIENT:(%22XREF_ID%22)

Using sildenafil as an example:
current URL - http://dailymed.nlm.nih.gov/dailymed/advSearch.cfm?startswith=NAME:(%22sildenafil%20citrate%22)
should be updated to - https://dailymed.nlm.nih.gov/dailymed/search.cfm?adv=1&labeltype=human&query=INGREDIENT:(%22sildenafil%20citrate%22)

**Comment by nclopezo** [comment]
I checked and the interface is not parsing the DailyMed references. The url comes from Elasticsearch and the interface just displays it as it comes:
https://gitlab.ebi.ac.uk/chembl/chembl/main-web-interface/glados-frontend-chembl-main-interface/-/blob/master/src/glados/static/coffee/views/References/ReferencesView.coffee#L49

You can see the references here:

https://www.ebi.ac.uk/chembl/interface_api/es_proxy/es_data/get_es_document/chembl_molecule/CHEMBL192

Unfortunately, this requires a reindexing to fix it. @juanfmx2

**Comment by Emma-Manners** [comment]
Resolved. These are now working.
