### ISSUE TITLE
show more from protein classification in the activity browser

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#1278]
When browsing activities, you can only filter proteins by their L1 classification. Useful protein family information  such as kinase is in L2. Please add L2 and maybe L3 as well in the filters.

**Comment by nclopezo** [comment]
This is done by https://gitlab.ebi.ac.uk/chembl/chembl/main-web-interface/elasticsearch-proxy-api/-/merge_requests/55
You may need to do a hard reload of the page to fully refresh it:
https://www.ebi.ac.uk/chembl/g/#browse/activities

**Comment by nclopezo** [comment]
![Screenshot 2020-12-01 at 11 23 18](https://user-images.githubusercontent.com/1944922/100767367-ae41fa00-33c7-11eb-83f2-18b415a8de56.png)
