### ISSUE TITLE
Download button not work

### ISSUE THREAD

**Issue by chemlove** [chembl/GLaDOS#1292]
https://www.ebi.ac.uk/chembl/g/#search_results/all/query=CCC1Cn2nc(-c3ccc(Cl)cc3OC)c3nc(C)cc(c32)N1CC1CC1

Nothing was downloaded.
See the video for details.

https://user-images.githubusercontent.com/30210271/127798388-74c1ee55-c074-46e2-98aa-274e735406fc.mp4

**Comment by nclopezo** [comment]
Hi @chemlove,
I opened the link and I was able to generate the files, you can use the following URLs to download them:
CSV:
https://www.ebi.ac.uk/chembl/interface_api/delayed_jobs/outputs/DOWNLOAD-fG34CQxrYthgp_shX1q_Gq9ry_SjFkT0IVlRGqDVxVA=/DOWNLOAD-fG34CQxrYthgp_shX1q_Gq9ry_SjFkT0IVlRGqDVxVA=.zip
TSV:
https://www.ebi.ac.uk/chembl/interface_api/delayed_jobs/outputs/DOWNLOAD-McCngawRB9Esm8fqyO_ticLC4_dVBNygOXmBHzGa6iU=/DOWNLOAD-McCngawRB9Esm8fqyO_ticLC4_dVBNygOXmBHzGa6iU=.zip
SDF:
https://www.ebi.ac.uk/chembl/interface_api/delayed_jobs/outputs/DOWNLOAD-LsEGmK3POCi2rfMiTAwlDeUJCGmxyVZ9IIRwx6FBS3s=/DOWNLOAD-LsEGmK3POCi2rfMiTAwlDeUJCGmxyVZ9IIRwx6FBS3s=.zip

Unfortunately, I wasn't able to see the image of the video that you uploaded. For a smiles, you could get better results by using the structure search. You can open the structure menu by clicking on 'Advanced Search'. For example, you can do a structure search with that smiles:
https://www.ebi.ac.uk/chembl/g/#similarity_search_results/CCC1Cn2nc(-c3ccc(Cl)cc3OC)c3nc(C)cc(c32)N1CC1CC1/40
I hope that helps.

**Comment by chemlove** [comment]
@nclopezo Thank you very much for your quick response. Your response help me a lot.
