### ISSUE TITLE
Cross reference link name should be Expression Atlas and not ArrayExpress

### ISSUE THREAD

**Issue by pcm32** [chembl/GLaDOS#1301]
Hi there,

On your cross references, you are linking to the expression of genes at our resource (Expression Atlas), which we really appreciate! But currently it says there "ArrayExpress" in the label of the link, where it should read "Expression Atlas" instead:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/368478/167444595-1ba11aaf-398e-466a-ae17-5377818979d2.png">

Could you please amend this? The link works fine, it is just the name of the resource.

Thanks!

**Comment by nclopezo** [comment]
Hi Pablo,

Thank you for your feedback, this has been fixed, along with the way it gets the reference from the ChEMBL data, you can see it here: 

https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL3774298/

**Comment by pcm32** [comment]
Thanks!

**Comment by Emma-Manners** [comment]
@nclopezo 

Although the cross reference Iink works fine and the resource name is correct, I noticed that we now use the UniProt accession in the gene cross references rather than the ENSEMBL_ID. We previously used the ENSEMBL_ID. Is this correct?

**Comment by nclopezo** [comment]
Those references don't seem to have any further processing, they are shown as they come from elasticsearch: 

https://www.ebi.ac.uk/chembl/interface_api/es_proxy/es_data/get_es_document/chembl_target/CHEMBL3774298?source=target_components.target_component_xrefs

<img width="679" alt="Screenshot 2023-11-02 at 14 56 53" src="https://github.com/chembl/GLaDOS/assets/1944922/ce23d936-39c6-4ef2-a236-f99d6756190f">

Is this what you are asking about?

**Comment by Emma-Manners** [comment]
Thanks. The above screenshot shows an Ensembl_ID but I agree that the XREFs haven't changed in the database and are working.
