### ISSUE TITLE
Chembl programmatic scripts failing due to offset limit

### ISSUE THREAD

**Issue by YojanaGadiya** [chembl/GLaDOS#1302]
Dear ChEMBL team,

There have been recent issues with accessing the ChEMBL server programmatically. Please could you take a look at the issue and solve it?

https://github.com/chembl/chembl_webresource_client/issues/120 

My suspect is that this is with the offset since the documentation mentions that the cutoff for the output allowed is up to 5000 molecules/assays which no more is the case.

**Comment by eloyfelix** [comment]
thank you for reporting. The issue with the webservices has been resolved to everything should be working fine now.
