### ISSUE TITLE
max phase by country

### ISSUE THREAD

**Issue by fschiro** [chembl/GLaDOS#1304]
For the max phase category, I understand that it is max phase in any country. Is there a way to query max phase by country? For example, if I only want to see max phase approved in United States (FDA)

**Comment by eloyfelix** [comment]
Max_phase in ChEMBL is the highest clinical phase recorded for any disease indication that an individual drug has been tested for in e.g. clinical trials (Phase 1, 2, 3), or approved (Phase 4) as a marketed drug by a regulatory body such as the FDA, or EMA etc. Remember that a drug may be approved for one disease indication, but concurrently may also be tested in clinical trials for a different disease indication. So the information for a specific drug to disease indication would be found under “Browse Indications” in the web interface (or “max_phase_for_ind” within the database table drug_indication / indication_refs), while the (overall) max_phase for a drug across all indications would be found under “Browse Drugs” in the web interface, or max_phase in the molecule_dicationary table of the database.

So if you want to find all approved (Phase 4) FDA drugs then you could look in the web interface for Browse Drugs, then filter by Max_phase = 4 and Source_id = 9 “Orange Book” aka ORANGE_BOOK. Note that ChEMBL uses Orange Book as the primary source of FDA drug information - see e.g. https://www.accessdata.fda.gov/scripts/cder/ob/index.cfm

Here’s a shortened link for the example above: https://www.ebi.ac.uk/chembl/g/tiny/-SxlqlovTxJu2ojiaBULgA==

(In addition, there will also be a small number of recently approved FDA drugs that have not yet been included in Orange Book. These would be found (along with other drugs from e.g. WHO) under the source_id = 12 “Manually Added Drugs” aka DRUGS. But you would need to query the downloaded database, or API, to access this set of drugs, and then manually check through the list to match them to e.g. https://www.fda.gov/drugs/new-drugs-fda-cders-new-molecular-entities-and-new-therapeutic-biological-products/novel-drug-approvals-2022.)

However, if you want to find clinical candidate drugs (with max_phase ={1,2,3}) then this information comes (almost always) from ClinicalTrials. So you could filter by e.g. Max_phase = 3, and Source_id = 8, “Clinical Candidates” aka CANDIDATES. The Clinical Trials information comes from any clinical trial worldwide, so you would need to manually inspect the results to filter those that are only relevant to an individual country.

Please get back to us if you have further queries.

**Comment by fschiro** [comment]
Thank you so much that answer was great.
