### ISSUE TITLE
Likely erroneous accession on CHEMBL4630576

### ISSUE THREAD

**Issue by erikyao** [chembl/GLaDOS#1310]
Hi CHEMBL scientists/developers,

I found that [CHEMBL4630576](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL4630576/) is reported with an accession `ENSG000001127154`. However `ENSG000001127154` seems not a stable Ensembl ID because it has 12 digits.

Quote from [Stable IDs](https://uswest.ensembl.org/info/genome/stable_ids/index.html):

> Stable IDs are created in the form ENS[species prefix][feature type prefix][a unique eleven digit number]

Is there a typo in `ENSG000001127154`? Thanks!

Best wishes!

**Comment by Emma-Manners** [comment]
Thanks for raising this issue. The accession has been fixed and the corrected version will be displayed in ChEMBL v34.
