### ISSUE TITLE
unnecessary space in CHEMBL4662965 target accession

### ISSUE THREAD

**Issue by erikyao** [chembl/GLaDOS#1311]
Hi CHEMBL scientists/developers,

Just an FYI that `CHEMBL4662965` record in the [taregt.json files](https://www.ebi.ac.uk/chembl/api/data/target.json) is (formatted for readability):

```python
{
  "cross_references": [],
  "organism": "Homo sapiens",
  "pref_name": "LPA mRNA",
  "species_group_flag": false,
  "target_chembl_id": "CHEMBL4662965",
  "target_components": [
    {
      "accession": "ENSG00000198670 ",
      "component_description": "LPA mRNA",
      "component_id": 19598,
      "component_type": "RNA",
      "relationship": "RNA",
      "target_component_synonyms": [],
      "target_component_xrefs": []
    }
  ],
  "target_type": "NUCLEIC-ACID",
  "tax_id": 9606
}
```

and the `"accession": "ENSG00000198670 "` entry has an unnecessary ending space character. It's not a serious problem though.

Best wishes!

**Comment by Emma-Manners** [comment]
Thanks for letting us know, this is fixed for ChEMBL v33.
