### ISSUE TITLE
retrieving target data from ChEMBL (protein classification, organism taxonomy, etc.)

### ISSUE THREAD

**Issue by MaedehDarsaraee** [chembl/GLaDOS#1315]
I am a PhD student in Chemistry, Biochemistry and Pharmacy department at the University of Bern and I am working on a drug design project using ChEMBL data. I need to retrieve the target data (protein classification, organism taxonomy, etc.) and add it to the bioactivity data that I already retrieved and it is an important part of my project, but I can't find a way to do that. I used ChEMBL API but It did not give me the information I needed. I am working with Jupyter notebook, Python 3.6. I would appreciate it if you suggest me a solution for this problem.

**Comment by Emma-Manners** [comment]
Thanks for the question, we've replied to your e-mail.
