### ISSUE TITLE
Q02127 target report card shows Server Error (500)

### ISSUE THREAD

**Issue by jurgjn** [chembl/GLaDOS#1319]
Searching for Q02127 (DHODH) on the home page (https://www.ebi.ac.uk/chembl/), shows a page with a single result (CHEMBL1966). Clicking on the corresponding link (https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL1966) results in a "Server Error (500)" page.

![CC9BDC4E-4D4D-4E45-B3E2-806E3C9A3268](https://github.com/chembl/GLaDOS/assets/5638655/6d9829a4-eb98-4ce3-a160-84ecf42f6469)
![E4A416DB-98FC-4BE9-908B-AE8DCAA4FD5C](https://github.com/chembl/GLaDOS/assets/5638655/889fdaf1-bc03-4af6-8272-511e0ac2dde6)

**Comment by nclopezo** [comment]
Hi @jurgjn,

The error should be fixed now.
