### ISSUE TITLE
Things to amend - June 2023

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#1323]
- [x] 1. Add a custom sorting for the release date filter in documents.
- [x] 2. Remove time from release date. <img width="121" alt="Screenshot 2023-11-01 at 09 31 57" src="https://github.com/chembl/GLaDOS/assets/1944922/be58b395-2b37-41ea-b009-3e8fa41edaf4">
- [x] 3. Show Molecule Features for all the compounds
- [x] 4. Delete text 'Synthetic' from 'Synthetic Small Molecule'
- [x] 5. Add new icon for chemical probe.
- [x] 6. Add new icon for natural product.
- [x] 7. Fix the overlapping of texts in the histogram bars:
 <img width="294" alt="Screenshot 2023-07-04 at 14 06 44" src="https://github.com/chembl/GLaDOS/assets/1944922/43ba7b10-9e71-41c9-8e85-6317afc69f61">

**Comment by nclopezo** [comment]
@juanfmx2 I checked and regarding 2 it would be better if we had a text from elasticsearch without the time part ('T00:00:00'), because it will be fixed from the source, instead to having to apply the parsing everywhere it appears on the interface.

**Comment by nclopezo** [comment]
Regarding task 1, now we can set up a custom configuration for certain properties. For example, for ChEMBL Release in documents, now you can select up to 100 bars, this means that you can see all the releases in the histogram:

https://github.com/chembl/GLaDOS/assets/1944922/1864824b-7bf4-494c-95ec-c0faf4125b98

Now you can also sort by either key or count, this means that you can sort by the release name instead of the number of items of the bar:

https://github.com/chembl/GLaDOS/assets/1944922/24a51ce4-3c5d-416a-ac9e-6e48d04e772f

As it was expected, the order is lexicographic. I tried to add a custom script to sort it in a 'natural' way, but it was not possible, and we will have the same problem when sorting on the table. I think is better to make a field with a name like 'release_label' that has the number first, and the values are something like:

- '1. CHEMBL_1'
- '2. CHEMBL_2'
- '3. CHEMBL_3'
- '4. CHEMBL_4'

That way we can sort it in a natural way easily.

**Comment by juanfmx2** [comment]
I think even if the number is leading it will not solve the sorting issue, because is will still be a string the only way to solve it is to add leading zeros to the the releases with a single digit (CHEMBL_01, CHEMBL_02, CHEMBL_03 . . .  CHEMBL_09)

**Comment by nclopezo** [comment]
Yes, you are right, my bad, the way to fix it would be to add leading zeros.

**Comment by nclopezo** [comment]
There is a new custom sorting for the ChEMBL release filter:
<img width="409" alt="Screenshot 2023-11-01 at 09 34 19" src="https://github.com/chembl/GLaDOS/assets/1944922/e7e9367d-1e94-458d-9932-0d3870f2f1ca">

More releases appear as the number of bars is increased. 
<img width="387" alt="Screenshot 2023-11-01 at 09 35 34" src="https://github.com/chembl/GLaDOS/assets/1944922/8cfde104-0b11-49ba-ac2a-f7b0bb7c1d3c">

**Comment by BZdrazil** [comment]
It looks great now, thank you!
