### ISSUE TITLE
Regarding Activity Comment 

### ISSUE THREAD

**Issue by sumone-compbio** [chembl/GLaDOS#1329]
Hi there, 

I came across several inhibitors for estrogen receptor alpha where the activity comment does not comply with the standard or pChembl values. For instance, a good inhibitor is something with pic50 > 7. However, seeing the inhibitors in the data table, several reported inhibitors are labeled 'active' with pic50 as low as 4.5. What could be the reason behind this?

**Comment by Emma-Manners** [comment]
We have some additional information on the activity_comment here - https://chembl.blogspot.com/2020/08/using-chembl-activity-comments.html

You can also contact us on our Helpdesk for data-related questions - 
https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/general-questions#how-do-i-report-errors-or-make-suggestions-for-the-interface
