### ISSUE TITLE
Scaffold buttons not shown in Marvin JS on Safari

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#251]
On safari I don't see any of the scaffold buttons at the bottom on Marvin JS, so can't draw anything!
![marvinbug](https://user-images.githubusercontent.com/7058697/31437959-0ddb00be-ae7f-11e7-817b-1b7aedc7d6de.jpeg)

**Comment by mnowotka** [comment]
This is directly related to #250 so I'm closing it as it's almost impossible for us to reproduce this problem is it seems that updating browser is much easier solution.
