### ISSUE TITLE
No way to display bioactivity data for multiple selected entities

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#252]
For compounds/targets the only way to select multiple compounds/targets and then retrieve all of the data seems to be via the 'Bioactivity' matrix/heat map view. 

However, since this view isn't present for other entities (e.g., assays), there is no way to get the data for multiple entries other than clicking through each report card. 

I think it would be useful for all entities to have a 'get Bioactivities for selected' button on the search results page so that you can go straight to the data view. Otherwise, I don't see what the point of being able to select entries is... 

Also maybe the link to do this on the matrix/heat map view should be a green button so it is a bit more obvious?

**Comment by nclopezo** [comment]
**This is ready:** 

Now when you are browsing elements, you will always see a link to "All Activities".
For example in: 
https://chembl-glados.herokuapp.com/g/#substructure_search_results/C1%3DCC%3DC(C%3DC1)C1C%3DCC%3DCC%3D1

You can see the following:
<img width="1427" alt="screen shot 2018-04-03 at 15 25 50" src="https://user-images.githubusercontent.com/1944922/38255289-598d327c-3753-11e8-8170-3c4e11c89874.png">

You can notice the following:
- The link only activates when there are less than 1024 items selected. 
- If all or none are selected, the link is created for ALL the items you are seeing.
- It updates as you change the selection. 

The link is available for all the main entities (Compounds, Target, Assays. Documents, Cell Lines, Tissues):
https://chembl-glados.herokuapp.com/g/#search_results/all/query=Liver

**Comment by nclopezo** [comment]
This also includes https://github.com/chembl/GLaDOS/issues/275

**Comment by nclopezo** [comment]
This was shown to @agaulton before closing.
