### ISSUE TITLE
Missing data on matrix view tooltips

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#253]
When you hover over a compound/target name on the bioactivity matrix/heat map view to see details, several of the fields say 'no data'. Perhaps you already know about this, but if not:

Targets:
UniProt Accession - should be available if it's a protein target
Compounds - must be some if the cell is green!
Bioactivities - must be some if the cell is green!

Compounds:
Targets  - must be some if the cell is green!
Bioactivities - must be some if the cell is green!

**Comment by nclopezo** [comment]
Thank you for reporting the bug, I will fix it. By the way, if you click on the text you can still go to a list of compounds/bioactivities.

**Comment by nclopezo** [comment]
This has been fixed.

**Comment by agaulton** [comment]
Looks good
