### ISSUE TITLE
Result pages don't load properly

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#254]
Only tested in safari so far, but after clicking on a filter the results are never displayed unless I click a different view (table/cards/infinite etc). I just see the green 'loading' line forever...

e.g., search 'dopamine' -> select 'Targets' -> click on 'Organism = Homo sapiens' filter -> no results shown -> click on 'Cards' -> the results appear right away

This is reproducible for me, happens any time I click a filter

**Comment by mnowotka** [comment]
Hi,

I created additional labels, one for each major browser.
@nclopezo - can we verify if that happens on any other browser?

**Comment by nclopezo** [comment]
Actually this one was because of a change I did these days. I fixed it here: https://github.com/chembl/GLaDOS/commit/1d1acf0d1994ba39fa39164f8262cc1c6115bd6f
 And I added a ghost inspector test: https://app.ghostinspector.com/tests/59de267b18b8510dccc8957b

**Comment by mnowotka** [comment]
@agaulton - can you verify if it's working now?

**Comment by mnowotka** [comment]
Once this is solved, please create a Ghose inspector test that checks that.

**Comment by nclopezo** [comment]
https://app.ghostinspector.com/tests/59de267b18b8510dccc8957b

**Comment by agaulton** [comment]
Yes fine now
