### ISSUE TITLE
Definitions for Max Phase on compound report card

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#255]
The definitions given here are not entirely correct as they apply more to data in clinical trials in general rather than the ChEMBL meaning (e.g., phase 4 in ChEMBL doesn't necessarily mean there is a phase 4 trial happening, just that it's approved, similarly phase 0 doesn't mean there is a preclinical trial)

I'm not sure the ? is necessary since you have the label ('Approved', 'phase II' etc) next to the score anyway...

**Comment by mnowotka** [comment]
I'm also linking this issue: #105 because along with changing definitions we can also change the icon from question mark to 'i' from information.

**Comment by mnowotka** [comment]
I would keep the tooltip in case someone would like to know what are other options. Just update descriptions and change '?' to 'i'.

**Comment by nclopezo** [comment]
OK, @agaulton could you please tell me which should be the correct texts for phase 0, 1, 2, 3, 4?

**Comment by agaulton** [comment]
Brief description:
4 = Approved
3 = Phase III
2 = Phase II
1 = Phase I
0 = Preclinical

If you want a longer explanation:
4 = Compound has been approved in at least one country/area
3 = Compound has reached phase III clinical trials (larger studies of safety and effectiveness)
2 = Compound has reached phase II clinical trials (preliminary studies of effectiveness)
1 = Compound has reached phase I clinical trials (safety studies, usually with healthy volunteers)
0 = Compound has not yet reached phase I clinical trials (preclinical/research compound)

**Comment by nclopezo** [comment]
**The descriptions have been updated.**
Max Phase 0:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2109133/
Max Phase 1:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2109441/
Max Phase 2:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2109564/
Max Phase 3:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2109361/
Max Phase 4:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1200421/
