### ISSUE TITLE
remove license error on Marvin sketcher

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#256]

**Comment by mnowotka** [comment]
This is a minor issue becase:
  - Marvin is fully functiona anyway
 - It will be gone once we deploy the interface on EBI infrastructure
 - We may consider using different sketcher (Ketcher 2) in wich case this issue will be invalid

**Comment by anne123** [comment]
Please can we fix this as it hasn't disappeared as Michal suggested it would - I don't think it looks good on a production interface

**Comment by nclopezo** [comment]
This is fixed.

**Comment by nclopezo** [comment]
I will keep this open and check why some bond options are not available in the buttons.

**Comment by nclopezo** [comment]
This is ready, the Marvin js sketcher has now the 'search' layout.
