### ISSUE TITLE
Downloading data

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#258]
e.g TSV file.  This doesn't work everything is in one column

**Comment by mnowotka** [comment]
The TSV fil download looks fine to me. We need some more information here in order to reproduce the issue.

**Comment by anne123** [comment]
I've attached the file I get.  This needs to open simply in excel for it to be useful.
[results(1).tsv.zip](https://github.com/chembl/GLaDOS/files/1379301/results.1.tsv.zip)

**Comment by mnowotka** [comment]
Screenshot from my Excel:
![screen shot 2017-10-12 at 16 45 53](https://user-images.githubusercontent.com/837119/31505470-e17cf754-af6c-11e7-9a77-b0a41cfca325.jpg)

**Comment by anne123** [comment]
screenshot from my excel
![excel_screenshot](https://user-images.githubusercontent.com/3308733/31505856-c1bbb436-af6d-11e7-9334-c9836b904cd0.jpeg)

**Comment by mnowotka** [comment]
OK, so this is about being able to correctly load the file using a double click / default application. According to what @eloyfelix this should be possible for both CVS and TSV files.
I'm marking this as a bug.

**Comment by nclopezo** [comment]
This has been fixed. The files now have the encoding that excel likes. You can try with:
https://chembl-glados.herokuapp.com/search_results/Dopamine

**Comment by anne123** [comment]
This is now working from Firefox :)

possibly already another issue but not working correctly from safari and can only download 10000 rows.

**Comment by mnowotka** [comment]
It works on my Mac using Firefox, Safari and Chrome but feel free to open a new issue if you see different behaviour.  I'd move discussing limits to a separate issue.
