### ISSUE TITLE
Target Use Case

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#259]
I still can’t see how to work through the target use case i.e search for target, get active compounds and show a selectivity profile of compounds against other targets

Is this possible?

**Comment by mnowotka** [comment]
It is and also it's critical to implement but we need to sketch some concrete solution together.

**Comment by anne123** [comment]
There is an example in the email I sent in August (CB2) but we can sit down and discuss.  Please let me know when.

**Comment by nclopezo** [comment]
This is the simple sketch that we made:

![scan_dmendez_2018-06-26-14-36-29](https://user-images.githubusercontent.com/1944922/41916579-3e08f920-7950-11e8-99ab-c4bc302fb828.jpeg)

This should finish this use case.

**Comment by nclopezo** [comment]
This is ready:
http://wwwdev.ebi.ac.uk/chembl/beta/g/tiny//xjDpbfQBoNotsaQY3p4Xg==
There is a description on how it works [here](https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/chembl-interface-questions#i-am-browsing-some-activities-what-does-the-browse-compounds-link-mean):

**Comment by nclopezo** [comment]
This was already shown to Anne. There are more improvements to be done and to discuss, but for now this can be closed.
