### ISSUE TITLE
Target Searching Autosuggestions

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#260]
Example 5-HT
 looking for 5-HT it suggests a lot of 5-HT-1A targets with different CHEMBL_IDs (presumably different species) but this is not obvious.  Shouldn’t it also suggest 5-HT2/3/4 etc?  Also selecting the first target in the list goes to a selectivity target (CHEMBL2111460). 
There is no way of knowing what the different 5-HT1 targets refer to for example
Also it would be good to be able to select the targets from all in targets and go straight to the target list page.  currently the only way to do this is to bypass the autosuggestions.

**Comment by mnowotka** [comment]
I agree, we need to think what fields (apart from ChEMBL Id and the field that matched) to include for each kind of entity.

**Comment by juanfmx2** [comment]
Deployed and ready!

**Comment by nclopezo** [comment]
Godlike!
