### ISSUE TITLE
Targets page UniProt Accession

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#261]
This is missing says no data

**Comment by agaulton** [comment]
Also missing on the target search results page

**Comment by mnowotka** [comment]
Yes, as I said, missing stuff is one of the major showstoppers now and also an issue we are aware about and going to solve it before December.

**Comment by mnowotka** [comment]
Can I have a screenshot please, and steps to reproduce it?

**Comment by anne123** [comment]
search for 5HT view Targets page.
![targets_example](https://user-images.githubusercontent.com/3308733/31496517-9ffe963e-af53-11e7-9b4e-ae5b2bf9ec1d.jpeg)

**Comment by nclopezo** [comment]
This has been fixed: https://chembl-glados.herokuapp.com/search_results/targets/Dopamine

**Comment by mnowotka** [comment]
Just to give some visual proof that this has been fixed:
![screen shot 2017-10-23 at 16 56 29](https://user-images.githubusercontent.com/837119/31899315-2cd87fda-b813-11e7-9650-56e635afeb9c.jpg)
