### ISSUE TITLE
Assay columns/filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#271]
On the assay search results page, it's not possible to show additional columns. Should add most of those columns that are possible as filters?

Also on default view, remove strain column and add BAO format (but with labels rather than IDs, see below).

On filters, remove 'Category' as this is not very useful. And show labels for BAO format terms rather than IDs (may need adding to web service, lives in the bioassay_ontology table)

**Comment by mnowotka** [comment]
I think this issue is now replaced with #290. Please reopen if not true.
