### ISSUE TITLE
browse activities filters

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#272]
Having the standard values here isn’t useful without the context of a standard type and units.  If you select Ki all it does is highlights dodgy data i.e very low or high values

From browse activities table ability to filter on pChEMBL values would be good (needed for use case 1).  

The ranges used for standard_value even on one activity type doesn’t make sense as most data is 0 to 50,000 for target CHEMBL214 for example (0-50uM).  This range includes what we would call active and inactive compounds.  Need ability to filter on actives (<1uM for example).

**Comment by mnowotka** [comment]
This one is very important. @juanfmx2 and @nclopezo , please have a look at this.

**Comment by juanfmx2** [comment]
With the new way the intervals are being calculated for the filters #385 , it is possible now to select the units and relationship type as well

**Comment by anne123** [comment]
Thanks - I think with the extra filters and the better ranges it is possible to do sensible searches.  This can be closed :)
