### ISSUE TITLE
Target search - targets returned

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#273]
Searching for dopamine gives 177 targets including ADMET, cell-lines and organisms.  I don't understand why all these are returned.  Current ChEMBL gives 51.

**Comment by mnowotka** [comment]
Interestingly, exactly 51 results are returned when searching for Dopamine (capital D):
![screen shot 2017-10-11 at 18 49 55](https://user-images.githubusercontent.com/837119/31457574-0f8cedec-aeb5-11e7-9240-a03b3e508bbc.jpg)
For dopamine we have indeed 177 targets in results. @juanfmx2, can you exaplain why? Is search case sensitive?

**Comment by mnowotka** [comment]
OK, so after chatting with @juanfmx2 it seems that the reson is that we are fetching additional data from UniChem. We should keep them separate and only show when no results from ChEMBL are there. Also this means that we should lowecase our queries to UniChem as it seems to be case sensitive.

**Comment by juanfmx2** [comment]
This has been fixed!
UniChem Results are not included by default.
