### ISSUE TITLE
Metal containing compounds

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#274]
e.g. CHEMBL364516 - needs to display the metal icon where there is no structure.

**Comment by mnowotka** [comment]
Agree but we can't use old images (they don't fit into the new design and are a bit low quality) and we don't have icons (requested but never got them back).

**Comment by mnowotka** [comment]
@nclopezo @juanfmx2 - new set of icons from Rodica.
[ChEMBL_iconfont_2017.zip](https://github.com/chembl/GLaDOS/files/1441430/ChEMBL_iconfont_2017.zip)

**Comment by nclopezo** [comment]
**This is fixed.**

All the special icons for compounds were updated, all are svg now:

Metal containing:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL364516/
Oligosaccharide:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2108122/
Natural Product:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1201454/
Small Molecule Polymer:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2108458/
Small Molecule:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL3544956/
Antibody:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2109414/
Peptide:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1201644/
Oligonucleotide:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL3545182/
Enzyme:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2107858/
Unknown:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2109133/
Cell:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2107865/
