### ISSUE TITLE
show/hide column options

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#277]
This needs reviewing.  In particular the compound_key is important as it is the name used in the paper.  Also compound pref_name

Remove record_id and activity_id from the list

To me molregno is also useful

**Comment by mnowotka** [comment]
Yes, we should agree on a default set of columns presented and their order.

**Comment by mnowotka** [comment]
Do we still need that issue, having #287, #288, #289, #290, #291, #292, #293?

**Comment by anne123** [comment]
I think the other issues cover this so you can close tis one.
