### ISSUE TITLE
structure search options

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#280]
There are 3 options:
search
similarity
substructure

The search option doesn't seem to work (just results in a scrolling line)
Also I can't get the similarity search to work
Substructure search is very slow

Also find a better name for search as it isn't clear what it is - maybe just use flexmatch?

**Comment by nclopezo** [comment]
I would like to know which was the structure that you were using as query, could you paste here the url of the page? In the url is the query smiles.
For example: https://chembl-glados.herokuapp.com/substructure_search_results/c1ccc(-c2ccccc2)cc1

**Comment by anne123** [comment]
now I can't get the substructure search to work either

**Comment by anne123** [comment]
This was the query
https://chembl-glados.herokuapp.com/flexmatch_search_results/c1ccc(-c2ncncn2)cc1

**Comment by mnowotka** [comment]
@juanfmx2 you asked me yesterday about flexmatch, did you changes something? Anyway, we need a ghost inspector for substructure, similarity and flax match.

**Comment by mnowotka** [comment]
It this issue broader than #280?

**Comment by juanfmx2** [comment]
This has been fixed!
But the name for the search button is still open to discussion . . .

**Comment by mnowotka** [comment]
Yes, so `flexmatch` is quite a long name and also it may refer to a properiatry algorithm so maybe we can find out some better name.

**Comment by anne123** [comment]
I think what this search is doing is a connectivity search i.e it is finding all molecules that have the atoms connected in the same way but doesn't search on specific stereochemistry  or cis/trans isomers examples are  omeprazole and azobenzene. If this is correct would connectivity search work as a name but we should ask others before deciding.

**Comment by mnowotka** [comment]
`connectivity search` is even longer than `flexmatch` and will destroy the whole layout. Can we have just `search` and the 'i' icon next to it? When you hover over that icon there will be a tooltip saying: "click here to read more about how we implement search" or something like this.
![m6ezc](https://user-images.githubusercontent.com/837119/31933875-4c2d7964-b8a2-11e7-9407-1be2d54a35db.png)

**Comment by nclopezo** [comment]
The button now says "connectivity"
