### ISSUE TITLE
Number of targets on Compound search results

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#281]
I did a search for sildenafil and you see sildenafil (175 targets) and sildenafil citrate (19 targets).

I'm not sure this is what people would expect to see (as far as the target is concerned they are the same thing) i.e. parent and salts
Would it be better to group compounds by parents to remove this problem?

**Comment by Emma-Manners** [comment]
On the new version of the website, the activities for alternative forms are aggregated in the activity charts. 

However, there is the option to include or exclude alternative forms as required. 

e.g. https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL192/

<img width="1198" alt="Screenshot 2023-11-01 at 14 31 21" src="https://github.com/chembl/GLaDOS/assets/46962491/3186928c-ae7c-4039-b82b-7206b4a480aa">
