### ISSUE TITLE
Compound search results columns/filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#287]
Anne and I went through the columns/filters shown on the compound results. Here are a few suggestions for sensible defaults etc

Table:
Default and optional columns ok as is. A couple of typos though:
QUED Weighted -> QED Weighted
ACD Logd -> ACD LogD

Filters:
Default filters (in this order):
Molecule Type
Max Phase
RO5 Violations
Molecular Weight
ALogP

Optional filters:
PSA
HBA
HBD
Rotatable Bonds
QED Weighted
ACD LogD
Molecular Species
RO5 Violations (Lipinski)
Therapeutic flag
ATC classification (probably just level 1 is enough)
Availability Type
Administration Route
Black Box Warning

Remove from filters:
Indication class
No. targets
No. bioactivities

**Comment by mnowotka** [comment]
The same question as with #288 - are No.targets and No. bioactivities irrelevant? It seem to be quite important, especially expressed as a histogram.

**Comment by nclopezo** [comment]
This one should be ready:
https://chembl-glados.herokuapp.com/search_results/compounds/Dopamine

**Comment by juanfmx2** [comment]
After a conversation with @agaulton and @anne123 the default configuration for this will be:
```
      # Default Selected
      [
        'molecule_type',
        'max_phase',
        'molecule_properties.num_ro5_violations',
        'molecule_properties.full_mwt',
        'molecule_properties.alogp',
        '_metadata.drug.is_drug',
        '_metadata.related_targets.count',
        '_metadata.activity_count',
      ],
      # Default Hidden
      [
        'molecule_properties.psa',
        'molecule_properties.hba',
        'molecule_properties.hbd',
        'molecule_properties.rtb',
        'molecule_properties.qed_weighted',
        'molecule_properties.acd_logd',
        'molecule_properties.molecular_species',
        'molecule_properties.num_lipinski_ro5_violations',
        'therapeutic_flag',
        'atc_classifications',
        'availability_type',
        'oral',
        'parenteral',
        'topical',
        'black_box_warning',
        'chirality',
        'dosed_ingredient',
        'first_approval',
        'first_in_class',
        'molecule_properties.acd_logp',
        'molecule_properties.acd_most_apka',
        'molecule_properties.acd_most_bpka',
        'molecule_properties.aromatic_rings',
        'molecule_properties.heavy_atoms',
        'molecule_properties.mw_freebase',
        'molecule_properties.num_alerts',
        'natural_product',
        'prodrug',
        'structure_type',
        'usan_stem',
        'usan_year',
        'withdrawn_flag',
      ],
```
However, with the current data is not possible to cover some cases. For that reason, I opened the following 3 issues: #410 , #411 and #412 

This can be closed now! :)
