### ISSUE TITLE
Target search results columns and filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#288]
Suggestions from Anne and I...

Table:
Default columns:
remove Species group (make optional)

Filters:
Default:
Organism
Target Type

Remove:
No. Compounds
No. Bioactivities

**Comment by mnowotka** [comment]
We spent quite some time impelmenting (No. Compounds, No. Bioactivities) filetrs. This was requested by @flatkinson. Any reason to get rid of them?

**Comment by nclopezo** [comment]
The table columns are now as suggested here:
https://chembl-glados.herokuapp.com/targets/
I didn't touch the number of compounds of bioactivities.

**Comment by nclopezo** [comment]
Filters are also ready

**Comment by agaulton** [comment]
Re. removing the number compound/bioactivities filters... I can't see any sensible use-case for filtering on this. I think it is important to show the numbers in the table so you have an idea how much data there is. But I can't see why someone would want to include only targets that have e.g., > 2000 data points and not those that have e.g., 1999 data points (aside from model building which I don't think will be done through the interface). 

You could have one target with 100,000 bioactivity values from pubchem but almost all compounds were inactive vs another target that has only two data points but very valuable information. So I can't see in what circumstances you'd filter on the number of data points (unless to deliberately exclude pubchem assays). 

But this is only mine/Anne's opinion and perhaps Francis has a reason, in which case, happy to keep... 

In either case, the filters are not sensible until we implement binning based on the data distribution as Juan was planning...

**Comment by agaulton** [comment]
Other issues fine, can close

**Comment by mnowotka** [comment]
No worries, I don't know how to notify @flatkinson that this conversation exists, @mention doesn't work on him :P

**Comment by juanfmx2** [comment]
After a conversation with @agaulton and @anne123 the default configuration for this will be:
```
       # Default Selected
      [
        'organism',
        'target_type',
        '_metadata.related_compounds.count',
        '_metadata.activity_count',
      ],
      # Default Hidden
      [
        'tax_id'
      ],
```
However, with the current data is not possible to cover some cases. For that reason, I opened the following 3 issues: #410 , #411 and #412 

This can be closed now! :)
