### ISSUE TITLE
Tissue search results columns/filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#289]
Table:
Default columns:
OK as is

Optional columns:
Add BTO ID and Caloha ID

Filters:
None make sense - remove EFO ID and UBERON ID

**Comment by nclopezo** [comment]
Does this mean that there should be no filters for tissues?

**Comment by nclopezo** [comment]
This one should be ready: 
https://chembl-glados.herokuapp.com/search_results/tissues/liver

**Comment by agaulton** [comment]
looks good

**Comment by juanfmx2** [comment]
After a conversation with @agaulton and @anne123 the default configuration for this will be:
```
 NO FILTERS!
```
However, with the current data is not possible to cover some cases. For that reason, I opened the following 3 issues: #410 , #411 and #412 

This can be closed now! :)
