### ISSUE TITLE
Assay search results columns/filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#290]
Table:
Default columns add:
BAO_format (but with label not ID)
Source (name not src_id)
Document

Default columns remove:
Strain

Optional columns add:
Assay type
Tissue
Cell type
Subcellular fraction
Strain

Filters:
Default:
Organism
BAO format (with labels)
Source (with name)

Optional:
Assay type
Tissue
Cell type
Subcellular fraction
Strain

Remove:
Category
Confidence score

**Comment by mnowotka** [comment]
@agaulton - why should we remove confidence score? There are some ML papers where people are selecting assays with a particualar value of confidence score.

**Comment by agaulton** [comment]
Reasons I'm not keen on confidence score:
1) People often misinterpret what it means e.g., think it is to do with how correct the activity value is rather than just confidence in the assignment of the target to the assay (for this reason, if we do include I think we should call it 'target confidence score' or something and include the description for each score)
2) The same effect can be achieved (but more flexibly and transparently) with the combination of target_type and relationship_type fields 
3) I would like to remove the field from the database at some point because of 1) + 2)

**Comment by juanfmx2** [comment]
After a conversation with @agaulton and @anne123 the default configuration for this will be:
```
       # Default Selected
      [
        'assay_organism',
        'bao_format',
        'src_id',
        'confidence_score',
        'confidence_description',
      ],
      # Default Hidden
      [
        'assay_type',
        'assay_type_description',
        'assay_tissue',
        'assay_cell_type',
        'assay_subcellular_fraction',
        'assay_cell_type',
        'assay_strain',
        'assay_tax_id',
        'relationship_type',
        'relationship_description',
      ],
```
However, with the current data is not possible to cover some cases. For that reason, I opened the following 3 issues: #410 , #411 and #412 

This can be closed now! :)

**Comment by nclopezo** [comment]
**This can be closed if approved.**
All the columns and filters are as agreed:
https://chembl-glados.herokuapp.com/assays/

**Comment by agaulton** [comment]
Looks good. A couple of minor things/questions otherwise can close:

a) Is number of items in a filter restricted to max 10 for everything? (see #459)

b) Confidence score - if we are keeping this, is it possible to combine the score and the description into one filter instead of having two (I think it's a little confusing the way it is) e.g., 
...
7 - Direct protein complex subunits assigned
8 - Homologous single protein target assigned
9 - Direct single protein target assigned

**Comment by nclopezo** [comment]
> a) Is number of items in a filter restricted to max 10 for everything? (see #459)

For now yes, we have discussed with @mnowotka to add advanced options to filters, which will include to select how many bins/buckets you want to see

> b) Confidence score - if we are keeping this, is it possible to combine the score and the description into one filter instead of having two (I think it's a little confusing the way it is) e.g.,

@juanfmx2 is working on it right now.

**Comment by mnowotka** [comment]
Advanced search is one thing and a default values is another. If we know in advance that there are fiters where some or all bins should be presented by default we should do it.

**Comment by mnowotka** [comment]
Also there is a one cosmetic issue that makes me sad, can something be done about it?
![screen shot 2017-11-20 at 13 38 07](https://user-images.githubusercontent.com/837119/33021076-8253b2ea-cdf8-11e7-99fe-bdf7a3ea67f7.jpg)

**Comment by mnowotka** [comment]
OK, I'm closing this one as we have #460 and #459.
