### ISSUE TITLE
Document search results columns/filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#291]
Table:
Default columns add:
Pubmed ID
DOI
Patent ID
Source
Journal

Optional:
Document type
Abstract

Filters:
Defaults:
Document type
Journal
Source
Year (see comment below)

Remove:
Issue
Volume

Year filter - most likely people want to restrict to most recent papers, is it possible to manually configure? Something like <1990, 1990-2000, 2000-2010, 2011, 2012, 2013... etc maybe

**Comment by mnowotka** [comment]
In chembl_app schema, DOCS table doesn't have FK to SOURCE so I can't add it.
@agaulton and @eloyfelix - please have a look.

**Comment by juanfmx2** [comment]
After a conversation with @agaulton and @anne123 the default configuration for this will be:
```
 
```
However, with the current data is not possible to cover some cases. For that reason, I opened the following 3 issues: #410 , #411 and #412 

This can be closed now! :)

**Comment by agaulton** [comment]
Src_id will be added to docs table from chembl_24 onwards (see main chembl schema), but we can leave for now...

**Comment by mnowotka** [comment]
I'd be tempted to push this change even before chembl_24 just to see new data propagation system.

**Comment by nclopezo** [comment]
**This can be closed if approved.** 
The columns and filters are now as agreed.
- The detail about the years filter is covered by https://github.com/chembl/GLaDOS/issues/411
- @juanfmx2 included the source using the indexing scripts, so it is not required from the web services.
https://chembl-glados.herokuapp.com/search_results/documents/Dopamine

**Comment by agaulton** [comment]
Looks good
