### ISSUE TITLE
Cell search results columns/filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#292]
Table:
Default:
add Source tissue
what is 'type' - looks like duplicate of description? Remove

Optional:
CLO ID
EFO ID
Cellosaurus ID
CL LINCS ID

Filters:
Default:
Source organism
Source tissue

Remove all others

**Comment by nclopezo** [comment]
This one should be ready:
https://chembl-glados.herokuapp.com/search_results/cells/liver

**Comment by agaulton** [comment]
looks good

**Comment by juanfmx2** [comment]
After a conversation with @agaulton and @anne123 the default configuration for this will be:
```
       # Default Selected
      [
        'cell_source_organism',
        'cell_source_tissue',
        'cell_source_tax_id'
      ],
      # Default Hidden
      [
      ],
```
However, with the current data is not possible to cover some cases. For that reason, I opened the following 3 issues: #410 , #411 and #412 

This can be closed now! :)
