### ISSUE TITLE
Bioactivity data view columns/filters

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#293]
Table:
Default columns:
Remove assay type

Add:
BAO format (label not ID)
Compound key
Source (name not src_id)
Activity comment
Assay ChEMBL ID (or link description to report card)
Link Document ID to report card

Optional:
Max Phase
Ro5 Violations
Molecular Weight
ALogP
Assay organism
Assay tissue
Assay cell type
Assay sub cellular fraction
Potential duplicate

Remove:
Standard flag
QUDT units
Activity ID
Record ID

Filters:
Default:
Standard type
Target type
Target organism
BAO format
PChEMBL value
Max Phase
Ro5 Violations
ALogP
Molecular Weight
Source

Optional:
Assay type
Standard value
Data validity comment
Journal
Year
Protein family classification (L1)?

**Comment by agaulton** [comment]
see bioassay_ontology table in schema for bao_format labels. Should add these to the assay API endpoint

**Comment by nclopezo** [comment]
Hi Anna, 
I also would like to know which property is 'Compound key'.

**Comment by juanfmx2** [comment]
After a conversation with @agaulton and @anne123 the default configuration for this will be:
```
       # Default Selected
      [
        'standard_type',
        # TODO missing target_type
        'target_organism',
        'bao_format',
        'pchembl_value',
        # TODO missing max_phase
        # TODO missing RO5 violations
        # TODO missing alogp
        # TODO missing molecular weight
        'src_id'
      ],
      # Default Hidden
      [
        'standard_value',
        'standard_units',
        'standard_relation',
        'assay_chembl_id',
        'assay_type',
        'document_chembl_id',
        'document_journal',
        'document_year',
        'ligand_efficiency.bei',
        'ligand_efficiency.le',
        'ligand_efficiency.lle',
        'ligand_efficiency.sei',
        'molecule_chembl_id',
        'potential_duplicate',
        'target_chembl_id',
        'target_tax_id',
      ],
```
However, with the current data is not possible to cover some cases. For that reason, I opened the following 3 issues: #410 , #411 and #412 

This can be closed now! :)

**Comment by mnowotka** [comment]
Comment from @anne123 : "I think ligand efficiencies should be added to the optional columns to view so that you can see the values for a list of compounds." So please close this issue only when ligand efficiencies are added as well. This is taken from issue #420, which I just closed.

**Comment by nclopezo** [comment]
For the record, we reviewed and updated the columns and filters, these are still missing:

- Compound Key.
- Target Type.
- Data validity comment (probably needs an update in WS endpoint).
- Protein family classification.

**Comment by nclopezo** [comment]
**This should be ready**
All the requested columns and filters are there:
https://chembl-glados.herokuapp.com/activities/

**Comment by agaulton** [comment]
Looks good (though not sure if there is much point in having the Assay/Document/Molecule ID filters)
