### ISSUE TITLE
Bioactivity plots in all report cards.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#295]
Some kinds of report cards are missing bioactivity plots normally present in the old interface. We need to ensure there are all in place.

**Comment by nclopezo** [comment]
All the report cards have the charts needed. **BUT** some of them are placeholders. We need to do some denormalisation in the indexes. Se issues:
https://github.com/chembl/GLaDOS-es/issues/1
https://github.com/chembl/GLaDOS-es/issues/2
https://github.com/chembl/GLaDOS-es/issues/3
https://github.com/chembl/GLaDOS-es/issues/4
https://github.com/chembl/GLaDOS-es/issues/5
https://github.com/chembl/GLaDOS-es/issues/6
https://github.com/chembl/GLaDOS-es/issues/7
https://github.com/chembl/GLaDOS-es/issues/8
https://github.com/chembl/GLaDOS-es/issues/9
https://github.com/chembl/GLaDOS-es/issues/10
https://github.com/chembl/GLaDOS-es/issues/11
https://github.com/chembl/GLaDOS-es/issues/12

**Comment by nclopezo** [comment]
**Update: 15 out of 18 charts are ready.**
For the pending ones we need this fix: https://github.com/chembl/GLaDOS-es/issues/15
Pending menas that they still have fake data.

Compound Report Card:

https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/

1. Related Activities pie chart.
2. Related Assays pie chart. 
3. Related Targets pie chart. **PENDING**

Target Report Card

https://chembl-glados.herokuapp.com/target_report_card/CHEMBL1862

4. Related Activities pie chart.
5. Related Compounds.
6. Related Assays pie chart.

Assay Report Card:

https://chembl-glados.herokuapp.com/assay_report_card/CHEMBL1804948

7. Related Activities.
8. Related Compounds.
9. Related Targets. **PENDING**

Document Report Card

https://chembl-glados.herokuapp.com/document_report_card/CHEMBL3734662/

10. Related Targets. **PENDING**
11. Related Assays.
12. Related Activities.

Cell Line Report Card:

https://chembl-glados.herokuapp.com/cell_line_report_card/CHEMBL3307715/

13. Related Assays.
14. Related Activities.
15. Related Compounds.

Tissue Report Card:

hhttps://chembl-glados.herokuapp.com/tissue_report_card/CHEMBL3559723/

16. Related Assays
17. Related Activities
18. Related Compounds

**Comment by nclopezo** [comment]
**All the plots are now there.**
However, I noticed something about the targets. In the tables histograms (#344) the targets are classified by type, but in the report cards they are classified by class. For some targets, this classification is not available. This can cause differences in the numbers obtained. 

For example: You can go to 
https://chembl-glados.herokuapp.com/documents/filter/document_chembl_id:CHEMBL3734662
and select "Targets" in the table options. 
You will see that it has 5 targets. 
But then if you go to the target report card:
https://chembl-glados.herokuapp.com/document_report_card/CHEMBL3734662/
The target summary is classified by class, and in the pie chart you see only 1 Target, the other 4 are missing. 

**You will see the same in the current interface:**
https://www.ebi.ac.uk/chembl/doc/inspect/CHEMBL3734662/

The 5 related targets are:
https://chembl-glados.herokuapp.com/targets/filter/_metadata.related_documents.chembl_ids.%5C*%3ACHEMBL3734662

For the 4 missing, the protein target classification value is "not applicable". 
- https://chembl-glados.herokuapp.com/target_report_card/CHEMBL2367379/
- https://chembl-glados.herokuapp.com/target_report_card/CHEMBL613847/
- https://chembl-glados.herokuapp.com/target_report_card/CHEMBL612545/
- https://chembl-glados.herokuapp.com/target_report_card/CHEMBL375/

What can we do about it? @mnowotka, @agaulton

**Comment by agaulton** [comment]
As discussed - remove the protein target classification chart from the assays card, but for other cards, if there is no data, tweak the message to say:
"No Target Classification data available for xxx CHEMBL3775102 (may be a non-protein target)"
(where xxx is Compound/Document etc)?

**Comment by nclopezo** [comment]
**This is ready**
I added the title for the case discussed.
https://chembl-glados.herokuapp.com/document_report_card/CHEMBL1125056/

**Comment by mnowotka** [comment]
This is amazing, thanks a lot!
