### ISSUE TITLE
Remove flash of unstyled content, add a splash screen / preloader.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#297]
When a main page is loded there is a flash of unstyled content. We can prevent this by producing a splash screen or preloader. Additionally, we should make sure that the search bar is the first element being shown.

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/

**Comment by mnowotka** [comment]
Looks great, thanks!
![screen shot 2018-03-07 at 11 35 13](https://user-images.githubusercontent.com/837119/37090282-a23f4b9e-21fb-11e8-8b0b-6e9ee18c4191.jpg)
