### ISSUE TITLE
Replace fake metabolism section on compound report card with actual values.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#298]
Metabolism section on the compound report card currently always shows a metabolism of aspirine. This has to be replaces with actual real content.

**Comment by nclopezo** [comment]
The section is now real, here are some examples:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1200879
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL88/
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL109/

The preferred name of the substrates and metabolites is missing (https://github.com/chembl/chembl_webservices_2/issues/149), as well as the enzyme chembl id (https://github.com/chembl/GLaDOS-es/issues/16)
**After these 2 properties are added, this issue will be ready.**

**Comment by mnowotka** [comment]
Thanks a lot David, I'm on it! I'll update this thicket when chembl/chembl_webservices_2#149 is ready.

**Comment by nclopezo** [comment]
Now that https://github.com/chembl/chembl_webservices_2/issues/150 is ready, we need to update the index. After this, this issue should be ready. I am writing this so I don't forget.

**Comment by nclopezo** [comment]
**This is ready:**
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/#Metabolism
The fields that were missing are now available.

**Comment by mnowotka** [comment]
Thanks a lot @nclopezo!
