### ISSUE TITLE
Implement structural alters section in the compound report card.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#301]
This is pretty self-explanatory.

**Comment by nclopezo** [comment]
**This is ready:**
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL457419

**Comment by nclopezo** [comment]
The template has been updated and now the images should not be distorted.
