### ISSUE TITLE
Implement the "Browse Drugs" section on the main website.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#303]
Use the new API "drugs" endpoint.

**Comment by nclopezo** [comment]
You can see the new drug browser by going to:
https://chembl-glados.herokuapp.com/drugs
Or, from the main page, by clicking on the "Browse Drugs" tab. 
<img width="1435" alt="screen shot 2017-10-17 at 16 43 58" src="https://user-images.githubusercontent.com/1944922/31674762-86a8208c-b35a-11e7-8908-6ef04040bb96.png">
