### ISSUE TITLE
Add feedback placeholders.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#306]
The new interface should encourage users to give a feedback without having to send an email. This task is about creating a placeholders in:

 - report cards (do you think some properties are incorrect?)
 - results page (do you think results are incorrect?)

There will be a separate issue about finding a right tool to actually implement feedback widgets.

**Comment by nclopezo** [comment]
This is already achieved with hotjar. It would be confusing to have an extra feedback component. I will close this for now and reopen if we decide that later.
