### ISSUE TITLE
Elixir banner and EBI framework integration

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#307]
Since we implemented our default template, EBI has changed thier headers and footers. We should integrate them.

**Comment by mnowotka** [comment]
Just a note that we should inclue Elixir ribbon.

**Comment by mnowotka** [comment]
Sorry guys, I need to include that one in the Public Beta milestone as well because we really need to have the Elixir banner from the very beggining (deadline is end of Q1).

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/

**Comment by mnowotka** [comment]
Thanks Laura. There is a small regression though (maybe not related to this issue). Look at the main search button. On the right there is a one-pixel-wide white space. Can you please remove that and I'll close this issue?
![screen shot 2018-03-02 at 21 34 46](https://user-images.githubusercontent.com/837119/36922949-8f5980aa-1e61-11e8-8fb6-18a73a589d8c.jpg)

**Comment by agaulton** [comment]
Front page is looking really nice now

I'm guessing the 'I am a super cool service' should be changed to 'ChEMBL is an Elixir Core Data Resource' (based on what PDBe/Europe PMC have)?

**Comment by mnowotka** [comment]
But it's true!

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/
I removed the whitespace, eliminated some unwanted scrollbars and changed the Elixir banner text

**Comment by mnowotka** [comment]
Looks great! Thanks Laura.
