### ISSUE TITLE
Integrate BLAST with the main search bar.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#310]
If a biological sequence is pasted this fact can be detected and we can run BLAST to search in large compounds and targets simultaneously and then show results as usual.

**Comment by nclopezo** [comment]
This is done in https://github.com/chembl/GLaDOS/pull/848

**Comment by nclopezo** [comment]
This is not ready. And has some bugs, see for example: https://www.ebi.ac.uk/chembl/beta/g/#search_results/compounds/query=EIVLTQSPATLSLSPGERATLSCRASQSISSYLAWYQQKPGQAPRLLIYDASNRATGIPARFSGSGSGTDFTLTISSLEPEDFAVYYCQQRSNWPLTFGQGTNLEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC

**Comment by nclopezo** [comment]
We are going to implement it as discussed and drafted here:
[SequenceSearchDrafts.pdf](https://github.com/chembl/GLaDOS/files/2795842/SequenceSearchDrafts.pdf)

**Comment by nclopezo** [comment]
Done in https://github.com/chembl/GLaDOS/pull/1044
