### ISSUE TITLE
Fix breadcrumbs

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#314]
They are not clickable now, to it's not possible to navigate.

**Comment by laurajunco** [comment]
This is deployed now but there are a few cases when some breadcrumb links should be different. For example in https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL59/  there's a link for Compound Report Card that goes to a page that doesn't exist. So i will work again on this when the new urls are done.

**Comment by mnowotka** [comment]
Thank you Laura. I'm not closing this one but reassgning this to @nclopezo to finish.

**Comment by nclopezo** [comment]
**The breadcrumb structure has been fixed**
- Breadcrumbs in the main page:
https://chembl-glados.herokuapp.com
- Breadcrumbs in search results:
https://chembl-glados.herokuapp.com/g/#search_results/Dopamine
- Breadcrumbs in browsing entities:
https://chembl-glados.herokuapp.com/g/#browse/compounds/filter/_metadata.related_targets.chembl_ids.%5C*%3ACHEMBL2111359
- Breadcrumbs in structure searches:
https://chembl-glados.herokuapp.com/g/#substructure_search_results/C1CCC(CC1)C1CCCCC1
- Breadcrumbs in report cards: 
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/

**Comment by mnowotka** [comment]
Very comprehensive set of examples, thank you David. Two questions:
 - will this still work then we deploy and root URL will change and will have a different length?
 - Can GhostInspector visit all the URLs you just gave and check if pages exist?

**Comment by nclopezo** [comment]
- will this still work then we deploy and root URL will change and will have a different length?
Yes, I used the url length and a regex to know if the url needs to be shortened., we could tweak them if necessary. 
- Can GhostInspector visit all the URLs you just gave and check if pages exist?
Yes, actually that reminds me that I need to update some of the ghost inspector tests.

**Comment by mnowotka** [comment]
This is now fully approved :D
