### ISSUE TITLE
Infinite view screwed up on substructure search

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#321]
(unless it's meant to look like this!)

![substr_infinite](https://user-images.githubusercontent.com/7058697/31552020-314b1894-b02e-11e7-8496-f0a09c27c8a9.jpeg)

**Comment by mnowotka** [comment]
Interestingly all the bugs mark with Safari label only seem to happen on the latest Mac Books. We don't see this issues happen on older machines. My Safari:

![screen shot 2017-10-13 at 17 15 19](https://user-images.githubusercontent.com/837119/31555755-32bee80c-b03a-11e7-92db-2ace75a44cd4.jpg)

**Comment by mnowotka** [comment]
Sorry, just realised this is an infinite view, checked again and I can reproduce this incorrect bahaviour in any browser.

**Comment by nclopezo** [comment]
This has been fixed, you can check by visiting: 
https://chembl-glados.herokuapp.com/substructure_search_results/c1ccc(-c2ccccc2)cc1
Or by doing any other substructure search.

**Comment by mnowotka** [comment]
It works, thanks!
