### ISSUE TITLE
Heatmap vs retrieving bioactivity data directly

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#324]
Related to issues #252 #275 

A suggestion:
It would be nice on all search results pages (compound/target/assays/documents/tissues/cells) if there was a way to select multiple entries and go directly to the bioactivity data for those.

So how about?

- Using the 'Bioactivity' button (that currently displays the matrix/heatmap view) to do this
- Adding an additional button called 'Heatmap' or 'Matrix' on the Compound/Target results pages that displays the heat map view

**Comment by mnowotka** [comment]
OK, so right now the heatmap does exactly this: if you select some entities on the table the heatmap will only display them. So I guess this task is only about ability to get bioactivity data for selected entities without having to go through the heatmap, correct?

**Comment by nclopezo** [comment]
This is already implemented. The heatmap for the activities view will be created and described in a separate issue.
