### ISSUE TITLE
compound report card plot idea - papers about compound per year

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#330]
![screen shot 2017-10-13 at 23 15 12](https://user-images.githubusercontent.com/837119/31568452-65a5d2da-b06c-11e7-912f-6e8e9520f539.jpg)

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/

**Comment by nclopezo** [comment]
I think we should add something that says "Loading..." to avoid showing the unstyled content. Should that be a new issue?

**Comment by mnowotka** [comment]
There is no need for a new issue, we have one already for a long time: https://github.com/chembl/GLaDOS/issues/297 and yes, this is important!

**Comment by mnowotka** [comment]
Anyway, this ticket is now closed, thanks Laura!

**Comment by mnowotka** [comment]
Hmm, I'm not sure if you noticed but this issue is about compound report card. The issue about the main website is here: https://github.com/chembl/GLaDOS/issues/326 so I'm reopening this one as we need this plot on the compound report cards as well.

**Comment by laurajunco** [comment]
This is deployed now:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL59/
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL112/

**Comment by mnowotka** [comment]
Thanks a lot, closing.
