### ISSUE TITLE
heatmap cells are not rendered correctly

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#332]
If I zoom out, zoom in, or pan I can see some artifacts: cells are not rendered or borders are missing:
![screen shot 2017-10-14 at 23 59 27](https://user-images.githubusercontent.com/837119/31580021-f0a23caa-b13b-11e7-8f02-e4ccd213da83.jpg)

**Comment by nclopezo** [comment]
**This has been fixed.** 
See for example:
https://chembl-glados.herokuapp.com/search_results/compounds/Dopamine

**Comment by mnowotka** [comment]
Thanks a lot!
