### ISSUE TITLE
targets and compounds indetifiers in heatmap should be real links

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#334]
If I hover overy any target or compound identifier in the matrix, the font color changes to green and there is an emphasis. This is like indicting that you are dealing with a link but when I click on identifier nothing happends. What should happen is the report card of selected entity opened in a new tab.

**Comment by nclopezo** [comment]
**This is ready:**
https://chembl-glados.herokuapp.com/search_results/Dopamine

**Comment by mnowotka** [comment]
Works!
