### ISSUE TITLE
Elipsis not working correctly for targets x compounds heatmap

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#335]
Just look at the image:
![screen shot 2017-10-15 at 00 13 00](https://user-images.githubusercontent.com/837119/31580085-bc3d3fe4-b13d-11e7-8d37-b9d979052016.jpg)
How to reproduce it?
1. Open this URL https://chembl-glados.herokuapp.com/search_results/targets/CHEMBL249
2. Switch to bioactivity heatmap view
3. Zoom out

This only happens when targets are in rows.

**Comment by nclopezo** [comment]
**This is [fixed](https://chembl-glados.herokuapp.com/activities/filter/target_chembl_id%3A(%22CHEMBL2111359%22%20OR%20%22CHEMBL3102%22%20OR%20%22CHEMBL2111342%22%20OR%20%22CHEMBL2096970%22%20OR%20%22CHEMBL2093868%22%20OR%20%22CHEMBL4702%22%20OR%20%22CHEMBL2304406%22%20OR%20%22CHEMBL3427%22%20OR%20%22CHEMBL2111341%22%20OR%20%22CHEMBL2096905%22%20OR%20%22CHEMBL3138%22%20OR%20%22CHEMBL2331075%22%20OR%20%22CHEMBL3071%22%20OR%20%22CHEMBL2097165%22%20OR%20%22CHEMBL2095169%22%20OR%20%22CHEMBL238%22%20OR%20%22CHEMBL2096910%22%20OR%20%22CHEMBL2281%22%20OR%20%22CHEMBL2992%22%20OR%20%22CHEMBL3998%22%20OR%20%22CHEMBL339%22%20OR%20%22CHEMBL265%22%20OR%20%22CHEMBL2095396%22%20OR%20%22CHEMBL1850%22%20OR%20%22CHEMBL3361%22%20OR%20%22CHEMBL2574%22%20OR%20%22CHEMBL2368%22%20OR%20%22CHEMBL217%22%20OR%20%22CHEMBL5067%22%20OR%20%22CHEMBL219%22%20OR%20%22CHEMBL2056%22%20OR%20%22CHEMBL5456%22%20OR%20%22CHEMBL2703%22%20OR%20%22CHEMBL234%22%20OR%20%22CHEMBL2967%22%20OR%20%22CHEMBL338%22%20OR%20%22CHEMBL2986%22%20OR%20%22CHEMBL2799%22%20OR%20%22CHEMBL5032%22%20OR%20%22CHEMBL2111460%22%20OR%20%22CHEMBL2095175%22%20OR%20%22CHEMBL2096990%22%20OR%20%22CHEMBL3038478%22%20OR%20%22CHEMBL2111468%22%20OR%20%22CHEMBL2111406%22%20OR%20%22CHEMBL2095201%22%20OR%20%22CHEMBL2094252%22%20OR%20%22CHEMBL2109245%22%20OR%20%22CHEMBL2097175%22%20OR%20%22CHEMBL2363064%22%20OR%20%22CHEMBL3751647%22)/#matrix_fs/Targets)**
