### ISSUE TITLE
Compound report card - Molecule Features

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#338]
We normally only show this section for drugbase compounds (i.e., drugs, clinical candidates, USANS), otherwise there will be a lot of 'unknown' icons.

E.g., CHEMBL147878 shouldn't have the section. 

For all compounds, perhaps we could include the molecule_type (as text) in the top box with the names/structure?

**Comment by nclopezo** [comment]
This has been fixed:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL147878/

**Comment by mnowotka** [comment]
Can't scroll due to the slowness, this is still to improve.

**Comment by nclopezo** [comment]
The scroll slowness has been fixed by https://github.com/chembl/GLaDOS/commit/243dc4fcc4d1d736c7cfce287284330743959e0d.

**Comment by agaulton** [comment]
Look good
