### ISSUE TITLE
Target report card cross refs

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#340]
This is currently fake data, so hard to tell but I think we're missing some of the cross refs:
Open Targets
PharmGKB
Pharos
Reactome
Uniprot (though there is a link to this in the components section)

Also it's not really intuitive how to open these sections to me - with just the top one showing it looks like maybe there isn't any data for the other databases. To open them I would probably click on the chain thing but that takes me to the database home page. Maybe we could have a little drop-down arrow symbol next to the name or something?

**Comment by mnowotka** [comment]
Just to update this issue: it depends on the following:

- https://github.com/chembl/chembl_webservices_2/issues/144
- https://github.com/chembl/chembl_webservices_2/issues/143

Both issues are in progress and hopefully will be closed next week.

**Comment by nclopezo** [comment]
This is now completely represented by https://github.com/chembl/GLaDOS/issues/508
