### ISSUE TITLE
Document report card - Assay Network

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#342]
Not sure how useful this is.

But also never loads for large data sets e.g., PubChem:
https://chembl-glados.herokuapp.com/document_report_card/CHEMBL1201862/

**Comment by mnowotka** [comment]
This heatmap was a prototype of the compounds vs tarets heatmap. It's not very useful now becasue there is something broken there (no way to see compounds, no way to reorder, etc). But I think it is useful in general to present all the assays and compounds extracted from a document but it still needs some work.

**Comment by mnowotka** [comment]
In general we need to revisit report cards since we lost a focus here and it seems that a lot of regression has been intorduced. Tests are needed and a discussion about widgets but I think that cards should show as many data-vis components as possible IF it makes sense.
