### ISSUE TITLE
Tax ID

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#345]
Throughout, we only show organism names, not the tax_id. I think this is probably fine for the interface, but we should include tax_id in exports everywhere we show an organism name. Possibly also have it as an optional column for the interface?

**Comment by mnowotka** [comment]
In general I'd avoid presenting PKs for entities with assigned ChEMBL IDs. But I'm happy to discuss so we can better understand the use case.

**Comment by mnowotka** [comment]
Ah, sorry, just realised that we are talking about organisms! Yes, makes sense :)

**Comment by nclopezo** [comment]
The tax ID has been added as an optional column for Target, Assay, CellLine, Activity. And now it is always included in the downloads. If this is OK this can be closed.

**Comment by agaulton** [comment]
Looks good
