### ISSUE TITLE
UniChem links not working

### ISSUE THREAD

**Issue by ARLEBI** [chembl/GLaDOS#352]
Searched for BRD4 - target - interface seems to pull back correct info from ChEMBL but some (at least) of the external links are not correct. e.g. CanSAR, PDBe, which both point to IKKbeta.

**Comment by mnowotka** [comment]
just to confirm with @nclopezo - these are placeholders, right?

**Comment by nclopezo** [comment]
Yes, they are. I will add the real references when I remove all the placeholders from report cards.

**Comment by nclopezo** [comment]
The UniChem links are not a placeholder anymore. 

See for example: 
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL59/

When there are no UniChem links available the section is not shown:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2109133/

**Comment by nclopezo** [comment]
By the way, I am aware that some of the other links are still placeholders. But this is also covered by https://github.com/chembl/GLaDOS/issues/340 and they will be added soon.
