### ISSUE TITLE
Substructure search

### ISSUE THREAD

**Issue by ARLEBI** [chembl/GLaDOS#356]
searched for NC1CCCCC1O. Seemed to take rather a long time to return results. Then got exactly 1000 hits which seems a suspiciously round number without any explanation that this was some kind of built-in limit...

**Comment by mnowotka** [comment]
Yes, this is a limitation of elasticsearch. I would like to understand how important it is to present all the results - we obviously can overcome this limitation (we already have some ideas) but my impression was that no one would like to browse through more than 1k results manually without adding some additional criteria that will narrow the results.

**Comment by anne123** [comment]
I'd also noticed that you only get 1000 structures back and to me this is not a desired outcome.  I've just run a SSS and some of the structures I got back aren't drug like.  People are going to want to see all the compounds and then filter according to criteria such as LogP and then look at the bioactivity data.  By restricting to some arbitrary set you could miss the most important/interesting data and just see some random structures (as I did on my search).  Many people will want to do the search and down load the structures so they can refine in other software etc.  I can see the need for an upper limit to limit search time but this is probably >100K compounds

**Comment by mnowotka** [comment]
Thanks to @juanfmx2 the limit is now 10k for both text and structure based search. I'm closing this issue now but I created another one: #399, which describes more general problem of setting limits, adressing the tradeoff between volume of data and speed and downloading data in bulk.
