### ISSUE TITLE
Big search button on the main web site not aligned in FF

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#382]
Look at this image:

![screen shot 2017-10-24 at 11 45 32](https://user-images.githubusercontent.com/837119/31939024-111d3eb8-b8b1-11e7-9ec3-eb73531a4192.jpg)

There is 1px wide white horizontal bar to the right from the search button. This need to be remove.

**Comment by nclopezo** [comment]
this has been fixed

**Comment by mnowotka** [comment]
Thanks!
