### ISSUE TITLE
clicking on a suggestion does not display the right tab if I do...

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#384]
1) Search for anything, let's say aspirin
2) Click on one of the tab button except All Results, let's say Compounds
3) Search for something else and click on a suggestion that corresponds to a category which is not, in this case, Compounds. For instance search for dopamine and click on Dopamine D1 receptor in the category Target
4) You should see the expected results except, your are still in the category Compounds instead of Targets

In my opinion, the displayed tab should be Targets or All Results with Targets at the top.

**Comment by agaulton** [comment]
I believe this is fixed now
