### ISSUE TITLE
Sensibly compute buckets so distribution is visible

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#385]
Just look at this facet:
![screen shot 2017-10-24 at 15 34 25](https://user-images.githubusercontent.com/837119/31949337-fc294ce8-b8d0-11e7-94f9-31b695005bd9.jpg)
All the most interesting data is in the first bucket anf then we have 4 outliers scattered across 3 buckets and 4 empty buckets.

Ideally, the 4 outliers should go into a single bucket (100,000+) and the range (0-100,000) should be diveded into 7 remaining bins. If elastic can't do it out of box, we need to write some logic that can do it for us.

**Comment by juanfmx2** [comment]
well we could get some statistical data, and build maybe 2 or 3 dev standar around the mean to cover most cases

**Comment by mnowotka** [comment]
That's the spirit!

**Comment by mnowotka** [comment]
Thanks Juan!
