### ISSUE TITLE
Replace IDs and Enums with appropriate labels

### ISSUE THREAD

**Issue by juanfmx2** [chembl/GLaDOS#410]
The following fields require to be updated with the proper labels for filtering:

Across All entities:
- SRC_ID -> Source Name
- Tax_id -> Taxonomy Tree With names
- BAO format -> BAO Label
- Assay Type -> F = Functional, etc

On Assay:
- Join labels for Confidence Score and Confidence Description
- Join labels for Relationship Type and Relationship Description

On Activity:
- Include Target Type
- Include max phase
- Include RO5 violations
- Include alogp
- Include full_mwt

On Compound:
- Availability type
- Chirality
- ATC Classifications first Level

On Target:
- Protein Family Levels 1 and 2

**Comment by juanfmx2** [comment]
This is fixed now!

**Comment by mnowotka** [comment]
Thanks Juan!
