### ISSUE TITLE
Filters that are CHEMBL IDS should present a mini report card on hover

### ISSUE THREAD

**Issue by juanfmx2** [chembl/GLaDOS#412]
Filters that are CHEMBL ID's like molecule_chembl_id, or target_chembl_id for activities should present a mini report card on hover

**Comment by nclopezo** [comment]
**This is ready**
To check you can go to https://chembl-glados.herokuapp.com/activities/
and then select filters like 'Molecule', 'Target', 'Assay' or 'Document'

**Comment by mnowotka** [comment]
Can I have a screenshot please?
