### ISSUE TITLE
Target Report Card - MWT distribution

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#419]
It only seems to be possible to select one bin at a time and display the bioactivity data.  A logical thing to want to do would be to elect all compounds with a MWT between 300 and 500 for example.  Also it would be better if the bins were better ranges <100, 100-200 etc.

**Comment by mnowotka** [comment]
There are 4 other issues that cover this one I think:
 - #385
 - #323 
 - #296
 - #294 

Also I don't think this is really a bug.
