### ISSUE TITLE
Ligand efficiencies as columns in activities table

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#420]
I'm not sure if we discussed or captured this but we have an option now to filter on ligand efficiencies but not then display them in the table.  I think ligand efficiencies should be added to the optional columns to view so that you can see the values for a list of compounds.

**Comment by mnowotka** [comment]
The full list of default and optional columns and filters for activities is descibed in this issue: #293. It's still open so I'll close this one and add a comment that we should have them in optional columns.
