### ISSUE TITLE
Search compound-target activity

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#437]
I have a compound and I want to know if there is an activity on ChEMBL for this compound on a given target.
Currently the only way to that is using the web service or to create a custom query with the new website (by the way, thank you Patricia and Juan for showing me how to do).
You can also search for a compound and look in the bioactivities if there is the target (the bioactivitiy heatmap is useful to do so but this visualisation is not easy if there are many targets). But when you have several hundred of activities, you really don't want to do that.

The solution is likely to add a free text search field in the bioactivity result to filter on the targets.

I know it is a duplicate of an existing issue, but to my knowledge this simple use case was not describe previously (my apologies if it did) so it should be described here. I think several users could be interested because I have just been asked how to do that by a former colleague who does this kind of search frequently and does not find the current solution easy.

**Comment by Emma-Manners** [comment]
We have some training materials and worked examples that show how to perform these types of searches using the interface and API:

https://www.ebi.ac.uk/training/online/courses/embl-ebi-programmatically/chembl-programmatically/
https://www.ebi.ac.uk/training/events/guide-explore-drug-compounds-and-their-biological-targets-using-chembl/
https://github.com/chembl/notebooks

We also have a bioactivity data filter for compound-target pairs:

<img width="1318" alt="Screenshot 2023-11-01 at 14 15 32" src="https://github.com/chembl/GLaDOS/assets/46962491/82248e6c-c4c7-4fdb-abd6-308b017b55aa">
