### ISSUE TITLE
why am I seeing these results?

### ISSUE THREAD

**Issue by ARLEBI** [chembl/GLaDOS#443]
Using my familiar query of BRD4 and selecting targets... I get one compound but I can't see why... so far as I can tell "brd4" doesn't occur in its smiles string, inchi etc. 
The compound returned is CHEMBL3828396

**Comment by mnowotka** [comment]
I'm sure @juanfmx2 will be able to answer this question but this reminds me that result highlighting (#305) is an important feature.

**Comment by juanfmx2** [comment]
yes In this case it is because that compound has the following data in its compound records

```
compound_records: [
    {
        compound_name: "N-(4-amino-4'-fluorobiphenyl-3-yl)tetrahydro-2H-pyran-4-carboxamide",
        compound_key: "**BRD4**884"
    }
],
```
