### ISSUE TITLE
implement a fullscreen mode for the heatmap

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#445]
Most of the data-vis components in GLaDOS have a fullscreen option but not the heatmap. And this is important to have it for al leat two reasons:

1. Heatmaps can be huge so every pixel is important.
2. Full screen option with mean haveing a separate view to which we can directly link. No more links to 'Dopamine' and having to click on the 'heatmap' button to see it.

**Comment by nclopezo** [comment]
**This is ready:**
This is the link to go to the search results:
https://chembl-glados.herokuapp.com/search_results/Dopamine

This is the standalone, shareable [link](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id%3A(%22CHEMBL59%22%20OR%20%22CHEMBL1557%22%20OR%20%22CHEMBL457419%22%20OR%20%22CHEMBL138040%22%20OR%20%22CHEMBL456176%22%20OR%20%22CHEMBL138921%22%20OR%20%22CHEMBL250711%22%20OR%20%22CHEMBL456817%22%20OR%20%22CHEMBL141970%22%20OR%20%22CHEMBL1256484%22%20OR%20%22CHEMBL531%22%20OR%20%22CHEMBL160074%22%20OR%20%22CHEMBL512943%22%20OR%20%22CHEMBL301265%22%20OR%20%22CHEMBL1201087%22%20OR%20%22CHEMBL350361%22%20OR%20%22CHEMBL348924%22%20OR%20%22CHEMBL589%22%20OR%20%22CHEMBL347228%22%20OR%20%22CHEMBL1371770%22%20OR%20%22CHEMBL1303%22%20OR%20%22CHEMBL3247442%22%20OR%20%22CHEMBL1009%22%20OR%20%22CHEMBL2110659%22%20OR%20%22CHEMBL2110793%22%20OR%20%22CHEMBL3545010%22%20OR%20%22CHEMBL3545388%22%20OR%20%22CHEMBL28278%22%20OR%20%22CHEMBL1823681%22%20OR%20%22CHEMBL1328898%22%20OR%20%22CHEMBL718%22%20OR%20%22CHEMBL2105069%22%20OR%20%22CHEMBL2105691%22%20OR%20%22CHEMBL300443%22%20OR%20%22CHEMBL1200748%22%20OR%20%22CHEMBL2104864%22%20OR%20%22CHEMBL1743952%22%20OR%20%22CHEMBL57241%22%20OR%20%22CHEMBL588%22%20OR%20%22CHEMBL493%22%20OR%20%22CHEMBL69271%22%20OR%20%22CHEMBL2104081%22%20OR%20%22CHEMBL1631970%22%20OR%20%22CHEMBL596802%22%20OR%20%22CHEMBL2106075%22%20OR%20%22CHEMBL2110687%22%20OR%20%22CHEMBL1201236%22%20OR%20%22CHEMBL459%22%20OR%20%22CHEMBL2103827%22%20OR%20%22CHEMBL1631968%22%20OR%20%22CHEMBL51910%22%20OR%20%22CHEMBL1743949%22%20OR%20%22CHEMBL2364614%22%20OR%20%22CHEMBL2106525%22%20OR%20%22CHEMBL273575%22%20OR%20%22CHEMBL287257%22%20OR%20%22CHEMBL2106980%22%20OR%20%22CHEMBL2104184%22%20OR%20%22CHEMBL1256842%22%20OR%20%22CHEMBL53%22%20OR%20%22CHEMBL2107788%22%20OR%20%22CHEMBL3247441%22%20OR%20%22CHEMBL1188395%22%20OR%20%22CHEMBL536282%22%20OR%20%22CHEMBL1201728%22%20OR%20%22CHEMBL1172928%22%20OR%20%22CHEMBL1201066%22%20OR%20%22CHEMBL3039565%22%20OR%20%22CHEMBL337702%22%20OR%20%22CHEMBL2106783%22%20OR%20%22CHEMBL2107365%22%20OR%20%22CHEMBL1118%22%20OR%20%22CHEMBL637%22%20OR%20%22CHEMBL1615372%22%20OR%20%22CHEMBL1200997%22%20OR%20%22CHEMBL1237021%22%20OR%20%22CHEMBL1712%22%20OR%20%22CHEMBL708%22%20OR%20%22CHEMBL1324%22%20OR%20%22CHEMBL2103767%22%20OR%20%22CHEMBL2106351%22%20OR%20%22CHEMBL493682%22%20OR%20%22CHEMBL2107261%22%20OR%20%22CHEMBL2105358%22%20OR%20%22CHEMBL2105459%22%20OR%20%22CHEMBL53929%22%20OR%20%22CHEMBL334491%22%20OR%20%22CHEMBL953%22%20OR%20%22CHEMBL2106804%22%20OR%20%22CHEMBL1275%22%20OR%20%22CHEMBL307739%22%20OR%20%22CHEMBL2218888%22%20OR%20%22CHEMBL509336%22%20OR%20%22CHEMBL1026%22%20OR%20%22CHEMBL2104671%22%20OR%20%22CHEMBL86882%22%20OR%20%22CHEMBL660%22%20OR%20%22CHEMBL887%22%20OR%20%22CHEMBL396778%22%20OR%20%22CHEMBL1201212%22%20OR%20%22CHEMBL972%22%20OR%20%22CHEMBL2107608%22%20OR%20%22CHEMBL1201319%22%20OR%20%22CHEMBL524%22%20OR%20%22CHEMBL1437%22%20OR%20%22CHEMBL1160714%22%20OR%20%22CHEMBL1201251%22%20OR%20%22CHEMBL2104207%22%20OR%20%22CHEMBL2105040%22%20OR%20%22CHEMBL2105064%22%20OR%20%22CHEMBL926%22%20OR%20%22CHEMBL1201234%22%20OR%20%22CHEMBL358040%22%20OR%20%22CHEMBL77622%22%20OR%20%22CHEMBL33720%22%20OR%20%22CHEMBL434%22%20OR%20%22CHEMBL211456%22%20OR%20%22CHEMBL1215%22%20OR%20%22CHEMBL679%22)/#matrix_fs/Compounds)
