### ISSUE TITLE
change cursor to hand when dragging mode on in heatmap

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#446]
Sometimes I'm confused what will happen when I drag the heatmap. It would be great to change the cursor to hand then the drag mode is on.

**Comment by nclopezo** [comment]
The cursor now changes when grabbing:
https://chembl-glados.herokuapp.com/search_results/Dopamine

**Comment by mnowotka** [comment]
Works like a charm, thanks!
