### ISSUE TITLE
Remove rows/columns tooltips when hovering above heatmap cells.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#447]
This was discussed today.

**Comment by nclopezo** [comment]
The tooltips from the rows/columns headers with be hidden if not interacted with them in 100 ms.
https://chembl-glados.herokuapp.com/search_results/Dopamine

**Comment by mnowotka** [comment]
Hmmm....
![screen shot 2017-11-17 at 11 56 03](https://user-images.githubusercontent.com/837119/32946163-58538d9c-cb8e-11e7-87df-7023635fc4af.jpg)

**Comment by nclopezo** [comment]
This is because of the CORS issue, which is affecting also the report cards. It's not related to the show/hide of the tooltips/

**Comment by mnowotka** [comment]
OK, I see this for the first time and I though that the CORS problem only occurs inside GhostInspector. If it occurs in mainstream browsers this needs to be fixed.

**Comment by mnowotka** [comment]
OK, it seems to be working now, an hour ago all I could see was a bunch of error tooltips.
I think we found a best compromise and I'm closing this but I'll keep the CORS issue open.
