### ISSUE TITLE
Number of items in a filter

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#459]
Does the number of items in a filter have to be restricted to ten for everything? For example, for the BAO_FORMAT, there are only 14 distinct formats (plus null, which shouldn't be there - my fault - and 'assay_format' which is a high-level catch-all term), so it would be nice if we could show them all. Currently, you could not filter on 'biochemical format' for example. 

I wouldn't suggest this for everything (like activity types), but I think there are certain key fields where you could want to choose any value even if not the most 'frequent' (source might be another example). Would there be a way to 'see more', or show the full list if you click on 'other categories' or something like that?

**Comment by agaulton** [comment]
Filters where I think it definitely makes sense to show all values:
Molecule_type
Target_type
BAO_format
Source

Others where showing all could still be useful, but will be a lot of values:
Journal name
Organism
ATC classification (maybe just the first couple of levels)
USAN stems

**Comment by juanfmx2** [comment]
This is ready! I updated the number of categories to 20 for those props. I would discourage showing more, because the lists can get quite big, but it can be done if requested.

**Comment by mnowotka** [comment]
OK, I'm closing this, @agaulton feel free to reopen if necessary.
