### ISSUE TITLE
Long filter values visually clash with numbers

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#460]
Like this:

![screen shot 2017-11-20 at 13 38 07](https://user-images.githubusercontent.com/837119/33021659-94ab232c-cdfa-11e7-9550-33b8b1b7b743.jpg)

Here:
https://chembl-glados.herokuapp.com/assays/

**Comment by nclopezo** [comment]
**This has been fixed.**
The way the width of the texts is calculated was changed, and a small padding between the text and the count has been added. It should be better now:
https://chembl-glados.herokuapp.com/assays/

**Comment by mnowotka** [comment]
Perfect, thanks!
