### ISSUE TITLE
open chemical editor after clicking on thumbnail in compound report card

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#461]
In the old interface, clicking on the compound image caused an editor to pop up:
https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL192

A similar behaviour should be implelmented in the new compound report card.

**Comment by nclopezo** [comment]
**This is ready:**
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL192/

**Comment by mnowotka** [comment]
Thanks David!
