### ISSUE TITLE
Metal containing compound image not displayed in activity infinite view

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#469]
If you go here: https://chembl-glados.herokuapp.com/activities/ and scroll hard enough you will see this compound:
![screen shot 2017-11-21 at 20 05 08](https://user-images.githubusercontent.com/837119/33094278-8203a99e-cef7-11e7-84e6-6807b6c6de93.jpg)
It's metal containing one so no image is available, still it should be replace by a placeholder.

**Comment by juanfmx2** [comment]
it is easier to reproduce this way:
https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL1985413

**Comment by mnowotka** [comment]
Great, we need a Ghost Inpector test for that.

**Comment by nclopezo** [comment]
**This has been fixed.** 
There are many different cases for the special images. I added tests for them. 

Jasmine Tests:
http://chembl-glados.herokuapp.com/js_tests/?spec=Activity

Ghost Inspector:
https://app.ghostinspector.com/tests/59ef3a1f38399239575bf919

Examples:

[Metal Containing](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL1985413)
[Oligosaccharide](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL1201460)
[Natural Product](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL1201469)
[Small Molecule Polymer](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL2108139)
[Small Molecule](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL3527276)
[Peptide](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL1201866)
[Enzyme](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL2108147)
[Unknown](https://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id:CHEMBL1909064)

There are no activities with:
[Oligonulceotide Image](http://chembl-glados.herokuapp.com/activities/filter/_metadata.parent_molecule_data.image_file:%22oligonucleotide.svg%22)
[Cell Image](http://chembl-glados.herokuapp.com/activities/filter/_metadata.parent_molecule_data.image_file:%22cell.svg%22)
