### ISSUE TITLE
Implement URL hashing

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#470]
Since URL can only have a limited lenght we should start looking at this problem. Theretically one can apply infinite number of filters resulting in infinitely long URL. Hashing it and sever-side resolution of such a hash should solve the problem.

**Comment by nclopezo** [comment]
**This is ready**
You can try urls like:
https://chembl-glados.herokuapp.com/g/tiny/vn8jUhI3wnY9P/Et+AFDmQ==
https://chembl-glados.herokuapp.com/g/tiny/ehJCV+FgFkeQregJ9arWmw==
https://chembl-glados.herokuapp.com/g/tiny/mLoCaXn56poZJEk3OoA29w==

In the heatmap, when it needs to shorten a url it shows the loader, then it directs you to the shortened url. Unfortunately this could required that the user disables pop up blocking for glados.

**Comment by mnowotka** [comment]
Thanks David!
