### ISSUE TITLE
Searching by Uniprot id

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#472]
I tried to search for a uniprot id P55072
It returned >11000 targets it should return one.

This was in response to a user query  - I wanted to try and see how  the new interface would work
The actual question was to search for a list of uniprot iDs but again this doesn't work

**Comment by juanfmx2** [comment]
I just checked, and it is definitely a bus, the term is being completely ignored, and actually in brings back all the documents for all the entities.

you can use "P55072" will provide a exact match in the meantime, and while I fix this

**Comment by juanfmx2** [comment]
This is ready and deployed!

**Comment by nclopezo** [comment]
Unstoppable!!!
