### ISSUE TITLE
Target search

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#486]
I searched for the target CCR5 but the specific options are for things starting with CCR not CCR5 so I don't see the specific thing I am interested in.  Search should be less general?

see attached screenshot
![screen shot 2017-11-28 at 10 17 18](https://user-images.githubusercontent.com/3308733/33314404-6f936b86-d425-11e7-93ae-9c3eadfe349b.png)

**Comment by juanfmx2** [comment]
In this case probably the server was not fast enough and the answer for CCR autocomplete arrived after and replaced the answer for CCR5 if you erase and rewrite you'll get the values for CCR5. However, I'll work on making the response time more accurate.
