### ISSUE TITLE
Make target synonyms list unique on target report card

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#487]
Example taken from: https://chembl-glados.herokuapp.com/target_report_card/CHEMBL3301384/

![screen shot 2017-11-28 at 10 25 04](https://user-images.githubusercontent.com/837119/33314755-8637818c-d426-11e7-9a9b-3a6e06b54615.jpg)

**Comment by juanfmx2** [comment]
I don't know if there is any difference between:

```
{
component_synonym: "CCR5",
syn_type: "GENE_SYMBOL"
},
{
component_synonym: "CCR5",
syn_type: "UNIPROT"
},
```
https://www.ebi.ac.uk/chembl/api/data/target/CHEMBL3301384.json
should we put different badge colors depending on the syn_type?

**Comment by mnowotka** [comment]
It is but not in a way we present a data (currently we don't destinquish between different synonym types) so in order to avoid confusion on the client side before rendering a list duplicates should be removed.

**Comment by laurajunco** [comment]
This is ready https://chembl-glados.herokuapp.com/target_report_card/CHEMBL3301384/

**Comment by mnowotka** [comment]
Thanks Laura!
