### ISSUE TITLE
Target Report Card Column sorting

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#488]
On the compound report card and the "approved drugs section" The default order for the max_phase should be 4 then 3 then 2 etc
When I try to sort on max phase it only sorts low to high I can't get it to sort the other way (i.e what you would normally want to see).  This was on the CCR5 human target (CHEMBL274)

**Comment by agaulton** [comment]
Please note, this is TARGET report card

**Comment by Emma-Manners** [comment]
Now resolved. 
The default order for the max phase is now descending (4->3->2->1). 
There is also an option to sort low to high.
