### ISSUE TITLE
Assay and documents search

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#491]
Searched for immune response but only gave specific option in documents. 

Displaying all assays on assays page.  Don't need confidence score and confidence description as defaults (description only).  Also they work in different ways i.e confidence shows entries where there is no data but confidence description doesn't.

Can't display the bioactivity data from this page which would be the obvious next step

Same is true from documents page - there is no way to get to the data from this page.

Ability to display abstracts in the docs table is a nice and useful feature :)

**Comment by agaulton** [comment]
This is mostly fixed now except that assays are still not suggested in search. Think this is to do with intricacies of elastic since other terms work...
