### ISSUE TITLE
Missing 'Withdrawal Information' section for Compound report card

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#492]
A know this isn't finished yet but there doesn't seem to be a section for withdrawn information e.g 
in this example https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL111

**Comment by nclopezo** [comment]
**This is ready:**
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL111/

**Comment by mnowotka** [comment]
Would it be possible to style it like it look like a warning?

**Comment by nclopezo** [comment]
Like this?
<img width="754" alt="screen shot 2017-12-11 at 16 52 49" src="https://user-images.githubusercontent.com/1944922/33842907-cb94597c-de93-11e7-8bc4-cf442d354b72.png">

**Comment by mnowotka** [comment]
Yeah!

**Comment by nclopezo** [comment]
The update is now deployed
