### ISSUE TITLE
browse activities

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#495]
Is it possible to do multiple selections of the filters - for example trying to choose all compounds with logP<4 and MWT <400 takes a long time as you have to select one range at a time

Also the compound images in the table are too small to be able to read - can there be an option to make these bigger and hence readable.

**Comment by mnowotka** [comment]
Selecting by dragging in histograms was described in this issue: https://github.com/chembl/GLaDOS/issues/509.
Zooming compound images in table was described in this issue: https://github.com/chembl/GLaDOS/issues/639.
So I'm closing that one.
