### ISSUE TITLE
Browse targets doesn't yet work

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#506]
The browse targets tab is not yet implemented. Can't retrieve targets or browse by organism/GO.
Just putting this in to make sure we capture

**Comment by nclopezo** [comment]
I am not sure what you mean. We already have this page: 
https://chembl-glados.herokuapp.com/targets/

**Comment by mnowotka** [comment]
I think this is about broswe targets tab on the main webpage, right?
![screen shot 2017-11-30 at 12 48 36](https://user-images.githubusercontent.com/837119/33431833-c46e302e-d5cd-11e7-8bdf-cd0d56b47727.jpg)

**Comment by nbosc** [comment]
Is it possible to fix the Browse Targets tab so the target family names do not overlap with the boxes?

**Comment by nclopezo** [comment]
@laurajunco is setting up this and (https://github.com/chembl/GLaDOS/issues/326) as the first 2 main visualisations in the main page. So we will fix that this or next week I think.

**Comment by nclopezo** [comment]
This is obsolete
