### ISSUE TITLE
Browse drug targets/indications views

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#507]
We have these as separate tabs on the old interface - do we want to do the same or something different? Either way, I think we should have some larger-scale way to search/display this data than just on the compound/target report cards...

**Comment by mnowotka** [comment]
Just for the record - we have "something" (there is a browse targets tab in the new interface) but it was not changed for a long time, some stuff got rusty and still there are many competeing ideas how to do it best. I'm hoping to kick off with the work aroud main website early in 2018 but this requires some ideas and brainstorming.
![screen shot 2017-11-30 at 12 48 36](https://user-images.githubusercontent.com/837119/33431654-1cf7321e-d5cd-11e7-98ce-58b78b2db978.jpg)

**Comment by nclopezo** [comment]
We have now a visualisation for targets in the main page. We already discussed and plan to create pages to browse mechanisms of action and drug indications(#953, #954).
