### ISSUE TITLE
Add "activities" view as a common view for all search results

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#513]
At the moment different search results have different kinds of views associated with them:

1. Views for compound results:
![screen shot 2017-12-04 at 12 28 26](https://user-images.githubusercontent.com/837119/33552963-aee29028-d8ee-11e7-8fff-b7bccf28da79.jpg)
2. Views for targets:
![screen shot 2017-12-04 at 12 29 06](https://user-images.githubusercontent.com/837119/33553015-ee837ac6-d8ee-11e7-9cb5-328ae869f944.jpg)
3. Views for documents:
![screen shot 2017-12-04 at 12 31 07](https://user-images.githubusercontent.com/837119/33553042-06c6b51c-d8ef-11e7-8ce2-b3fe5f36054b.jpg)

And so on...

This task would consist of two subtasks:

- [ ] Rename something that is currently call "Bioactivities" to "Heatmap"
- [ ] Add a new view called "Bioactivities" that will show a list of related bioactivities. This view would be common to all the results.

Actually, the best implementation of such a "view" would be simply redirectling to the bioactivities search results (https://chembl-glados.herokuapp.com/activities/filter/...) becaue then we can do other cool things.

**Comment by nclopezo** [comment]
We agreed with @agaulton that the "Bioactivity View' will be called 'Heatmap'.
- There is already a link to browse all activities.
- Heatmap is an specific preconfigured and easy to use way of visualising the activities.
- The plan is to enhance the [activities browser](https://chembl-glados.herokuapp.com/g/#browse/activities) (see https://github.com/chembl/GLaDOS/issues/514) to have a more complex 'heatmap section' with menu that will allow the user to configure the heatmap that they want to see.  
  - The first idea for the configuration is to select what will be in x axis and what will be in y (compounds, targets, documents, etc...)

**Comment by nclopezo** [comment]
This was shown to @agaulton before closing.
