### ISSUE TITLE
Enhance "Browse Activities" view with ability to jump to related entities

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#514]
The "Browse Acitivities" (https://chembl-glados.herokuapp.com/activities/) view is a heart of GlaDOS but it doens't have all the nice functionalities it diserves. What would be nice is:

- [ ] To have an ability to jump to compounds view. In that case compounds would be a unique list of those icluded in the current bioactivities view.
- [ ] To have a similar ability to jump to targets view.
- [ ] To have a similar ability to jump to documents view.

In case of compounds and targets we can do even better. We can enhance this:

![screen shot 2017-12-04 at 12 48 25](https://user-images.githubusercontent.com/837119/33553638-7aa74ce2-d8f1-11e7-8d3e-88f6a1fc0141.jpg)

By adding two more icons:

- [ ] compouns vs targets heatmap
- [ ] targets vs compounds heatmap

Of course, other kinds of heatmap (documents vs compounds, documents vs targets) are possible as well.

**Comment by nclopezo** [comment]
This has been already implemented. Further improvements will be discussed.
