### ISSUE TITLE
Find the best set of sorting/coloring criteria for heatmap.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#516]
So far the heatmap can be coloured by:

 - Activity Count
 - pChEMBL Value Avg

And rows and columns can be sorted by:

 - Activity Cound
 - pChEMBL Value Max
 - Hit Count

This may not be the optimal selection. As discussed with @ARLEBI, @anne123, @agaulton, @nclopezo and @juanfmx2 we should discuss the best available set of criteria.

**Comment by anne123** [comment]
I would keep this simple for now.  Colour by activity count or pCHEMBL value (but I would use max not average to be consistent with sorting).

Likewise sort by activity count and pCHEMBLmax - I can't remember what hit count is

**Comment by nclopezo** [comment]
N/A
