### ISSUE TITLE
Results views should be embedable.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#521]
When designing report cards we spent some time making sure different components are embedable. The same should be applied to search results. In particular, it should be possible to embed:

- [x] heatmap
- [x] scatterplot
- [x] table
- [ ] any mini report card from results

**Comment by nclopezo** [comment]
**This is ready.**
You can check by visiting:
https://chembl-glados.herokuapp.com/g/#search_results/all/query=Dopamine

**Comment by mnowotka** [comment]
One comment: I would rethink placement of "embed" buttons, both for the whole results page and for a single card. Button for the whole page is above top pagination, which is not very intuitive and button on every mini report card occupies the space that could be used by substructure/similarity search buttons.

**Comment by nclopezo** [comment]
Yes, we were thinking that in the cards we can add three dots (...) and show more options, but right now the only option available is to embed.
