### ISSUE TITLE
Make all table headers sticky.

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#523]
We have realised that when you scroll down the activities table the header disappears.  This should remain as otherwise you don't remember what the different columns are.

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/g/#search_results/all/query=Dopamine

**Comment by nclopezo** [comment]
It works, thank you!
(We agreed with Anne and Anna to close this kind of issues between us.)
