### ISSUE TITLE
result container without any results takes too much space

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#527]
This is how "Cell Lines" container looks like when there are no results:

![screen shot 2017-12-10 at 18 07 54](https://user-images.githubusercontent.com/837119/33807865-2397978e-ddd5-11e7-8ce3-9244f93dfc97.jpg)

There is way too much of white space here.

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/search_results/Dopamine
![screen shot 2018-02-26 at 11 26 33](https://user-images.githubusercontent.com/17466890/36668052-f19748d8-1ae7-11e8-82bf-4656b0ab3dad.png)

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/search_results/Dopamine
![screen shot 2018-02-26 at 12 25 31](https://user-images.githubusercontent.com/17466890/36670426-328c524a-1af0-11e8-80f3-966766e51a1e.png)

**Comment by mnowotka** [comment]
Perfect! Thanks Laura!

**Comment by nclopezo** [comment]
The tissue results don't have any filter (this was agreed with @agaulton before). But now it doesn't show the results:
http://chembl-glados.herokuapp.com/search_results/tissues/Liver

**Comment by nclopezo** [comment]
That reminds me that we need to review and pay attention to the ghost inspector tests, 4 are failing right now.
