### ISSUE TITLE
Piecharts in report cards should be displayed side by side

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#528]
I think this is similar to #116 and #264. The gist is too save some space in the report cards to save users from scrolling. Another way to save some space on large and medium (laptop) screens would be to present piecharts side by side not on under another. This would also mean changing scrollspy because those 3 piecharts are now 3 single entries in the scrollspy.

For the reference, I'm pasting a full view of the compund report card to give an idea how long it is now.
![windows_8 1_firefox_57_ 64-bit _1366x768_chromeless](https://user-images.githubusercontent.com/837119/33807983-b7029aea-ddd6-11e7-9d9e-bc09d75f2828.png)

**Comment by laurajunco** [comment]
This is ready:

https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL59/
https://chembl-glados.herokuapp.com/target_report_card/CHEMBL2366498/
https://chembl-glados.herokuapp.com/assay_report_card/CHEMBL1804948/
https://chembl-glados.herokuapp.com/document_report_card/CHEMBL2086259/
https://chembl-glados.herokuapp.com/cell_line_report_card/CHEMBL3308584/
https://chembl-glados.herokuapp.com/tissue_report_card/CHEMBL3559723/

**Comment by mnowotka** [comment]
This is great @laurajunco, thanks a lot. Before I close this issue, can you please try to position the lagend out of the plot? I found this example: https://codepen.io/bmarker/pen/mqbZEQ, can you try it?

**Comment by mnowotka** [comment]
Another problem can be seen on this card: https://chembl-glados.herokuapp.com/document_report_card/CHEMBL2086259/. Can we make sure that even if data is not there the container maintains the same size if the layout is two column? Otherwise it doesn't look good.
![screen shot 2018-01-23 at 18 39 38](https://user-images.githubusercontent.com/837119/35293873-f9f9a772-006c-11e8-8c5b-e66bee393cad.jpg)

**Comment by nclopezo** [comment]
I just noticed that we forgot to change the scrollspy. I will tell Laura tomorrow.

**Comment by mnowotka** [comment]
OK, so now we have three things to fix :P

**Comment by nclopezo** [comment]
It would be 3 sections merged in one? So in the scrollspy instead of for example here:
https://chembl-glados.herokuapp.com/document_report_card/CHEMBL2086259/#AssaySummary

- "Protein Target Summary"
- "Assay Summary"
- "Bioactivity Summary"

There would be one section, with a new name? what would this name be?

**Comment by mnowotka** [comment]
Activity plots?

**Comment by nclopezo** [comment]
OK

**Comment by laurajunco** [comment]
This is ready:

https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL59/
https://chembl-glados.herokuapp.com/target_report_card/CHEMBL2366498/
https://chembl-glados.herokuapp.com/assay_report_card/CHEMBL1804948/
https://chembl-glados.herokuapp.com/document_report_card/CHEMBL2086259/
https://chembl-glados.herokuapp.com/cell_line_report_card/CHEMBL3308584/
https://chembl-glados.herokuapp.com/tissue_report_card/CHEMBL3559723/

**Comment by mnowotka** [comment]
Woohoo! This is great! Congrats @laurajunco on your first closed issue!
