### ISSUE TITLE
carousel view should have prev/next overlay buttons instead of pagination.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#530]
This is what we have now in terms of navigation between items in carousel: there is a pagination below the items, which takes some extra space

![screen shot 2017-12-10 at 18 54 32](https://user-images.githubusercontent.com/837119/33808285-979abec6-dddb-11e7-9ab2-c532a064424b.jpg)

This is what I would like to have, instead of pagination there are two buttons overlaying the items so the don't take any more vertical space.

![screen shot 2017-12-10 at 18 58 08](https://user-images.githubusercontent.com/837119/33808311-2d2d737a-dddc-11e7-8986-b3bc893e31e0.jpg)

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL59/

**Comment by mnowotka** [comment]
Thanks Laura. This is a step in a good direction. But the action that we want to achive when clicking on the button is a smooth animation of new compounds entering a stage and old ones leaving. This means that when you are on a page N you need to prefetch pages N-1 and N+1.

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL10/

**Comment by mnowotka** [comment]
This is now one of most visually refined bits in the interface. Thanks so much Laura.
