### ISSUE TITLE
Don't show pagination where there is a single page.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#536]
Like here (https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL111/#StructuralAlerts)

![screen shot 2017-12-12 at 16 50 40](https://user-images.githubusercontent.com/837119/33897158-9d943834-df5c-11e7-937e-25596681753d.jpg)

It only takes space.

**Comment by nclopezo** [comment]
**This is done:**
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL111/#StructuralAlerts
