### ISSUE TITLE
some molecules fail to parse using marvin and similarity search

### ISSUE THREAD

**Issue by eloyfelix** [chembl/GLaDOS#541]
Looks like Marvin is using rdkit (maybe beaker?) for molecule exporting to SMILES when doing similarity search.

If molecule can't be sanitized by rdkit is then not possible to run a similarity search on it:

<img width="872" alt="screen shot 2018-01-08 at 12 21 43" src="https://user-images.githubusercontent.com/1122541/34670580-e0be9434-f46e-11e7-8e36-d64fbec708c7.png">

Solution(for most molecules) is to not sanitize them when loading:
Chem.MolFromMolBlock(molfile, sanitize=False)

After opening the molecule with no sanitization is also a good idea to set aromaticity as it's nice to see in the SMILES string which atoms are aliphatic and which ones aromatic.

Chem.SanitizeMol(mol, sanitizeOps=Chem.rdmolops.SanitizeFlags.SANITIZE_SETAROMATICITY)
or
Chem.SetAromaticity(mol)

**Comment by juanfmx2** [comment]
temporarily if you know the CHEMBL ID you can do: http://chembl-glados.herokuapp.com/similarity_search_results/CHEMBL3832892/70

However, the similarity maps don't seem to be working for this molecules

**Comment by mnowotka** [comment]
When the "Similarity" button is clicked the 'ctab2smiles' function from Beaker is called. This function can accept the `sanitize` flag:

curl -X POST -F "file=@non_kekule.mol" -F "kekuleSmiles=0" -F "sanitize=0" http://ves-oy-56.ebi.ac.uk/chembl/api/utils/ctab2smiles

So @juanfmx2 - you can fix this!

![screen shot 2018-02-07 at 16 48 56](https://user-images.githubusercontent.com/837119/35929195-d1f7e49e-0c26-11e8-915b-13b8848355ff.jpg)

**Comment by mnowotka** [comment]
Exactly the same fix can be applied to similarity maps. Similarity maps are not drawn because first the `ctab2smiles` is called. It returns nothing because the compound doesn't pass sanitization so the empty string is given to the subsequent calls which causes errors. If you just set the `sanitize` flag to 0 this should be resolved.
![screen shot 2018-02-07 at 16 53 30](https://user-images.githubusercontent.com/837119/35929457-74bc2294-0c27-11e8-9fec-e5beb3be2880.jpg)

**Comment by juanfmx2** [comment]
An initial fix for this has been deployed:
http://chembl-glados.herokuapp.com/substructure_search_results/CHEMBL3832893
waiting for chembl/chembl_beaker#17

**Comment by mnowotka** [comment]
This guy still doesn't work: http://chembl-glados.herokuapp.com/substructure_search_results/CHEMBL3832893

**Comment by juanfmx2** [comment]
The initial fix for this has been deployed, but we still need to wait for chembl/chembl_beaker#18

**Comment by mnowotka** [comment]
I'm working on this as we speak!

**Comment by mnowotka** [comment]
OK, the corresponding beaker issue is solved and fixed, I checked everything on the interface and it seems to be working fine. Phew, this bug was more comlex than expected!
