### ISSUE TITLE
Redirect when wrong entity is requested by chembl_id

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#543]
If I go to this URL: https://chembl-glados.herokuapp.com/target_report_card/CHEMBL819/
I will get an error message because CHEMBL819 is not a target. But we can check it's a compound so we can show this error but also explain what happened:

"No target found with id CHEMBL819. CHEMBL819 is a compound. Redirecting in 5s..."

**Comment by juanfmx2** [comment]
This is ready now.
http://chembl-glados.herokuapp.com/target_report_card/CHEMBL8546/
http://chembl-glados.herokuapp.com/target_report_card/CHEMBL854594/
http://chembl-glados.herokuapp.com/assay_report_card/CHEMBL25/
http://chembl-glados.herokuapp.com/compound_report_card/CHEMBL612545
http://chembl-glados.herokuapp.com/compound_report_card/CHEMBL3559723/
http://chembl-glados.herokuapp.com/tissue_report_card/CHEMBL3307409/

**Comment by mnowotka** [comment]
Thanks Juan
