### ISSUE TITLE
Improve front page twitter box.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#555]
Currently the twitter box on the front page occupies a lot of space and can only show 2 tweets:
![screen shot 2018-01-26 at 14 29 49](https://user-images.githubusercontent.com/837119/35444124-6a1f0ef4-02a5-11e8-92f2-8814acaa92dd.jpg)
In contrast, ChEBI guys have a twiiter box that is smaller but allows to scroll tweets:
![screen shot 2018-01-26 at 14 31 03](https://user-images.githubusercontent.com/837119/35444176-944d9844-02a5-11e8-8e83-c9e88e89cbb7.jpg)
We need to steal from them :P

**Comment by juanfmx2** [comment]
This is deployed now http://chembl-glados.herokuapp.com/

**Comment by juanfmx2** [comment]
main page is available again!

**Comment by mnowotka** [comment]
Yep, I guess this is now all done, thanks @laurajunco, @nclopezo and @juanfmx2 !
