### ISSUE TITLE
Make a coherent colour palette and apply it to all plots in the new interface

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#556]
We now have many different data-vis components and all of them uses different set of colours. It would be great to work out and apply some unified set of colours.

**Comment by juanfmx2** [comment]
This is deployed now!
http://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/
http://chembl-glados.herokuapp.com/target_report_card/CHEMBL2414/
[Bioactivity Matrix](http://chembl-glados.herokuapp.com/activities/filter/molecule_chembl_id%3A(%22CHEMBL59%22%20OR%20%22CHEMBL1557%22%20OR%20%22CHEMBL457419%22%20OR%20%22CHEMBL138040%22%20OR%20%22CHEMBL250711%22%20OR%20%22CHEMBL138921%22%20OR%20%22CHEMBL456176%22%20OR%20%22CHEMBL456817%22%20OR%20%22CHEMBL141970%22%20OR%20%22CHEMBL1256484%22%20OR%20%22CHEMBL531%22%20OR%20%22CHEMBL160074%22%20OR%20%22CHEMBL512943%22%20OR%20%22CHEMBL301265%22%20OR%20%22CHEMBL350361%22%20OR%20%22CHEMBL348924%22%20OR%20%22CHEMBL1201087%22%20OR%20%22CHEMBL589%22%20OR%20%22CHEMBL347228%22%20OR%20%22CHEMBL1371770%22%20OR%20%22CHEMBL1303%22%20OR%20%22CHEMBL3247442%22%20OR%20%22CHEMBL1009%22%20OR%20%22CHEMBL2105691%22%20OR%20%22CHEMBL300443%22%20OR%20%22CHEMBL2105069%22%20OR%20%22CHEMBL1823681%22%20OR%20%22CHEMBL1200748%22%20OR%20%22CHEMBL718%22%20OR%20%22CHEMBL1328898%22%20OR%20%22CHEMBL2110659%22%20OR%20%22CHEMBL2110793%22%20OR%20%22CHEMBL28278%22%20OR%20%22CHEMBL3545010%22%20OR%20%22CHEMBL3545388%22%20OR%20%22CHEMBL2104864%22%20OR%20%22CHEMBL57241%22%20OR%20%22CHEMBL1743952%22%20OR%20%22CHEMBL1631970%22%20OR%20%22CHEMBL596802%22%20OR%20%22CHEMBL588%22%20OR%20%22CHEMBL2106075%22%20OR%20%22CHEMBL493%22%20OR%20%22CHEMBL2110687%22%20OR%20%22CHEMBL2103827%22%20OR%20%22CHEMBL1201236%22%20OR%20%22CHEMBL459%22%20OR%20%22CHEMBL51910%22%20OR%20%22CHEMBL1743949%22%20OR%20%22CHEMBL1631968%22%20OR%20%22CHEMBL287257%22%20OR%20%22CHEMBL2364614%22%20OR%20%22CHEMBL2106525%22%20OR%20%22CHEMBL273575%22%20OR%20%22CHEMBL69271%22%20OR%20%22CHEMBL2106980%22%20OR%20%22CHEMBL2104184%22%20OR%20%22CHEMBL1256842%22%20OR%20%22CHEMBL2104081%22%20OR%20%22CHEMBL53%22%20OR%20%22CHEMBL2107788%22%20OR%20%22CHEMBL3247441%22%20OR%20%22CHEMBL1188395%22%20OR%20%22CHEMBL536282%22%20OR%20%22CHEMBL1201728%22%20OR%20%22CHEMBL1201066%22%20OR%20%22CHEMBL1172928%22%20OR%20%22CHEMBL3039565%22%20OR%20%22CHEMBL337702%22%20OR%20%22CHEMBL2107365%22%20OR%20%22CHEMBL2106783%22%20OR%20%22CHEMBL1118%22%20OR%20%22CHEMBL637%22%20OR%20%22CHEMBL1615372%22%20OR%20%22CHEMBL1200997%22%20OR%20%22CHEMBL1237021%22%20OR%20%22CHEMBL1712%22%20OR%20%22CHEMBL708%22%20OR%20%22CHEMBL1324%22%20OR%20%22CHEMBL334491%22%20OR%20%22CHEMBL953%22%20OR%20%22CHEMBL2103767%22%20OR%20%22CHEMBL2106351%22%20OR%20%22CHEMBL493682%22%20OR%20%22CHEMBL1275%22%20OR%20%22CHEMBL1026%22%20OR%20%22CHEMBL2107261%22%20OR%20%22CHEMBL2105459%22%20OR%20%22CHEMBL2105358%22%20OR%20%22CHEMBL53929%22%20OR%20%22CHEMBL2218888%22%20OR%20%22CHEMBL509336%22%20OR%20%22CHEMBL307739%22%20OR%20%22CHEMBL2106804%22%20OR%20%22CHEMBL2104671%22%20OR%20%22CHEMBL86882%22%20OR%20%22CHEMBL660%22%20OR%20%22CHEMBL396778%22%20OR%20%22CHEMBL887%22%20OR%20%22CHEMBL1201212%22%20OR%20%22CHEMBL972%22%20OR%20%22CHEMBL2107608%22%20OR%20%22CHEMBL1437%22%20OR%20%22CHEMBL524%22%20OR%20%22CHEMBL1201319%22%20OR%20%22CHEMBL1160714%22%20OR%20%22CHEMBL1201251%22%20OR%20%22CHEMBL2105040%22%20OR%20%22CHEMBL2104207%22%20OR%20%22CHEMBL2105064%22%20OR%20%22CHEMBL1201234%22%20OR%20%22CHEMBL926%22%20OR%20%22CHEMBL358040%22%20OR%20%22CHEMBL77622%22%20OR%20%22CHEMBL33720%22%20OR%20%22CHEMBL434%22%20OR%20%22CHEMBL211456%22%20OR%20%22CHEMBL1215%22%20OR%20%22CHEMBL679%22)/#matrix_fs/Compounds)

**Comment by mnowotka** [comment]
There are a few of other plots:

- Metabolism Graph (look at arrow colors):
   ![screen shot 2018-02-02 at 11 22 53](https://user-images.githubusercontent.com/837119/35730826-725f47a8-080b-11e8-94e1-fe6f8c178fe2.jpg)
- Target Associated Compound Properties (The histogram should probably have only one color and it looks teal but can you confirm this teal is exactly the teal from the color palette?)
   ![screen shot 2018-02-02 at 11 25 18](https://user-images.githubusercontent.com/837119/35730920-c60396de-080b-11e8-893c-d523a16d3c10.jpg)
- Word cloud (ideally color should change accoring to the score so the size of the word)
   ![screen shot 2018-02-02 at 11 27 38](https://user-images.githubusercontent.com/837119/35731048-2b5889a4-080c-11e8-82db-ad9cf5ee9b84.jpg)
- In table histograms (somehow the colors here don't play nicely, for examle black)
   ![screen shot 2018-02-02 at 11 28 42](https://user-images.githubusercontent.com/837119/35731124-5f3e26a2-080c-11e8-9a79-6a59f97378d1.jpg)
- There is also a "target hierarchy" plot on the main webpage (in one of the tabs) but I can't check it as the front page now returns error 500.

**Comment by juanfmx2** [comment]
The main page is available again:
This is the plot @mnowotka refers to:
(it is located under the tab Browse Targets)
![screen shot 2018-02-02 at 12 40 56](https://user-images.githubusercontent.com/6558395/35733764-8977dad0-0816-11e8-8f84-8b2abacb9151.png)

**Comment by mnowotka** [comment]
Yep, I just realised that there are more things broken in this widget so I guess it will be better to move it to the separate issue.

**Comment by juanfmx2** [comment]
@mnowotka what about "Database Schema" and "Web Services Diagram" should they use the same palette?

**Comment by laurajunco** [comment]
I changed the colour palette for those graphs:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/
https://chembl-glados.herokuapp.com/document_report_card/CHEMBL1151719/
https://chembl-glados.herokuapp.com/

**Comment by mnowotka** [comment]
Thanks, Laura!
