### ISSUE TITLE
Add margin for a message about loading filters

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#557]
This is what the user sees when it takes some time to load filters:

![screen shot 2018-01-26 at 14 34 18](https://user-images.githubusercontent.com/837119/35444437-7859d39a-02a6-11e8-96cc-7df69a3f8d00.jpg)

The "Loading filters..." message touches the left border. Can we please center it?

**Comment by laurajunco** [comment]
https://chembl-glados.herokuapp.com/search_results/Dopamine

**Comment by mnowotka** [comment]
Thanks Laura!
