### ISSUE TITLE
Disable hotjar on embeded widgets

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#565]
We don't need hotjar everywhere. In particular we don't need the "smiley face" little thingy when we know the page (or a part of it) has been embeded. This is a code to detect if a page is inside an iframe: https://stackoverflow.com/questions/326069/how-to-identify-if-a-webpage-is-being-loaded-inside-an-iframe-or-directly-into-t, it may be helpful.

**Comment by juanfmx2** [comment]
This is ready and deployed! https://target-attention.herokuapp.com/

**Comment by mnowotka** [comment]
That was fast, thanks Juan!
