### ISSUE TITLE
alternate forms view shows erros for compounds without structure

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#584]
When a compound doesn't have an image alternate forms will not have an image as well so in that case we also need to present praceholders for them. Now we are getting errors:

![screen shot 2018-02-07 at 16 17 35](https://user-images.githubusercontent.com/837119/35930632-5caadee0-0c2a-11e8-8604-8cb5ea44e480.jpg)

**Comment by nclopezo** [comment]
This has been fixed:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1370561/
