### ISSUE TITLE
DOCUMENTS BY YEAR

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#605]
Please can we remove this from the home page of the new interface.  It highlights the fact that we have no data in ChEMBL from the literature since 2016 and also not even all the 2016 papers.  When we release ChEMBL24 we will only have 300 documents from 2017.  Also can we remove the date on the ChEMBL23 release?  I don't think we want stress this.

We can discuss what should go on the home page for now but maybe some text about ChEMBL?

**Comment by mnowotka** [comment]
Since we discussed all the details and agreed on the carousel view I'm closing this one.
