### ISSUE TITLE
Known drugs records go to half widget width

### ISSUE THREAD

**Issue by Cradoux** [chembl/GLaDOS#616]
Only happens when it is displaying the reduced information version, and when the number of records results in multiple pages, as shown

![screen shot 2018-02-22 at 15 20 01](https://user-images.githubusercontent.com/33261184/36546662-e51bba50-17e3-11e8-816e-1e9c4cc1756f.png)

**Comment by laurajunco** [comment]
@Cradoux could you please paste the url where you can see this bug?

**Comment by Cradoux** [comment]
Here's the link: https://target-attention.herokuapp.com

If you scroll down to the "Ongoing projects" section, then click on one of the lines in the plot, it should update the widget to the known drugs. You may need to try a few to get one with multiple pages

**Comment by laurajunco** [comment]
This should be fixed now: 
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL3/
https://target-attention.herokuapp.com/

@Cradoux can you please check if its fixed?

**Comment by Cradoux** [comment]
Works perfectly!
