### ISSUE TITLE
Bioactivities widget missing pie chart

### ISSUE THREAD

**Issue by Cradoux** [chembl/GLaDOS#618]
Can be seen upon initial page load here: https://target-attention.herokuapp.com

<img width="523" alt="screen shot 2018-02-22 at 15 47 16" src="https://user-images.githubusercontent.com/33261184/36548282-c7b21ad2-17e7-11e8-8ece-1f4b84412a49.png">

**Comment by mnowotka** [comment]
Hi Chris!
It works for me :P Can you provides steps to reproduce it? Maybe this dosn't work on a specific device (mobile)? Give us some more details.
![screen shot 2018-02-23 at 11 40 16](https://user-images.githubusercontent.com/837119/36592615-6680563c-188e-11e8-8bc6-27a167d8d7f4.jpg)

**Comment by nclopezo** [comment]
I know when it happens, it happens when the width becomes too small. It depends on the screen you are using.

**Comment by mnowotka** [comment]
OK, so if we know this, can we don something to prevent it from happening?

**Comment by Cradoux** [comment]
It only happens when the page first loads (and with a narrow window). 

However when I select another target (by clicking on one of the lines in the plot, you have to filter to only display "Discovery" compounds to get the bioactivities), the plot updates correctly, despite still being the same size

**Comment by nclopezo** [comment]
Everything is possible.

**Comment by mnowotka** [comment]
So just do it!

**Comment by mnowotka** [comment]
I'll assign you so you won't forget :P

**Comment by laurajunco** [comment]
This is deployed now: 
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL10/
https://target-attention.herokuapp.com/

**Comment by nclopezo** [comment]
Hi @Cradoux,
Could you confirm that this is fixed?

**Comment by Cradoux** [comment]
Yep, this seems fixed, thanks
