### ISSUE TITLE
Remove items from left-hand menu

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#626]
Many of menu items on the front page are no longer active and should be removed.
@anne123, @agaulton can you please provide a list of items that should be removed?
![screen shot 2018-02-23 at 20 45 33](https://user-images.githubusercontent.com/837119/36616125-85720792-18da-11e8-9ae4-4649ea9e458d.jpg)

**Comment by anne123** [comment]
Hi Michal, Laura
I think the list you have left here is fine. Thanks

**Comment by laurajunco** [comment]
I also updated a few layout and style elements of the side bar https://chembl-glados.herokuapp.com/

**Comment by mnowotka** [comment]
Thanks Laura. Bofore I close that one I would like to to fix some other cosmetic things we discussed:

- [ ] Removing top padding above the fisr menu item.
- [ ] Removing space above the Download button
- [ ] Removing the 'Advenced' button from the searchbar

**Comment by mnowotka** [comment]
This is now all finished, thanks Laura!
