### ISSUE TITLE
Top search bar should not be split into two parts.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#627]
Currently the top search bar consists of two parts: smaller one above left-hand menu and larger one above main website content. This should be merged into a single top bar.

![screen shot 2018-02-23 at 20 48 21](https://user-images.githubusercontent.com/837119/36616289-22318c9c-18db-11e8-9bb6-84ace91bccc3.jpg)

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/
![screen shot 2018-02-26 at 09 16 42](https://user-images.githubusercontent.com/17466890/36662294-d20793fe-1ad5-11e8-8b3e-ecf3fe1032d0.png)

**Comment by mnowotka** [comment]
Thanks Laura!
