### ISSUE TITLE
checkboxes from mini cards obscure the top bar

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#637]
Like in that screenshot:

![screen shot 2018-02-27 at 13 00 45](https://user-images.githubusercontent.com/837119/36730148-489b914e-1bbe-11e8-9082-c5ab2bfa0e55.jpg)
Taken from: https://chembl-glados.herokuapp.com/search_results/Dopamine

**Comment by laurajunco** [comment]
This is now deployed: http://localhost:8000/search_results/Dopamine

**Comment by mnowotka** [comment]
Thanks Laura!
