### ISSUE TITLE
Display Bioactivity data from Assays table

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#643]
I'm sure this is also captured somewhere else but the example is search for an assay description (I did immune response) this displays a list of 213 assay and you can select ones of interest but there needs to be the bioactivity icon (as on the compound page) to display all the bioactivity data on the assays of interest.

probably we need this for the release.

**Comment by mnowotka** [comment]
Yes, it's captured here: https://github.com/chembl/GLaDOS/issues/513 already planned for the public beta.
