### ISSUE TITLE
Logic for what is displayed on compound report cards

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#647]
I have been through all the sections and produced this summary of how I think they should work.  Also added a few comments from Patricia.  Please ask if anything isn't clear.

Compound report cards should work on the principal that all the data on the salts and parent is aggregated on the parent report card while the salt report cards show just the data on that specific salt.  The exceptions are everything is shown on all parents and all salts for parent compound properties, metabolism, target predictions and structural alerts regardless of whether they are drugs, clinical candidates etc

Some Specifics:
Name And Classification

- [x] Names associated with their salt forms on the new interface e.g. Viagra is only on citrate is this what we want?  On old interface synonyms are aggregated on the parent

Representations

- [x] I think this is fine - representation on the specific form

Sources

- [x] Not working This should work as in old interface i.e the sources are aggregated on the parent but then specific for the salt forms. 

- [x] Also can these sources be ordered alphabetically?

Alternate Forms

- [x] Ability to switch between report cards is working fine
Juan was interested in a different name for this but there isn’t anything obvious as it encompasses isotopes as well as parents so I would leave it as it is for now

- [x] Can the molecules be shown a bit smaller so that more than 3 can be seen at once?

Similar Compounds
I have a number of questions about this as the compounds and similarities returned are entirely different from doing a similarity search on the same compound using the BioVia similarity search.  I see a potential for a lot of confusion here amongst the users.

- [x] Also if we keep this - can we move this lower down the page as looking at the drug info and then wanting to go back to the parent and salt we kept selecting the wrong thing one of the similar compounds

- [x] Also remove the exact match - not sure how this works though for enantiomers/racemates

- [x] A logical thing to do with the similar compounds is to select them all and to be able to see the bioactivity data.  Can this be implemented?

- [x] I would set the threshold much higher e.g. 80 or preferably 85%.

Molecule Features

- [x] If any salt form is drug or USAN the parent needs to show the icons.  If there is a difference for a salt i.e. it is just a USAN this should be shown
As an example Histamine. CHEMBL90 is the parent and shown with icons. CHEMBL535166 is not a drug so shows no icons.  The dihydrochloride CHEMBL1533310 is a USAN so should be shown with a different set of icons related to that form.  This is not working correctly in the new interface. Use the old interface as an example of correct working.

Mechanism of Action

- [x] This should be aggregated on the parent but then shown for salts that are drugs.  e..g OCTREOTIDE (CHEMBL1680) parent and acetate salt shows MoA the other two salts don't

Indications

- [x] These should be aggregated across all salt forms on the parent but on the salt forms the individual indications should be shown.  i.e. should work as on the old interface

Clinical Data

- [x] Links to clinical trials etc - I’m not sure how this is working but it is different on new and old interfaces e.g sildenafil. More trials in new interface than the old for sildenafil and sildenafil citrate for example.  Need to confirm which is behaviour we want.

- [x] Patricia comment: [In my view, the links should work as in the old interface, i.e. the drug synonyms should match an intervention in clinical trials. I would avoid links to trials where the intervention is for another drug but the synonym of interest appears somewhere else in the text of that trial.
See for example the case of COMPACTIN (I think this is a synonym for Mevastatin):
- using the general search (http://clinicaltrials.gov/ct2/results?term=search term)  we get two trials (none for the drug of interest). 
- using the more specific search (http://clinicaltrials.gov/search?intr=search_term) we get 0 trials (which I think is the correct result)]

CHEMBL192 in Literature

- [x] Why does this give the CHEMBL ID in the right hand menu - would it be better to just say literature.  I am not sure why these plots are limited to literature and don’t include the other data sets in ChEMBL.  Can this be changed and called documents in ChEMBL.  It might be necessary to ad a bar with no date.

Activity Charts

- [x] This is not working.  Data should all be aggregated on the parent page and then just for the individual salts on the salt pages.  i.e. as it works on the old interface

Metabolism

- [x] This should appear on all the parent and salt pages for the compound.  Not working correctly on old or new interface (probably needs more discussion).

- Patricia comment [At the moment, the metabolism information is shown for the salts, and respective parents, of the drug recorded in the metabolism table in the database. In order to propagate the metabolism data across other salts that are neither drugs or are not in the metabolism table, we should discuss if this should  just be an interface feature or should we also change the data in the database.]
**(This should be converted in a new issue if necessary after discussion)**

Target Predictions

- [x] These are calculated on the parents but should appear on all the parent and salt compound report cards

Calculated Parent Properties

- [x] These should be the properties of the parent. Currently Mwt is for the salt on sildenafil citrate.  They are described as calculated parent properties which is correct.  The full Mwt can be reported on the salt but needs to be described appropriately

Structural Alerts

- [x] This appears as on the old interface so is correct.  On the individual salt forms

Cross References

- [x] These are on individual forms and as in the old interface.  I assume this is what we want as probably anything else is more difficult to do.

UniChem Cross References

- [x] No option to do connectivity matches.  This should be implemented as in the old interface

**Comment by mnowotka** [comment]
I'm removing a "bug" label because this is not a bug but some non-trivial convept to implement.

**Comment by mnowotka** [comment]
Removing the exact match from similarity results is already planned here: #614.

**Comment by mnowotka** [comment]
Smilarity threshold is described here: #658.

**Comment by mnowotka** [comment]
Just added some tickboxes to convert one big issus into a list of smaller. Completed issues are checked.

**Comment by mnowotka** [comment]
Regarding: "Can the molecules be shown a bit smaller so that more than 3 can be seen at once?". Mini-report cards can be scaled using +/- buttons on the left, is that fine?

**Comment by anne123** [comment]
Additional comment - Names and synonyms.  We can discuss but Anna had the suggestion that we aggregate on the parent but split the synonyms into parent and salt sections

**Comment by mnowotka** [comment]
Yes, the issue about synonyms and trade names is #107.

**Comment by nclopezo** [comment]
I will upload this so we can continue spilling tea on it:
![img_20180328_104133](https://user-images.githubusercontent.com/1944922/38021615-3ea590c2-3275-11e8-9cfa-92d4bdaf4bbd.jpg)

Also, as a reminder for me, the following can already be done without waiting for the update in the index:
- Showing metabolism section correctly.
- Calculated Properties.
- Highlight in alternative forms the parent and the current compound. 
- Unichem conectivity matches.

**Comment by agaulton** [comment]
Just to confirm, for Clinical Data section:
On parent page, link to clinical trials.gov with all syns/trade names for parent and all children
On child page, link to clinical trials.gov with just syns/trade names for that molecule form

In both cases, we should use URL of this form to restrict to just interventions field:
https://clinicaltrials.gov/ct2/results?intr=Sildenafil%20OR%20UK-92480

**Comment by nclopezo** [comment]
The clinical data link is now being created as requested: 
- https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL192/
- https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1737/

**Comment by juanfmx2** [comment]
@nclopezo it is possible now to get the mechanism of actions using the following filter:
http://wwwdev.ebi.ac.uk/chembl/glados-es/chembl_mechanism/_search?q=_metadata.all_molecule_chembl_ids:CHEMBL3707332
before rendering the table you only need to check, if is approved drug is true.

As well you can filter the drug indications:

http://wwwdev.ebi.ac.uk/chembl/glados-es/chembl_drug_indication/_search?q=_metadata.all_molecule_chembl_ids:CHEMBL1201536

http://wwwdev.ebi.ac.uk/chembl/glados-es/chembl_drug_indication/_search?q=_metadata.all_molecule_chembl_ids:CHEMBL3

Also Target Predictions is ready now.

**Comment by agaulton** [comment]
Aggregating drug indications on parent - here is an example:

CHEMBL2 (Prazosin) + CHEMBL1558 (Prazosin Hydrochloride) both have the indication ‘Hypertension’ (D006973) but the highest phase is different (4 for parent and 1 for salt). Therefore I think if we’re going to aggregate these on the parent page, we should probably:

a) show a distinct list (e.g., only show salt indications if different from parent)
b) take the highest phase overall and include the references from both (appreciate this might be a bit complicated though)

It's a good idea to show whether the info came from parent or salt though (where both, I'd just say parent)

**Comment by agaulton** [comment]
Some examples for mechanism of action:
1) CHEMBL190 (parent) and CHEMBL1200434 + CHEMBL1370561 (salts) - each have same three mechanisms
2) CHEMBL612 (parent) and CHEMBL1200782, CHEMBL3544971 + CHEMBL3989844 (salts) - each have same three mechanisms
3) CHEMBL1169 (parent) and CHEMBL1200584 + CHEMBL2096646 (salts) - two salts have same mech, parent is different

I didn't find any cases where the references are different yet. Largest number of parent/salt forms with mechanisms is 4 (like in 2 above). Largest number of distinct mechanisms for a compound is 13 (CHEMBL1946170). Hope that helps

**Comment by nclopezo** [comment]
Ok thanks. I will implement a table which merges the same mechanisms in one row.

**Comment by nclopezo** [comment]
The drug indications are ready:

- Parent: https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL190/
- Salts with the same 3 mechanisms: 
  - https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1370561/
  - https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1200434/
-Salts with no mechanisms:
  - https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL2107084/
  - https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1355736/

**Comment by nclopezo** [comment]
This is ready!!!
