### ISSUE TITLE
Similarity search result page is now completely broken

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#653]
Just look at this disaster: https://chembl-glados.herokuapp.com/similarity_search_results/CHEMBL25/70, we definitely need tests for that!
![screen shot 2018-03-03 at 19 00 45](https://user-images.githubusercontent.com/837119/36938134-3b738062-1f15-11e8-9ab3-362f459e1238.jpg)

**Comment by nclopezo** [comment]
- The url has changed: 
https://chembl-glados.herokuapp.com/g/#similarity_search_results/CHEMBL25/70
- There is a ghost inspector test already which is indeed failing.
- I decided to push some changes even if they were incomplete, so solve and prevent some conflicts with the work of @laurajunco

**Comment by mnowotka** [comment]
Thanks David, I'll wait for a confirmation from you that this is fully fixed.

**Comment by nclopezo** [comment]
So as I said before the page is working:
https://chembl-glados.herokuapp.com/g/#similarity_search_results/CHEMBL25/70

 I just updated the ghost inspector test: 
https://app.ghostinspector.com/tests/59ee0bfa639a7d76ba1e5deb 
which is passing now

**Comment by mnowotka** [comment]
Perfect, thanks a lot David!
