### ISSUE TITLE
Filters are all collapsed on initial load in the results page.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#655]
For example: https://chembl-glados.herokuapp.com/g/#search_results/Dopamine

What we have now:
![screen shot 2018-03-05 at 10 50 40](https://user-images.githubusercontent.com/837119/36971247-1b00e12c-2063-11e8-9e7c-a66a7739a9cc.jpg)

What we want to have:
![screen shot 2018-03-05 at 10 51 26](https://user-images.githubusercontent.com/837119/36971279-31291adc-2063-11e8-9eaa-2fff06dc6eac.jpg)

**Comment by nclopezo** [comment]
**This has been fixed:**
https://chembl-glados.herokuapp.com/g/#search_results/Dopamine
https://chembl-glados.herokuapp.com/g/#browse/compounds

**Comment by mnowotka** [comment]
Great, thanks!
