### ISSUE TITLE
Result page loads slowly

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#656]
The result page is very complex. Results are grouped into separate entities: compounds, targets, documents, etc and each group have multiple ways of visualisation (cards, table, scatter plot etc). This requires many HTTP requests to be fired and lots of DOM elements to render.

On the other hand, at the begining, all the user wants to see it the most relevant group in default view and filters. We have to make sure that this leads/renders first.

**Comment by nclopezo** [comment]
The search speed was improved significantly by https://github.com/chembl/GLaDOS/pull/848

**Comment by nclopezo** [comment]
The bug caused by https://github.com/chembl/GLaDOS/pull/861 has been fixed. Also, now the search results page only loads the sections when they are opened, or scrolled to.

**Comment by nclopezo** [comment]
This means that the search page now loads faster.
