### ISSUE TITLE
Similarity search edit, bad display

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#674]
After I do a similarity search, if I want to edit the query I cannot see the bottom of the Marvin JS window 
![image](https://user-images.githubusercontent.com/26281131/37276953-34a9d1d8-25db-11e8-8b8d-60bf5e21838c.png)

Actually, there is a trick! You can zoom out!
![image](https://user-images.githubusercontent.com/26281131/37277005-5a464cbe-25db-11e8-9da1-7fa05372ce7f.png)

**Comment by mnowotka** [comment]
This should work without tricks ;)

**Comment by juanfmx2** [comment]
An easy way to replicate this is with a query with no results:
http://chembl-glados.herokuapp.com/g/#substructure_search_results/C1%3DCC2%3DC3C(%3DC1)CCC1CCCC(C4CCCCC24)C31

**Comment by mnowotka** [comment]
I see! Looks like a task for @laurajunco :P

**Comment by laurajunco** [comment]
This is fixed now! http://chembl-glados.herokuapp.com/g/#substructure_search_results/C1%3DCC2%3DC3C(%3DC1)CCC1CCCC(C4CCCCC24)C31
