### ISSUE TITLE
DOIs (redirect old urls to new interface)

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#678]
Just recording this so we don't forget.  When we retire the old interface we need to make sure the DOIs all point to the new interface.  I am assuming the doc report card URLs will need to change? If yes when do we start assigning new DOIs to the new URLs?

**Comment by mnowotka** [comment]
All URLs for any report cards and front page should be exactly as they are in the old interface. It's important that we keep all the important URL stable.

**Comment by anne123** [comment]
Excellent - thanks Michal.  One less thing to do :)

**Comment by nclopezo** [comment]
From what I just discussed with Michal, we could do the following:
- Place a link on top of the pages in the old interface saying something like "Click here to see this page in our new interface"
- When the old interface is completely replaced by the new one, we can make the old urls to redirect to the new urls.

**Comment by anne123** [comment]
I'm confused - does this mean the URLs of the report cards will need to change?

I can see while we have two interface versions it is a problem and redirecting will work so long as we never forget and remove the redirect.  It would be good to understand what the release URL structure will be so we can think about structuring new DOIs appropriately.  Will the release/download locations also change as we have URLs for these too?

**Comment by mnowotka** [comment]
All URLs will stay intact. This is important not to break any URLs that may be already spread over web.

**Comment by nclopezo** [comment]
As we had agreed earlier, the old interface will have links to the new one. I renamed this issue and moved it to a new milestone to remember this.

**Comment by nclopezo** [comment]
@anne123 The interface will support old report card urls (see https://github.com/chembl/GLaDOS/pull/1049#issuecomment-471954867), the 'beta' will disappear after the switch. 
The release downloads are only in the ftp and these urls won't be affected. For example the DOI http://doi.org/10.6019/CHEMBL.database.24.1 will not change, and none of future DOIs due to the swap.

**Comment by nclopezo** [comment]
Are there any other important urls that we need to take into account?

**Comment by nclopezo** [comment]
The switch has been done and this has been addressed.
