### ISSUE TITLE
Similarity Search results show the similarity incorrectly

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#682]
I noticed that at some point we broke the similarity field:
http://chembl-glados.herokuapp.com/g/#similarity_search_results/CHEMBL59/70

<img width="1020" alt="screen shot 2018-03-13 at 15 47 10" src="https://user-images.githubusercontent.com/1944922/37352749-dc76df64-26d5-11e8-8982-dcc13f7c8a98.png">

How can CHEMBL59 be less than 100% similar to itself?
<img width="489" alt="screen shot 2018-03-13 at 15 48 08" src="https://user-images.githubusercontent.com/1944922/37352802-f7c66e88-26d5-11e8-89c4-21a7f25d08c3.png">

Why are the similarities of the last items less than 70%?

The problem is when jumping from Web Services to Elasticsearch, I am fixing this right now.

**Comment by nclopezo** [comment]
**This has been fixed:**
http://chembl-glados.herokuapp.com/g/#similarity_search_results/CHEMBL59/70
I added some steps to the ghost inspector test:
https://app.ghostinspector.com/tests/59ee0bfa639a7d76ba1e5deb
I checked manually with:
https://www.ebi.ac.uk/chembl/api/data/similarity/CHEMBL59/70.json?only=molecule_chembl_id,similarity

**Comment by mnowotka** [comment]
:D
