### ISSUE TITLE
Title  and text stating 'Alternate Forms' in compound report card for compound families should be amended to 'Alternative Forms'

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#687]
'Alternate Forms' is American English and should be corrected in the title and text to use the adjective 'Alternative', ie correct English. The existing ChEMBL website is also incorrect!

Screen shot below:
![screen shot 2018-03-14 at 15 55 09](https://user-images.githubusercontent.com/32895834/37414009-1eecb934-27a0-11e8-87e4-3fa8caffba14.png)

**Comment by laurajunco** [comment]
This is now deployed: https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL11/

**Comment by FionaEBI** [comment]
A couple of minor wording issues: 
1. Please can you order the list on the right hand side of the Compound Report page so that the 'Alternative Forms' is in the same order as the sections in the Compound Report. Currently, the 'Alternative Forms is at the bottom of the list on the right hand side, but feature in the middle section of the compound report card. See http://wwwdev.ebi.ac.uk/chembl/compound_report_card/CHEMBL25/
![Screenshot 2019-10-30 at 15 37 40](https://user-images.githubusercontent.com/32895834/67873338-3998ee00-fb2b-11e9-8894-4c83428b1ccb.png)
2. The wording in the Activity Charts section of the compound report page should be updated to use the term 'Alternative Forms' instead of 'Alternate Forms'. This occurs twice on each plot - in the green 'Exclude Alternate Forms Data' and the title of the pie chart ' ...(including alternate forms). See 
![Screenshot 2019-10-30 at 15 38 19](https://user-images.githubusercontent.com/32895834/67873639-a8764700-fb2b-11e9-99af-ef894fa69d54.png)

**Comment by Emma-Manners** [comment]
Thanks. Now resolved.
