### ISSUE TITLE
molecule features hover 

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#690]
When a compound as a molecule features section, to know the meaning of a rectangle you need to hover over it.

The is issue is you have to hover specifically over the little symbol when it represents only a small area in the whole rectangle.

**Comment by nclopezo** [comment]
Could you please add a screenshot?

**Comment by nbosc** [comment]
I tried but you don’t see the cursor on the screenshot. I showed to @laurajunco

**Comment by laurajunco** [comment]
This is deployed: https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/

@nbosc can you check that it works alright?
