### ISSUE TITLE
Breadcrumbs share icon is not user friendly

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#699]
We have a breadcrums working now, for example here: https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL121/, they look like this:

![screen shot 2018-03-15 at 14 41 20](https://user-images.githubusercontent.com/837119/37470222-f3870ec4-285e-11e8-990b-45b5bd81115a.jpg)

When you click on the last part (share icon), you will see a dialog with URL:

![screen shot 2018-03-15 at 14 42 06](https://user-images.githubusercontent.com/837119/37470255-0d7ef1b6-285f-11e8-9bcf-f258d5c33161.jpg)

Which you can now copy and share.

This is too much action. Ideally all I do is I just click in the icon and it's immediately copied to my clipboard, similarily to the way how clone URL work in GitHub for example.

**Comment by juanfmx2** [comment]
Not only that, this should be compatible with the mobile devices share functionality:

https://stackoverflow.com/questions/15921262/is-it-possible-to-trigger-share-menu-on-smartphones-via-html-js

**Comment by nclopezo** [comment]
It now uses the same component used to how the inchis and smiles. which allows copying easily:

https://www.ebi.ac.uk/chembl/beta/g/tiny/+C2MrLOcfO9c9ltaDWRcMg==
