### ISSUE TITLE
Add 'Helm Notation' and 'Biological Sequence' sections 

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#7]
I noticed that these 2 sections are missing from the compound report card. They appear when a compound is a peptide/antibody:

https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL1201585
http://glados-ebitest.rhcloud.com/compound_report_card/CHEMBL1201585/

**Comment by nclopezo** [comment]
**This is ready:**

The sections are only shown when there is data available:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL1201585

When there is no data the sections are hidden:
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/

**Comment by mnowotka** [comment]
Thanks @nclopezo.
