### ISSUE TITLE
Use elastic search refresh='wait_for' in hash saver

### ISSUE THREAD

**Issue by juanfmx2** [chembl/GLaDOS#700]
In the python elastic search library it is possible to specify the option:

**refresh** – If true then refresh the affected shards to make this operation visible to search, if wait_for then wait for a refresh to make this operation visible to search, if false (the default) then do nothing with refreshes., valid choices are: ‘true’, ‘false’, ‘wait_for’

Where wait for will only return back after the change is ready for search.

**Comment by nclopezo** [comment]
Done in:
https://github.com/chembl/GLaDOS/blob/a29b525885a5231710a644289b3c180174785116/src/glados/models.py#L101
