### ISSUE TITLE
Beta icon is not present everywhere or in the same way.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#702]
When the interface is released it has to be indicated that this is a beta stage.

Right now, when you visit a front page, there is nothing to indicate this:

<img width="1440" alt="screen shot 2018-03-18 at 15 47 59" src="https://user-images.githubusercontent.com/837119/37567797-c5ddec9c-2ac3-11e8-9af9-51e82c36ea9c.png">

When you start scrolling, the beta icons shows up:
<img width="1440" alt="screen shot 2018-03-18 at 15 48 42" src="https://user-images.githubusercontent.com/837119/37567803-dcb3c676-2ac3-11e8-8223-1c1d671745ce.png">

On other pages (results, report cards) there is still no beta sign without scrolling and on scroll it there is no icon be 'beta' description:

<img width="1439" alt="screen shot 2018-03-18 at 15 50 32" src="https://user-images.githubusercontent.com/837119/37567824-1e1cafa6-2ac4-11e8-9b72-c6a8b979894f.png">

I think the "beta" icon should be there always next to the "ChEMBL" logo and description on every page and regardless if you scroll or don't.

**Comment by laurajunco** [comment]
This is deployed now https://chembl-glados.herokuapp.com/
