### ISSUE TITLE
Deploy GLaDOS UI to EBI boxes.

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#703]
GLaDOS infrastructure consists of a few parts:

- [x]  REST API (This is properly deployed and available at https://www.ebi.ac.uk/chembl/api)
- [x]  Elastic engine (I trust this is deployed and availalble at https://www.ebi.ac.uk/chembl/glados-es but I leave this box for Juan to check). And make sure that the interface can consume it correctly. 
- [x] Continuous Integration: set up a jenkins server to handle the scripts that will deploy the interface. 
- [x] UI - this is currently deployed on heroku (chembl-glados.herokuapp.com) and uses a single VM that Juan/David got free of charge.

If GLaDOS is going to be released as beta, we need to make sure that all 3 tick boxes above are checked. Obviously the biggest problem is with UI, which (just as other services) should be deployed on at least 4 boxes (two pairs, each part on different data center or at least two defferent physical hosts). There are currently 3 options to deploy UI:

1. OpenShift - something that the TSC team and Conor are currently working on se we can get involved in a pilot project but there is a risk of coming across some obstacle that will slow down the whole process as EBI is not offically using OpenShift yet.
2. Embassy Cloud - similar to the way we have released SureCheMBL we can do it using OpenStack via EmbassyCloud. This means requesting another cloud tenancy.
3. Web production provided boxes - the most traditional way, the most predictible one but also having some well known problems.

**Comment by nclopezo** [comment]
The web interface is now available here https://www.ebi.ac.uk/chembl/beta/ and its deployment process has been automated. 
We are just missing the configuration of the fallback elasticsearch servers by @juanfmx2

**Comment by nclopezo** [comment]
this is complete!
