### ISSUE TITLE
Link from compound report card to target goes to old ChEMBL website, not to beta ChEMBL website

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#704]
On the Dexamethasone Compound Report Card, the double clicking on the link for the target (CHEMBL2034) under 'Mechanism of Action' goes to the old ChEMBL interface, not the beta ChEMBL interface.
See pic
![screen shot 2018-03-19 at 11 06 21](https://user-images.githubusercontent.com/32895834/37592274-19cf40ba-2b66-11e8-8fbe-d7c193734824.png)

**Comment by nclopezo** [comment]
@FionaEBI 
Hi Fiona:

This has been fixed: 
http://chembl-glados.herokuapp.com/compound_report_card/CHEMBL131/#MechanismOfAction
