### ISSUE TITLE
Add Carousel of Visualisations to Main Page

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#707]
We agreed to add this but this was not described. We agreed to create a carousel with the current visualisations that we have in the main page. 

![img_20180319_155550](https://user-images.githubusercontent.com/1944922/37607148-26c50358-2b8f-11e8-8ffa-9cb08b7bc6a1.jpg)

**Comment by laurajunco** [comment]
#707

**Comment by laurajunco** [comment]
This is deployed now: https://chembl-glados.herokuapp.com/

**Comment by nclopezo** [comment]
Thank you!
