### ISSUE TITLE
Incorrect citation of document from assay report card

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#715]
The Journal Article is incorrectly cited from the assay report card. See screenshots of new (called 'Journal') and old (called 'reference') web interface. The old web interface leads to the correct journal article. 

![screen shot 2018-03-21 at 16 05 26](https://user-images.githubusercontent.com/32895834/37721542-b9aa8416-2d21-11e8-874a-0f4da2147b33.png)

![screen shot 2018-03-21 at 16 05 14](https://user-images.githubusercontent.com/32895834/37721541-b982dbaa-2d21-11e8-86d7-c14eabdd6da7.png)

**Comment by nclopezo** [comment]
It seems that for some reason this was not added to the index and I forgot to request it. We need to add that field to the elasticsearch index first: https://github.com/chembl/GLaDOS-es/issues/22

**Comment by nclopezo** [comment]
This is fixed:
http://chembl-glados.herokuapp.com/assay_report_card/CHEMBL878858/
