### ISSUE TITLE
Show/hide filters section is not working

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#717]
When selecting filters the page becomes opaque and you cannot select or unselect a filter.

![image](https://user-images.githubusercontent.com/26281131/37826792-cd38dec6-2e8c-11e8-9c76-986d0ecf824e.png)

**Comment by laurajunco** [comment]
For the record the url is: https://chembl-glados.herokuapp.com/g/#browse/targets

**Comment by laurajunco** [comment]
This is fixed now: https://chembl-glados.herokuapp.com/g/#browse/targets

**Comment by nclopezo** [comment]
@nbosc, can you confirm that this is fixed?

**Comment by nclopezo** [comment]
I will assume that your reaction is a confirmation, I hadn't seen it before.

**Comment by nbosc** [comment]
I thought you would understand the thumb up on Laura’s post :)
