### ISSUE TITLE
click on some links of 'want to know more' open a page with a persistent loading screen

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#757]
Click on FAQS, Database schema or Fundings here:
![image](https://user-images.githubusercontent.com/26281131/39299394-8672a822-4940-11e8-85fb-e089bc94e4d8.png)

Get one of these for ever:
![image](https://user-images.githubusercontent.com/26281131/39299434-98fc114a-4940-11e8-86f1-3f1c7a42c6a3.png)

**Comment by laurajunco** [comment]
Thanks for noticing @nbosc I will fix this!

**Comment by laurajunco** [comment]
This is Fixed
- https://chembl-glados.herokuapp.com/acknowledgements/
- https://chembl-glados.herokuapp.com/db_schema
- https://chembl-glados.herokuapp.com/faqs/
