### ISSUE TITLE
Assay Report Card: add assay parameters section

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#785]
As in https://github.com/chembl/chembl_interface/issues/33

**Comment by agaulton** [comment]
See for example: https://www.ebi.ac.uk/chembl/old/assay/inspect/CHEMBL1038125

Assay parameters are already in the assay web service, just need to include the standard_type, standard_relation, standard_value (or standard_text_value) and standard_units in interface on assay report card.

**Comment by nclopezo** [comment]
https://github.com/chembl/GLaDOS-es/issues/32 needs to be done first.

**Comment by nclopezo** [comment]
This is done:
https://www.ebi.ac.uk/chembl/assay_report_card/CHEMBL1038125/
