### ISSUE TITLE
Improve molecule features icons

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#790]
Some of the icons do not reflect the concept properly. Also we would like to see if we can modify them by ourselves without having to contact other teams about that. We need to:

- [x]  See if we can modify the icons and generate the font by ourselves. 
- [x] Discuss about some icons that can be improved and replace them. 
- [x]  Change colour of second row to a more "bluish" colour.

**Comment by laurajunco** [comment]
Things to be done:

- [ ] Center icons in container boxes

- [ ] Improve the level of detail and contrast icons have in desktop screens

- [ ] Polymer Icon: make it bigger

- [ ] 'Discontinued' icon: make it more readable

- [ ] The Chirality icons: the hands should have the same kind of icon

- [ ] Topical icon: make it more like a cream

- [ ] OTC icon: make it more readable, only the basket

- [ ] Enzyme icon: more like pacman



- [ ] Think of a better icon for Inorganic molecules

**Comment by laurajunco** [comment]
Two more things to do:

- [ ] Update compound placeholder images with new icons

- [ ] Test a few other combinations of green and blue in the context of the results page
