### ISSUE TITLE
Main page: Add section with github details

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#807]
We need a section on the main page that shows the following:
- Latest commit on master branch in this repository.
- Link to the repository.
- Link to create a new issue. 

Similar to the one in the materialise page:

<img width="1104" alt="screen shot 2018-05-24 at 09 25 54" src="https://user-images.githubusercontent.com/1944922/40473615-97512bc8-5f34-11e8-983e-1dc423b51699.png">

**Comment by laurajunco** [comment]
This is deployed: https://chembl-glados.herokuapp.com/

**Comment by nclopezo** [comment]
Thank you!
