### ISSUE TITLE
Organise the styles

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#827]
We currently have most of the styles in a huge scss file, which is easy to read for a machine, but not for a human. We need to organise this in a better way that is more consistent and maintainable. 
The tasks are:

- [x] Split the current scss file into different sections (for example: visualisations, report cards, results page)
- [x] Create scss variables for common items (for example: colour palette, paddings, borders, z-indexes)
- [x] Create a page like this one with the result of the standardisation: https://la-silla-vacia.github.io/lsv-components/docs/tokens

**Comment by laurajunco** [comment]
This is deployed: https://chembl-glados.herokuapp.com/design_components/

**Comment by nclopezo** [comment]
Thanks a lot!
