### ISSUE TITLE
Filtering in top bar after results are displayed doesn't work

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#849]
Hello, 
When I search for a compound (CHEMBL185) then the results are returned without any problem. BUT then I click on the top bar to filter by e.g. 'tissues', or 'cells' rather than 'compound', then this doesn't seem to work... See snapshot: 
![screen shot 2018-06-06 at 17 03 16](https://user-images.githubusercontent.com/32895834/41050626-d59d6f5a-69ab-11e8-973f-a797769c9b37.png)

**Comment by nclopezo** [comment]
We are aware of this. I will try to fix it while @juanfmx2 is on holiday.

**Comment by nclopezo** [comment]
Hi @FionaEBI,

This should be fixed now. The tabs should work, and also the search results page now should load faster. By the way, now you can also use new EBI url, which will become the official one: https://www.ebi.ac.uk/chembl/beta/

**Comment by nclopezo** [comment]
the bug with Safari has been fixed by https://github.com/chembl/GLaDOS/pull/865
