### ISSUE TITLE
Clicking on compound suggestion returns compounds that contains the word 'compound' in their name

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#850]
If you search for FLUOROURACIL and click on the suggested CHEMBLID, you get this:
![image](https://user-images.githubusercontent.com/26281131/41050918-99cda9e4-69ac-11e8-9cc8-073b8d36f1c5.png)

**Comment by nclopezo** [comment]
This is the same issue described by https://github.com/chembl/GLaDOS/issues/870
