### ISSUE TITLE
Changes to "Want to know more" section

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#869]
- [x]  **Internships**

Change text to:
Internships at ChEMBL 
(leave old image)

We are looking for skilled students with scientific or programming experience to join our team for 3-6 month internships. This is not necessarily a summer internship program, you can start whenever convenient for you after being accepted.

How to apply?
Just send your CV to kholmes @ ebi.ac.uk with 'ChEMBL Tech Internships' subject.

When to apply?
You can apply anytime but we will only contact selected candidates.

Will I get paid?
The internship is paid 800 GBP per month OR funded by your alma mater (whatever is better for you).

- [x]  **Funding**

change text to:
Current Awards
2014-2019: Wellcome Trust (Strategic Award WT086151/Z/08/Z). The member states of EMBL
2016-2022: European Commission Horizon 2020. Toxicity Testing and Risk Assessment in the 21st Century EU-ToxRisk (681002)
2015-2019: Coordinated Research Infrastructures Building Enduring Life-science Services CORBEL (654248)
2018-2023: Illuminating the Druggable Genome NIH grant 1U24CA224370-01
2014-2020: Open Targets
2013-2018: European Commission FP7 HeCaTos - Safety prediction (602156)
2017-2022: European Commission/IMI2 eTRANSAFE - Enhacing TRANslational SAFEty Assessment through Integrative Knowledge Management (777365)
2017-2021: European Commission/IMI2/TransQST - Translational quantitative systems toxicology to improve the understanding of the safety of medicines (116030)

Past Awards
2009-2016: European Commission/IMI IMI eTox (115002)
2014-2016: Illuminating the Druggable Genome NIH grant 1U54CA189205-01
2008-2014: Chemogenomics at the EBI, WT Strategic award 086151/Z/08/Z
2012-2015: European Commission FP7 BioMedBridges (284209)
2014-2014: Pistoia Alliance Application of HELM Nomenclature to ChEMBL peptide content.
2012-2014: Medicines for Malaria Ventures - Malaria Data Deposition Portal
2012-2014: European Commission/IMI IMI Open PHACTS (115191)
2011-2014: European Commission FP7 DiXa (283775)
2011-2014: BBSRC/EPSRC/MRC SMSDrug.net - Chemical Biology Networking (EP/I037229/1)
2013-2013: Syngenta - Herbicide and Insecticide Data for ChEMBL
2011-2013: GSK - ADMET SARfari
2009-2013: European Commission ESFRI EU-OpenScreen (261861)
2010-2011: Pfizer - Druggability Analysis

**Status**
Should we just limit this to the ChEMBL webpages/webservices?

**FAQs**
These should be copied over from the old interface FAQs but the interface examples will need to be updated for the new interface

**Comment by eloyfelix** [comment]
internship salary is 1000 GBP per month since January I think. We definitely should also update this! :)

**Comment by anne123** [comment]
I thought that it was GBP 1000 too but on the intranet it still says GBP 800 http://tsc.ebi.ac.uk/article/inviting-trainee-or-visitor 

We should double check this.

**Comment by nclopezo** [comment]
The recreation of the FAQs are represented by https://github.com/chembl/GLaDOS/issues/871

**Comment by nclopezo** [comment]
@anne123, @eloyfelix, the internship document has been updated. I wrote 1000 GBP because that is what Laura was being paid.

**Comment by nclopezo** [comment]
**This is ready:**
https://www.ebi.ac.uk/chembl/beta/
