### ISSUE TITLE
Search returns targets with the string "target" as part of the target name

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#870]
seems to return targets with the string "target" as part of the target name e.g PDE4 also returns 
CHEMBL3883304 (Aurora kinase A/Targeting protein for Xklp2) and others
https://www.ebi.ac.uk/chembl/beta/g/#search_results/targets/query=Targets%20PDE4

**Comment by anne123** [comment]
Also today noticed that something similar happens when you search for a document e.g. searching for TG-GATES in documents also returns documents with the word documents in the abstract eg https://www.ebi.ac.uk/chembl/beta/g/#search_results/all/query=Documents%20TG-GATES

we should check other entities such as compounds/assays etc

**Comment by anne123** [comment]
Is there any news on when this will be fixed as it looks quite bad from a user perspective.  I've been looking at a user query related to a target falcipain and it is again showing a lot of non related targets with target in the name.

**Comment by juanfmx2** [comment]
This, and a group of other fixes will be ready soon. I'm looking forward to have them deployed  by tomorrow

**Comment by anne123** [comment]
Thanks Juan 
That will be good - let me know if I need to do any testing
