### ISSUE TITLE
molecule type by approval graph is not working properly

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#916]
If you select any of the small molecule sections it says there is no data. e.g. https://www.ebi.ac.uk/chembl/beta/g/tiny/jXzgAbpVwLvdC/3RkCNbTg==

Also https://www.ebi.ac.uk/chembl/beta/g/tiny/wo6bnCeW4fd6v8Y6N9VaFQ== returns 3 compounds but the section of the bar chart Year 2015, unknown says there are 4.  

I think there are other examples where the numbers are wrong but equally many are correct.

**Comment by nclopezo** [comment]
**This is fixed:** 
https://www.ebi.ac.uk/chembl/beta/
Now all the data comes from drugs only.
