### ISSUE TITLE
Table header blinks when you scroll

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#919]
It seems that when the table header is going to be pinned it can cause some blinking. It can be reproduced by going to 
https://www.ebi.ac.uk/chembl/beta/compound_report_card/CHEMBL1256484/
And scrolling to this position:

<img width="1345" alt="screen shot 2018-08-07 at 09 33 40" src="https://user-images.githubusercontent.com/1944922/43764431-59140944-9a25-11e8-95c5-c64e97d168f0.png">

**Comment by nclopezo** [comment]
This is fixed:
https://www.ebi.ac.uk/chembl/beta/compound_report_card/CHEMBL59/
@nbosc

**Comment by nbosc** [comment]
nicely fixed :)
