### ISSUE TITLE
Add protein target classification levels L3, L4 to Browse Target Filters

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#924]
Can we add some other levels L3, L4 etc (maybe as options) as I think a use case is to use the wheel to see a subset but then you might want to filter more specifically when you realise you have a large amount of data.  This would be preferable to having to go back to the start to do this.

**Comment by nclopezo** [comment]
this is done:
https://www.ebi.ac.uk/chembl/beta/g/#browse/targets

**Comment by nclopezo** [comment]
@anne123
