### ISSUE TITLE
Assign the right document to each assay

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#94]
Currently, on the Assay Report Cards, all the Journal links point to the same article.

**Comment by nbosc** [comment]
Ahahah, was no longer thinking about this issue! I've just been trapped again...
Don't you think that something that should be fixed asap?

**Comment by mnowotka** [comment]
Not asap but in the due course when we concentrate on removing fake data from report cards, possibly we will start working on this in two weeks from now.

**Comment by nclopezo** [comment]
This was done some weeks ago:

https://www.ebi.ac.uk/chembl/beta/assay_report_card/CHEMBL674114/
https://www.ebi.ac.uk/chembl/beta/assay_report_card/CHEMBL851463/

**Comment by nbosc** [comment]
I trust you :)
