### ISSUE TITLE
Review data downloads

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#942]
When downloading data you get (I think) all the fields you can view regardless of what you select.  I think this is probably OK but maybe not what people expect.  However the field list could be more useful as to have a quick look at a dataset I would also like to see pref_name, parent_molregno and some more physchem data.  Maybe the way to do this is to add these fields to those displayed?

parent_molregno is important as it looks as if you have data on more compounds than you do and there is no obvious way to see this.

Also the max number of rows that can be downloaded.  Can this be increased?  For example I think it would be reasonable to expect to be able to download all the data on a target.  Doing this for dopamine D2 (human) is 16,000 data points and 10,000 is the current maximum

**Comment by nclopezo** [comment]
Hi Anne, 

If you use 'Command -', you can zoom out the interface pages, I was able to take this screenshot in one go:

![screen shot 2018-08-16 at 14 41 50](https://user-images.githubusercontent.com/1944922/44212366-1327a680-a163-11e8-825d-ccace1824d19.png)

Also I we can improve this by doing the following 2 things:

- [ ] Place the sections in the report cards in the same order as in the old interface. 
- [ ] Allow the user do drag and drop items in the scrollspy and reorder the sections as they wish:
![screen shot 2018-08-16 at 14 48 46](https://user-images.githubusercontent.com/1944922/44212545-89c4a400-a163-11e8-9624-7cf5ddae4100.png)

**Comment by nclopezo** [comment]
There is no limit anymore for the items in the downloads. The review of the fields in the downloads will be handled in https://github.com/chembl/GLaDOS/issues/1105
