### ISSUE TITLE
Target predictions - target names missing

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#972]
This is missing from the table for example:
https://www.ebi.ac.uk/chembl/beta/compound_report_card/CHEMBL1643/

**Comment by nclopezo** [comment]
This is fixed

**Comment by eloyfelix** [comment]
Target predictions "Target Pref. Name" is missing again

**Comment by nclopezo** [comment]
This was included in the indexation but now is missing. Something must have changed in elasticsearch:
https://www.ebi.ac.uk/chembl/glados-es/chembl_molecule/_doc/CHEMBL1643

```javascript
"target_predictions": [
        {
          "in_training": "0",
          "target_organism": "Homo sapiens",
          "target_tax_id": "9606",
          "probability": "0.00021844014",
          "target_chembl_id": "CHEMBL4261",
          "target_accession": "Q16665",
          "pred_id": 136987,
          "molecule_chembl_id": "CHEMBL1643",
          "value": 1
        },
        {
          "in_training": "0",
          "target_organism": "Bos taurus",
          "target_tax_id": "9913",
          "probability": "0.00002724577",
          "target_chembl_id": "CHEMBL4975",
          "target_accession": "P28190",
          "pred_id": 136992,
          "molecule_chembl_id": "CHEMBL1643",
          "value": 1
        },
        {
          "in_training": "0",
          "target_organism": "Rattus norvegicus",
          "target_tax_id": "10116",
          "probability": "0.99999999421",
          "target_chembl_id": "CHEMBL318",
          "target_accession": "P25099",
          "pred_id": 136951,
          "molecule_chembl_id": "CHEMBL1643",
          "value": 1
        },
```

@juanfmx2

**Comment by agaulton** [comment]
FYI a user also reported this issue: https://twitter.com/ydu_sci/status/1153314548541034496

**Comment by nclopezo** [comment]
I just deployed some changes that fix the problems with the sorting. It seems that the pref name disappeared from the index and the response doesn't contain it anymore. I created this issue in our elasticsearch repository https://github.com/chembl/GLaDOS-es/issues/37

**Comment by nclopezo** [comment]
To be clear, this can't be closed until chembl/GLaDOS-es#37 is resolved.

**Comment by agaulton** [comment]
If we are going to do target predictions on the fly, this may no longer be needed...

**Comment by nclopezo** [comment]
This is no longer needed.
