### ISSUE TITLE
substructure search

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#981]
Please could we make the default on the substructure search results page to be NOT to show the substructure in red (change the toggle) as it makes a lot of sensible molecules look really weird?
e.g. 
https://www.ebi.ac.uk/chembl/beta/g/#substructure_search_results/CC(C)C(%3DO)NC(CCN(C)C)C1C%3DCC%3DCC%3D1

**Comment by agaulton** [comment]
This is changed now
